#!/usr/bin/env python3
"""Write complete generate_batch_c_posts.py with 250 topics."""
import textwrap
from pathlib import Path

OUT = Path("/Users/michael/Desktop/my-portfolio/scripts/generate_batch_c_posts.py")

# category, suffix, title, description, tags|pipe, keywords, hook, tool, when, mistake
RAW = []

def R(*a):
    RAW.append(a)

# Kubernetes 28
R("Kubernetes","pod-disruption-budgets","Pod Disruption Budgets for Safe Cluster Upgrades","Design PodDisruptionBudgets that protect quorum during node drains, cluster upgrades, and Karpenter consolidation.","DevOps|Kubernetes|SRE","PodDisruptionBudget, PDB, node drain","At 2 a.m. during a node pool upgrade, Redis Sentinel lost quorum because three pods were evicted simultaneously.","PodDisruptionBudget","Before enabling cluster autoscaler consolidation or your first production node drain.","Setting minAvailable to 100% on stateless Deployments blocks all voluntary evictions.")
R("Kubernetes","vertical-pod-autoscaler","Vertical Pod Autoscaler: Recommendations vs Auto Mode","Operate VPA in recommendation or auto mode: right-size requests, avoid OOM loops, and coordinate with HPA.","DevOps|Kubernetes|Cost Optimization","VPA, vertical pod autoscaler, right-sizing","Finance flagged 40% over-provisioned CPU requests while pods averaged a fraction of allocated resources.","Vertical Pod Autoscaler","Enable VPA recommendations first on batch tiers before auto mode.","Running VPA auto on the same Deployment as HPA on CPU causes scaling fight loops.")
R("Kubernetes","horizontal-pod-autoscaler-custom-metrics","HPA with Custom and External Metrics","Scale Deployments on Prometheus, KEDA, or cloud queue depth using HorizontalPodAutoscaler v2.","DevOps|Kubernetes|Observability","HPA, custom metrics, KEDA","Checkout latency breached SLO while CPU sat flat—queue depth existed but HPA watched CPU only.","HPA v2","When CPU/memory do not correlate with user-visible latency or backlog.","Scaling on CPU alone during I/O-bound spikes never adds pods.")
R("Kubernetes","network-policies-default-deny","Kubernetes Network Policies: Default Deny Baseline","Implement default-deny network policies with explicit egress and ingress allowlists.","DevOps|Kubernetes|Security","network policy, default deny","Compliance demanded default-deny; the first policy broke DNS because kube-dns egress was missing.","NetworkPolicy","Roll out namespace by namespace after inventorying flows.","Applying deny-all without DNS egress breaks every pod overnight.")
R("Kubernetes","resource-quota-limitrange","ResourceQuota and LimitRange for Multi-Tenant Namespaces","Govern namespace consumption with ResourceQuota and LimitRange defaults.","DevOps|Kubernetes|Platform","ResourceQuota, LimitRange","Notebooks requested 8 CPU each with no limits and starved production scheduling.","ResourceQuota","When onboarding tenant namespaces or opening self-service namespace creation.","Quotas without LimitRange let pods with missing requests bypass fairness.")
R("Kubernetes","ingress-nginx-rate-limiting","Ingress-NGINX Rate Limiting and Edge Protection","Configure NGINX Ingress rate limits, connection limits, and edge throttling.","DevOps|Kubernetes|Security","ingress-nginx, rate limiting","A scraping bot hammered search at 2k RPS before application-level limits existed.","Ingress-NGINX","Before public launch or after abuse on unauthenticated endpoints.","Global limits that throttle health checks flip synthetic monitors.")
R("Kubernetes","etcd-backup-restore-ops","etcd Backup and Restore Operations","Automate etcd snapshots, validate restore drills, and document RTO.","DevOps|Kubernetes|SRE","etcd backup, snapshot, restore","Restored etcd from a snapshot taken mid-compaction—it was unusable.","etcd snapshots","For every self-managed control plane before declaring DR complete.","Backups without tested restore are wishful thinking.")
R("Kubernetes","karpenter-nodepool-tuning","Karpenter NodePool Tuning for Cost and Speed","Configure Karpenter NodePools: instance families, consolidation, limits.","DevOps|Kubernetes|Cost Optimization","Karpenter, NodePool, consolidation","Spot reclamation spiked; batch jobs restarted because consolidation was too aggressive.","Karpenter NodePool","When moving from Cluster Autoscaler or when spot interruptions spike.","Allowing all instance types picks wrong shapes for workloads.")
R("Kubernetes","secrets-store-csi-driver","Secrets Store CSI Driver with External Secrets","Mount cloud secrets via CSI and sync rotation with External Secrets Operator.","DevOps|Kubernetes|Security","Secrets Store CSI, External Secrets","Weekly DB password rotation required rolling restarts across twelve services.","Secrets Store CSI","When eliminating secret env vars or meeting short-lived credential compliance.","Mounts without rotation polling leave pods on stale credentials.")
R("Kubernetes","topology-spread-constraints","Topology Spread Constraints for Zone Balance","Spread pods across zones and nodes with topologySpreadConstraints.","DevOps|Kubernetes|SRE","topologySpreadConstraints, multi-AZ","An AZ power event took 80% of API pods because replicas piled into one zone.","topologySpreadConstraints","For tier-1 services before declaring multi-AZ HA complete.","DoNotSchedule with skew 1 and too few replicas blocks scheduling.")
R("Kubernetes","cluster-autoscaler-overprovision","Cluster Autoscaler Over-Provisioning Patterns","Use overprovision deployments and priority classes to reduce scale-up latency.","DevOps|Kubernetes|Capacity","cluster autoscaler, overprovision","Black Friday traffic spiked; new nodes took eight minutes while pending pods queued.","Cluster Autoscaler","When pending pod duration during scale-up breaches SLO.","Overprovision without priority classes wastes budget 24/7.")
R("Kubernetes","gpu-node-scheduling","GPU Node Scheduling and Fractional GPUs","Schedule ML workloads on GPU nodes with device plugins, taints, and MIG.","DevOps|Kubernetes|MLOps","GPU scheduling, device plugin","Training jobs pending-scheduled for hours because GPU nodes ran default workloads.","GPU device plugin","Before production ML training or inference on Kubernetes.","Missing taints let non-GPU workloads consume expensive GPU nodes.")
R("Kubernetes","priority-classes-preemption","PriorityClasses and Preemption for Critical Workloads","Define PriorityClasses so critical pods preempt lower-priority batch work safely.","DevOps|Kubernetes|SRE","PriorityClass, preemption","Critical payment pods pending while batch analytics consumed the entire node pool.","PriorityClass","When batch and latency-sensitive workloads share clusters.","Overusing system-cluster-critical devalues the entire priority model.")
R("Kubernetes","init-containers-migration","Init Containers for Migration and Bootstrap","Use init containers for schema migration, config fetch, and dependency wait logic.","DevOps|Kubernetes|Platform","init containers, bootstrap","App containers started before Flyway finished—500 errors until manual restart.","init containers","When apps need ordered startup beyond simple probes.","Heavy migration logic in init without timeout leaves pods stuck Init:0/1.")
R("Kubernetes","sidecar-containers-native","Native Sidecar Containers in Kubernetes 1.29+","Adopt native sidecar containers for logging, mesh, and proxy lifecycle ordering.","DevOps|Kubernetes|Platform","sidecar containers, lifecycle","Istio sidecar terminated before app flushed buffers during rollout.","native sidecar containers","When upgrading to Kubernetes 1.29+ with service mesh or log agents.","Mixing classic and native sidecars without restartPolicy causes confusion.")
R("Kubernetes","cronjob-timezone-dst","CronJob Timezone and DST-Safe Scheduling","Run CronJobs with correct timezones and avoid DST duplicate/skipped runs.","DevOps|Kubernetes|SRE","CronJob, timezone, DST","Billing CronJob ran twice on DST fall-back—double charges until rollback.","CronJob timeZone","For finance, billing, or compliance jobs tied to local midnight.","UTC-only CronJobs that ignore business timezone requirements.")
R("Kubernetes","job-backoff-limits-parallelism","Job Backoff Limits and Parallelism Tuning","Configure Job backoffLimit, parallelism, and completions for batch reliability.","DevOps|Kubernetes|Data Engineering","Kubernetes Job, backoffLimit","A poison message retried 10k times before backoff—cluster API throttled.","Kubernetes Job","Before production batch pipelines on native Jobs.","Unbounded parallelism overwhelming downstream databases.")
R("Kubernetes","statefulset-rolling-update","StatefulSet Rolling Update Strategies","Manage StatefulSet partition updates, OnDelete strategy, and PVC retention.","DevOps|Kubernetes|SRE","StatefulSet, rolling update","Rolling update restarted all Kafka brokers simultaneously despite partition setting.","StatefulSet","For stateful tiers before first in-place version upgrade.","Deleting StatefulSet with wrong PVC retention policy loses data.")
R("Kubernetes","daemonset-upgrade-strategy","DaemonSet Upgrade and Surge Patterns","Upgrade DaemonSet agents with maxUnavailable tuning.","DevOps|Kubernetes|Platform","DaemonSet, rolling update","Log agent upgrade left 30% of nodes on old version—blind spot during incident.","DaemonSet","Before upgrading CNI, log, or security DaemonSets fleet-wide.","maxUnavailable 100% on single-replica-per-node DaemonSets.")
R("Kubernetes","configmap-hot-reload","ConfigMap Hot Reload Without Pod Restart","Reload configuration from ConfigMaps using watchers, sidecars, or Reloader.","DevOps|Kubernetes|Platform","ConfigMap, hot reload","Feature flag change required full Deployment restart for one boolean.","ConfigMap reload","When config changes are frequent and restarts are costly.","Assuming kubelet sync instantly updates in-memory app config.")
R("Kubernetes","downward-api-metadata","Downward API for Pod Metadata Injection","Expose labels, annotations, and resource limits to containers via Downward API.","DevOps|Kubernetes|Platform","Downward API, metadata","Observability agent could not tag metrics with pod version—hardcoded in env.","Downward API","When apps need self-aware metadata without hardcoding.","Projecting sensitive annotations into env visible to all containers.")
R("Kubernetes","ephemeral-storage-limits","Ephemeral Storage Limits and Eviction","Set ephemeral-storage requests/limits and monitor emptyDir pressure.","DevOps|Kubernetes|SRE","ephemeral storage, eviction","Log-heavy pod filled node disk; kubelet evicted unrelated production pods.","ephemeral-storage","For workloads writing logs, caches, or temp files to emptyDir.","Missing ephemeral limits on log or download workloads.")
R("Kubernetes","taints-tolerations-nodepools","Taints, Tolerations, and Dedicated Node Pools","Isolate workloads with taints, tolerations, and dedicated node pools.","DevOps|Kubernetes|Platform","taints, tolerations","GPU and batch workloads competed on same nodes—p99 latency collapsed.","taints and tolerations","When mixing latency-sensitive and batch/GPU tiers in one cluster.","NoEffect tolerations that do not match node taints.")
R("Kubernetes","custom-scheduler-plugins","Custom Scheduler Plugins and Scheduling Profiles","Extend kube-scheduler with plugins for topology, cost, or compliance scoring.","DevOps|Kubernetes|Platform","scheduler plugins","Compliance required EU-only nodes; default scheduler ignored region labels.","scheduler plugins","When default scoring cannot express cost, compliance, or affinity rules.","Custom scheduler without fallback profile blocks all scheduling.")
R("Kubernetes","api-server-audit-logging","API Server Audit Logging for Security and Forensics","Configure audit policies, log backends, and retention for API forensics.","DevOps|Kubernetes|Security","audit logging, API server","Post-incident: no record of who applied cluster-admin RoleBinding.","API audit policy","Before SOC2 audit or after suspicious RBAC change.","Logging RequestResponse for all resources—etcd-sized log volumes.")
R("Kubernetes","rbac-least-privilege","RBAC Least Privilege for Platform Teams","Design Role bindings with least privilege and break-glass paths.","DevOps|Kubernetes|Security","RBAC, least privilege","Contractor retained cluster-admin six months after offboarding.","Kubernetes RBAC","During tenant onboarding and quarterly access reviews.","ClusterRole aggregates that grant wildcard verbs silently.")
R("Kubernetes","service-account-iam-roles","IRSA and Workload Identity for Service Accounts","Bind service accounts to cloud IAM roles without static keys.","DevOps|Kubernetes|Security","IRSA, workload identity","Long-lived AWS keys in Secrets leaked via compromised pod.","IRSA","When pods call cloud APIs—S3, SQS, Secrets Manager.","Annotating wrong IAM role ARN—silent permission failures.")
R("Kubernetes","cert-manager-letsencrypt-dns01","cert-manager DNS-01 with Let's Encrypt","Automate TLS with cert-manager, DNS-01 challenges, and wildcard certificates.","DevOps|Kubernetes|Security","cert-manager, DNS-01","HTTP-01 failed for internal services; wildcard cert manual renewal expired.","cert-manager","When services are not publicly reachable for HTTP-01 validation.","DNS-01 without restricted IAM on Route53.")

print("RAW count after k8s:", len(RAW))
