
def add_rest(R):
    # Helm 14
    R("Helm","helm-chart-testing-ct-lint","Helm Chart Testing with chart-testing and helm-unittest","Validate Helm charts before release with ct lint/install and helm-unittest.","DevOps|Kubernetes|Helm","chart-testing, helm-unittest","Chart bump removed securityContext; Argo synced valid YAML but pods failed admission.","chart-testing","Before publishing charts to OCI.","ct without helm-unittest misses template logic regressions.")
    R("Helm","helm-dependency-management","Helm Dependency Management and Subchart Patterns","Manage Helm dependencies: conditions, aliases, OCI registries, Chart.lock.","DevOps|Kubernetes|Helm","Helm dependencies, Chart.lock","Umbrella chart floating redis range changed persistence defaults.","Helm dependencies","When composing platform charts with stateful subcharts.","Floating dependency ranges on stateful subcharts.")
    R("Helm","helm-oci-registry-migration","Migrating Helm Charts to OCI Registries","Publish and consume Helm charts from OCI instead of HTTP chart repos.","DevOps|Helm|Supply Chain","Helm OCI, chart registry","HTTP chart repo outage blocked all deploys for four hours.","Helm OCI registry","During chart repo consolidation.","OCI push without immutability—tags overwritten.")
    R("Helm","helmfile-multi-env","Helmfile for Multi-Environment Deployments","Orchestrate multi-env Helm releases with helmfile and gotmpl.","DevOps|Helm|GitOps","helmfile, multi-environment","Twelve near-identical helm upgrade scripts drifted within a month.","helmfile","When managing more than three environment-specific releases.","helmfile without version pinning on remote repos.")
    R("Helm","helm-hooks-weight-order","Helm Hooks: Weights, Ordering, and Cleanup","Configure pre/post install hooks with correct weights and delete policies.","DevOps|Kubernetes|Helm","Helm hooks, hook-weight","DB migration hook ran after app pods—schema mismatch outage.","Helm hooks","When charts run migrations via hooks.","hook-delete-policy without idempotent hooks.")
    R("Helm","helm-values-schema-validation","Helm Values Schema Validation","Enforce values.schema.json on charts to reject invalid input early.","DevOps|Kubernetes|Helm","Helm values schema","Typo set replicas to string—HPA ignored it.","values.schema.json","When platform charts are consumed by many teams.","Schema too permissive—allows dangerous requests.")
    R("Helm","helm-secrets-sops","Helm Secrets with SOPS","Encrypt Helm values with SOPS; decrypt in CI and GitOps.","DevOps|Helm|Security","Helm secrets, SOPS","Plaintext DB passwords in values.yaml in Git history.","SOPS","When secrets must live in Git for GitOps.","SOPS keys in same repo as encrypted files.")
    R("Helm","helm-diff-pre-deploy","Helm Diff Before Deploy in CI","Run helm diff in CI to show manifest changes before upgrade.","DevOps|Helm|CI/CD","helm diff, CI","Blind upgrade changed ClusterIP to LoadBalancer.","helm diff","On every production chart upgrade PR.","Diff against wrong release name.")
    R("Helm","helm-rollback-strategies","Helm Rollback Strategies and Release History","Plan Helm rollback, history limits, and atomic upgrades.","DevOps|Kubernetes|Helm","Helm rollback, atomic","Rollback to revision 3 restored broken config.","Helm rollback","Before first production Helm upgrade on tier-1.","--atomic without adequate probe timeouts.")
    R("Helm","helm-library-chart-patterns","Helm Library Chart Patterns for DRY Templates","Extract shared templates into library charts.","DevOps|Kubernetes|Helm","Helm library chart","Four teams copied identical label helpers—drift broke selectors.","library charts","When three or more charts duplicate helpers.","Library chart version not pinned.")
    R("Helm","helm-post-renderer-kustomize","Helm Post-Renderers with Kustomize","Patch Helm output with kustomize post-renderer.","DevOps|Helm|GitOps","Helm post-renderer, kustomize","Vendor chart could not add required pod labels.","Helm post-renderer","When upstream charts cannot be modified.","Post-renderer patches not tested in CI.")
    R("Helm","helm-release-health-checks","Helm Release Health Checks and Wait Logic","Configure --wait, --timeout, and resource readiness.","DevOps|Kubernetes|Helm","Helm wait, readiness","Helm reported deployed while pods CrashLoopBackOff.","Helm --wait","On all automated Helm upgrades.","Timeout too short for slow-start JVM.")
    R("Helm","helm-chart-signing-provenance","Helm Chart Signing and Provenance","Sign charts with cosign and verify before install.","DevOps|Helm|Security","Helm signing, cosign","Compromised chart mirror served modified templates.","cosign chart signing","Before adopting third-party charts.","Verification in CI but not in GitOps controller.")
    R("Helm","helm-governance-standards","Helm Chart Governance and Platform Standards","Establish org-wide Helm standards and review gates.","DevOps|Helm|Platform","Helm governance","Incident traced to chart missing probes.","Helm standards","When more than five teams publish internal charts.","Standards documented but not enforced in CI.")
