# Unique topic specs for batch-02-part0 (sorted slice indices 500-549)
SLUG_SPECS: dict[str, dict] = {
    "android-fcm-topic-subscriptions": {
        "title": "FCM Topic Subscriptions at Scale",
        "description": "Subscribe to topics with conditional intersections, server-side replay on token rotation, and logout hygiene — without turning Firebase into a per-user database.",
        "focus": "subscribeToTopic churn, Admin SDK replay, conditional expressions, topic naming registry, token rotation, shared tablet logout",
        "section_headings": [
            "Broadcast tower vs token loop",
            "Topic naming and cardinality caps",
            "Client opt-in toggles that survive toggling",
            "Server-owned segments at login",
            "Conditional intersections without nested logic",
            "Logout hygiene on shared devices",
            "Metrics that mean your topic model is rotting",
        ],
        "faq": [
            ("How many FCM topics can one Android app safely use?", "Firebase documents roughly 2,000 topics per project, but practical limits hit earlier when subscribe/unsubscribe churn and server fan-out grow. Treat topics as coarse broadcast channels — region, language, product line — not per-user slots."),
            ("Should topic subscribe happen on client or server?", "Use the Admin SDK on your backend when attributes are known at login — idempotent, auditable, survives reinstall when you replay from server. Client-side subscribeToTopic fits explicit user opt-in toggles."),
            ("What happens to topics when a user logs out?", "Topic membership binds to the FCM token, not your user ID. Unsubscribe sensitive topics before clearing session state; replay server-side subscriptions after onNewToken."),
            ("When are conditional topics enough?", "When you need intersections of coarse segments like premium AND region_us. They support up to five expressions — not nested booleans, not per-SKU personalization."),
        ],
        "code": """```kotlin
suspend fun syncTopics(token: String, segments: UserSegments) = withContext(Dispatchers.IO) {
    api.registerToken(token)
    segments.regions.forEach { region ->
        FirebaseMessaging.getInstance().subscribeToTopic("region_$region").await()
    }
    if (segments.marketingOptIn) {
        FirebaseMessaging.getInstance().subscribeToTopic("marketing_global").await()
    }
}

suspend fun onLogout() {
    FirebaseMessaging.getInstance().unsubscribeFromTopic("account_alerts").await()
    FirebaseMessaging.getInstance().unsubscribeFromTopic("team_favorites").await()
}
```""",
    },
    "android-feature-flags-implementation": {
        "title": "Feature Flags on Android Without Flag Soup",
        "description": "Local vs remote flags, kill switches, and typed evaluation layers that keep Compose screens testable when half your users are on the old path.",
        "focus": "Remote Config vs dedicated flag service, typed FlagReader, default-off kill switches, exposure logging, flag cleanup debt, Hilt-provided evaluation",
        "section_headings": [
            "Remote Config is not always the right flag store",
            "Typed evaluation beats stringly-typed ifs",
            "Kill switches wired before the happy path",
            "Gradual rollout without double-fetch races",
            "Testing both paths in CI",
            "Flag debt and sunset ceremonies",
            "Observability: exposure vs activation",
        ],
        "faq": [
            ("Remote Config or a dedicated feature flag service?", "Remote Config fits simple toggles tied to Firebase. Dedicated services (LaunchDarkly, Unleash, in-house) fit targeting rules, audit trails, and instant rollback at scale."),
            ("Where should flag evaluation live?", "Domain layer or ViewModel — never inside Composable bodies. Composables observe StateFlow<Boolean>; evaluation happens once per screen entry or config refresh."),
            ("How do I test both flag paths?", "Inject a FakeFlagReader in JVM tests; use Remote Config debug overrides on internal builds; maintain a QA menu for forced paths."),
            ("What is a kill switch vs a rollout flag?", "Kill switch defaults off server-side and enables fast disable without app update. Rollout flag defaults on for internal testers and ramps by percentage — different rollback semantics."),
        ],
    },
    "android-firebase-remote-config-strategies": {
        "title": "Firebase Remote Config Strategies That Survive Production",
        "description": "Fetch intervals, real-time updates, parameter groups, and safe defaults when the network is slow or Firebase throttles your app.",
        "focus": "minimumFetchInterval, setDefaultsAsync, activate, real-time RC listener, parameter groups, A/B testing vs feature flags, offline cache behavior",
        "section_headings": [
            "Fetch cadence and throttling reality",
            "Defaults that ship in the APK",
            "activate() vs fetchAndActivate timing",
            "Real-time updates without UI flicker",
            "Parameter groups for team ownership",
            "Personalization without leaking PII keys",
            "When Remote Config is the wrong tool",
        ],
        "faq": [
            ("What minimumFetchInterval should production use?", "3600 seconds or higher for production fetches initiated by users. Lower intervals in debug. Real-time listeners supplement but do not replace sensible fetch policy."),
            ("Do defaults matter if the server always responds?", "Yes — first launch, airplane mode, and throttled fetch all serve defaults. Wrong defaults brick onboarding for hours."),
            ("Remote Config vs A/B Testing?", "RC parameters can power experiments, but Firebase A/B Testing adds statistical analysis. Do not conflate parameter change with measured experiment unless wired through A/B console."),
            ("How handle stale cache after emergency rollback?", "Bump a version parameter, call fetch with zero interval on critical path once, or ship a hotfix that changes default XML — have a runbook for all three."),
        ],
    },
    "android-fitness-api-integration": {
        "title": "Google Fit and Health Connect Fitness Data",
        "description": "Reading steps, workouts, and heart rate through Health Connect and legacy Fit APIs — permissions, aggregation windows, and battery-aware sync.",
        "focus": "Health Connect ExerciseSessionRecord, aggregation queries, Fit migration, permission rationale, background read limits, duplicate data sources",
        "section_headings": [
            "Health Connect as the modern read path",
            "Legacy Fit APIs you still encounter",
            "Permission UX that passes review",
            "Aggregation windows and timezone edges",
            "Deduplicating overlapping data sources",
            "Background sync without waking the device hourly",
            "Presenting fitness data users trust",
        ],
        "faq": [
            ("Health Connect or Google Fit API?", "Health Connect for new apps — unified permission model across fitness apps. Fit REST/API only when supporting legacy integrations or server-side aggregation."),
            ("Can I read fitness data in background?", "Reads are allowed with granted permissions, but frequent polling drains battery. Batch with WorkManager and respect Health Connect change tokens."),
            ("Why do step counts disagree with Samsung Health?", "Multiple sources write steps — dedupe by data origin metadata and prefer Health Connect aggregation APIs over raw sum."),
            ("What permission strings does Play require?", "Declare Health Connect permissions in manifest and show in-app rationale before system sheet — vague 'health data' copy fails review."),
        ],
    },
    "android-foldable-state-posture": {
        "title": "Foldable Posture, Hinge Angle, and State on Android",
        "description": "WindowMetrics, Jetpack WindowManager folding features, and preserving selection across half-folded tabletop mode.",
        "focus": "FoldingFeature state, hinge angle sensor, WindowSizeClass, separating posture from size, SavedStateHandle selection, dual-pane rules",
        "section_headings": [
            "Posture is not the same as width",
            "Reading FoldingFeature without guessing",
            "Tabletop mode UX expectations",
            "Persisting selection across fold transitions",
            "Compose layout switches that do not flash",
            "Testing on emulator vs real hinge hardware",
            "Activity embedding interaction with posture",
        ],
        "faq": [
            ("Do I need Jetpack WindowManager on foldables?", "Yes for reliable FoldingFeature events across OEMs. Raw configuration changes alone miss half-open states."),
            ("Should list-detail split depend on fold angle?", "Combine width thresholds with posture — TABLETOP may want stacked video + controls even when width suggests dual pane."),
            ("ViewModel or rememberSaveable for fold state?", "ViewModel for business selection (selected item id). rememberSaveable for ephemeral UI like scroll position."),
            ("How test without a foldable?", "Use Android Studio foldable emulator profiles and adb shell commands; still verify on at least one physical Fold/Flip before release."),
        ],
    },
    "android-foreground-service-notification-types": {
        "title": "Foreground Service Types and Notification Requirements",
        "description": "Android 14+ foregroundServiceType declarations, matching permissions, and notification content that satisfies policy reviewers.",
        "focus": "foregroundServiceType manifest, specialUse justification, notification channel importance, FGS timeout API 34, type-specific permissions, startForeground timing",
        "section_headings": [
            "Every FGS type maps to a permission",
            "Manifest declarations Play actually reads",
            "Notification content that is not decorative",
            "startForeground deadline and ANR avoidance",
            "specialUse and the declaration form",
            "Timeout behavior on Android 14+",
            "Migrating legacy FGS without type",
        ],
        "faq": [
            ("What happens if foregroundServiceType is missing?", "On Android 14+, starting FGS without declared type crashes or throws SecurityException depending on targetSdk."),
            ("Can one service declare multiple types?", "Yes — declare all types the service may use and pass the matching type to startForeground on each start path."),
            ("What belongs in the FGS notification?", "Ongoing user-visible work description — not blank title, not ads. Match channel importance to user expectation."),
            ("When is specialUse appropriate?", "Rare cases outside defined types — requires Play Console declaration and strong justification; expect scrutiny."),
        ],
    },
    "android-foreground-service-restrictions": {
        "title": "Foreground Service Restrictions by API Level",
        "description": "Background start limits, while-in-use permissions, FGS quotas, and when WorkManager replaces a foreground service entirely.",
        "focus": "Background FGS start ban API 31, whileInUse location/camera/mic, SYSTEM_ALERT_WINDOW myths, dataSync timeout, user-initiated exemption, WorkManager migration",
        "section_headings": [
            "Background start ban timeline",
            "whileInUse vs always permission pairing",
            "User-initiated vs app-initiated starts",
            "FGS quotas and dataSync timeouts",
            "When WorkManager replaces FGS",
            "OEM-specific kill behavior",
            "Policy declarations in Play Console",
        ],
        "faq": [
            ("Can I start FGS from BOOT_COMPLETED?", "Generally no for most types — user must launch app or trigger visible action. Exceptions are narrow (high-priority FCM, etc.)."),
            ("Does whileInUse location allow background FGS?", "Location FGS needs foreground app visibility or qualifying exemption — whileInUse alone does not grant infinite background tracking."),
            ("What is the dataSync FGS timeout?", "Android 15 limits dataSync FGS duration — design upload pipelines to chunk work and hand off to WorkManager."),
            ("How prove user-initiated start?", "Tap on ongoing notification action, in-app button press — document in UX and log for policy audits."),
        ],
    },
    "android-foreground-service-types": {
        "title": "Choosing the Right Foreground Service Type",
        "description": "Map product features to camera, microphone, location, mediaPlayback, and other FGS types without mixing incompatible permissions.",
        "focus": "type matrix, mediaPlayback vs mediaProjection, connectedDevice BLE, health, remoteMessaging, shortService API 34",
        "section_headings": [
            "Type matrix by product feature",
            "mediaPlayback vs mediaProjection split",
            "location FGS and map apps",
            "connectedDevice for BLE companions",
            "remoteMessaging for VOIP-adjacent push",
            "shortService for quick finish work",
            "Combining types without permission sprawl",
        ],
        "faq": [
            ("Which type for music playback?", "mediaPlayback — pairs with MediaSession and ongoing media-style notification."),
            ("Navigation app while backgrounded?", "location type with visible navigation notification; respect background location approval separately."),
            ("BLE sync overnight?", "connectedDevice may fit — verify against latest policy; often WorkManager + periodic sync is safer."),
            ("What is shortService?", "API 34+ type for work finishing within minutes — not a loophole for long downloads."),
        ],
    },
    "android-fragment-result-api-patterns": {
        "title": "Fragment Result API Patterns Without Memory Leaks",
        "description": "setFragmentResult, clearFragmentResultListener, and Navigation Component integration for type-safe callbacks between destinations.",
        "focus": "FragmentManager result keys, viewLifecycleOwner listener scope, NavController back stack, typed bundles vs JSON, process death, Compose Navigation equivalent",
        "section_headings": [
            "Replacing target fragment callbacks",
            "Listener lifecycle and leak traps",
            "Type-safe result wrappers",
            "Navigation graphs and result keys",
            "Multiple listeners on one key",
            "Process death and lost results",
            "Compose Navigation alternatives",
        ],
        "faq": [
            ("Fragment Result API vs shared ViewModel?", "Shared ViewModel for sibling fragments in same graph; Result API for one-shot callbacks from child to parent with clear delivery semantics."),
            ("Why clear listeners in onDestroyView?", "Listeners on activity FragmentManager survive rotation if attached wrong — bind to viewLifecycleOwner."),
            ("Can I pass complex objects?", "Use Parcelable or JSON strings — keep bundles small; large payloads belong in repository with id reference."),
            ("Does this work with Compose Navigation?", "Prefer Navigation Compose savedStateHandle or explicit callback routes — Fragment Result API is FragmentManager-centric."),
        ],
    },
    "android-full-screen-intent-permission": {
        "title": "Full-Screen Intent Permission on Android 14+",
        "description": "USE_FULL_SCREEN_INTENT is special access — alarm and call apps must justify it, others should degrade to high-priority notifications.",
        "focus": "canUseFullScreenIntent, NotificationManager policy, alarm clock role, incoming call UX, Play declaration, fallback heads-up",
        "section_headings": [
            "Who actually gets full-screen intent",
            "Checking canUseFullScreenIntent at runtime",
            "Alarm and call app exemptions",
            "High-priority notification fallback",
            "Play Console declaration workflow",
            "User settings that revoke access",
            "Testing incoming call flows on Pixel vs Samsung",
        ],
        "faq": [
            ("Do all apps get full-screen intents on Android 14?", "No — only apps granted permission or qualifying use cases (alarm, call). Others must use heads-up notifications."),
            ("How check if my app can use FSI?", "NotificationManager.canUseFullScreenIntent() on API 34+ before relying on full-screen activity launch."),
            ("What if user disables full-screen notifications?", "Degrade gracefully — show heads-up and in-app incoming UI when foreground."),
            ("Chat app incoming call — allowed?", "If not default dialer/phone role, expect denial — design VoIP UX without assuming FSI."),
        ],
    },
    "android-fused-location-provider": {
        "title": "Fused Location Provider: Priority, Intervals, and Battery",
        "description": "LocationRequest priorities, batching, last location cache, and switching to passive updates when the map is not visible.",
        "focus": "Priority.PASSIVE vs HIGH_ACCURACY, setWaitForAccurateLocation, getLastLocation staleness, LocationCallback lifecycle, batching maxWaitTime",
        "section_headings": [
            "Priority tradeoffs in plain language",
            "Last location cache and staleness",
            "Lifecycle-bound LocationCallback",
            "Batching fixes for burst updates",
            "Passive updates when app is idle",
            "Play Services availability failures",
            "Handoff to foreground service for navigation",
        ],
        "faq": [
            ("HIGH_ACCURACY vs BALANCED_POWER?", "HIGH_ACCURACY for turn-by-turn; BALANCED for city-level features; PASSIVE when piggybacking on other apps' fixes."),
            ("Is getLastLocation enough for checkout?", "Only if freshness threshold met — check elapsedRealtimeNanos vs your SLA."),
            ("Why location stops after screen off?", "Background limits — pair with FGS for navigation or reduce to geofence/WorkManager for periodic checks."),
            ("Google Play services missing on device?", "Feature-detect and show error — Chinese OEM devices may lack GMS."),
        ],
    },
    "android-geofencing-battery-efficient": {
        "title": "Geofencing Without Draining the Battery",
        "description": "GeofencingClient transition types, initial trigger traps, radius sizing, and combining geofences with WorkManager for server sync.",
        "focus": "GEOFENCE_TRANSITION_ENTER/EXIT/DWELL, INITIAL_TRIGGER flag, max geofence count, pending intent mutability, mock location detection",
        "section_headings": [
            "When geofence beats continuous GPS",
            "Radius sizing and false triggers",
            "INITIAL_TRIGGER surprise entries",
            "PendingIntent flags and reboot persistence",
            "Geofence limit and batch registration",
            "Mock location and fraud signals",
            "Syncing geofence events to server reliably",
        ],
        "faq": [
            ("How many geofences can I register?", "100 per app on typical devices — batch strategically and unregister stale regions."),
            ("Why immediate ENTER on register?", "INITIAL_TRIGGER_ENTER fires for geofences user already inside — handle without duplicate server events."),
            ("Geofencing vs Activity Recognition?", "Geofence for place-based triggers; Activity Recognition for walking/driving context — combine carefully to save power."),
            ("Do geofences survive reboot?", "Yes if registered with proper PendingIntent — replay from server on app start to heal drift."),
        ],
    },
    "android-gpu-profiling-renderthread": {
        "title": "GPU Profiling and RenderThread Jank on Android",
        "description": "Systrace/Perfetto GPU queues, RenderThread vs UI thread, overdraw, and Compose-specific GPU layer pitfalls.",
        "focus": "RenderThread, GPU completion fence, Profile GPU Rendering bars, AGI, Compose graphicsLayer, shader compilation jank",
        "section_headings": [
            "UI thread vs RenderThread split",
            "Reading GPU bars without guessing",
            "Shader compilation stutter first launch",
            "Compose graphicsLayer cost",
            "Overdraw on legacy Views",
            "Thermal throttling mid-trace",
            "Fix verification with Macrobenchmark",
        ],
        "faq": [
            ("RenderThread blocked — what now?", "Look for expensive display lists, bitmap uploads, or driver shader compile — reduce layer count and image size."),
            ("Profile GPU Rendering still useful?", "Quick bar chart on device; Perfetto gives deeper timeline for hard cases."),
            ("Compose jank differs from Views?", "Yes — recompositions plus lazy list prefetch interact with GPU — use Composition tracing alongside GPU trace."),
            ("AGI vs Android Studio profiler?", "AGI for Vulkan/GLES deep dives; Studio profiler for CPU+render thread overview."),
        ],
    },
    "android-gradle-managed-devices-testing": {
        "title": "Gradle Managed Devices for CI Android Tests",
        "description": "Define virtual devices in Gradle, run instrumented tests on CI without maintaining emulators manually, and cache system images.",
        "focus": "managedDevices block, aosp/atd images, Gradle Device Manager, sharding, screenshot tests, CI memory limits",
        "section_headings": [
            "Managed devices vs custom CI emulators",
            "Choosing ATD vs AOSP images",
            "Gradle DSL for device matrix",
            "Sharding instrumented tests in CI",
            "Screenshot and golden image tests",
            "CI memory and KVM requirements",
            "When physical devices still win",
        ],
        "faq": [
            ("What are Gradle managed devices?", "Virtual devices declared in build.gradle, provisioned automatically for connectedCheck — no manual AVD management."),
            ("ATD images for CI speed?", "Android Test Devices images boot faster — good for unit-adjacent instrumented tests; less OEM fidelity."),
            ("Can managed devices replace Firebase Test Lab?", "Complement — local GMD for PR checks, Test Lab for wide device matrix nightly."),
            ("How parallelize without OOM?", "Limit maxParallelDevices and shard by Gradle test options — CI runners have finite RAM."),
        ],
    },
    "android-graphics-layer-compose": {
        "title": "graphicsLayer in Compose: When It Helps and Hurts",
        "description": "Hardware layers for alpha, rotation, and clip — and the memory cost when every list item uses graphicsLayer unnecessarily.",
        "focus": "Modifier.graphicsLayer, renderEffect, clip, rotationZ, layer type auto, elevation interaction, list item overuse",
        "section_headings": [
            "What graphicsLayer actually allocates",
            "Alpha animation without invalidating layout",
            "Rotation and clip for cards",
            "RenderEffect blur cost on older GPUs",
            "LazyColumn item layer explosion",
            "Interaction with elevation and shadows",
            "Debugging layer count in Layout Inspector",
        ],
        "faq": [
            ("graphicsLayer vs drawWithCache?", "graphicsLayer promotes to display list layer for transforms; drawWithCache for custom drawing reuse — different tools."),
            ("Why did memory spike after animation?", "Each layer is an offscreen buffer — remove layer when animation completes."),
            ("Blur with RenderEffect on list items?", "Avoid — one blurred header maybe; never per-row blur on scroll."),
            ("Does graphicsLayer help scroll performance?", "Sometimes for complex item transforms — measure; default items rarely need it."),
        ],
    },
    "android-graphql-apollo-android": {
        "title": "Apollo GraphQL on Android Production Patterns",
        "description": "Codegen operations, normalized cache, auth header interceptors, and error handling that does not treat GraphQL errors as HTTP 200 success.",
        "focus": "Apollo Kotlin 3/4, SqlNormalizedCache, interceptors, @ApolloExperimental, websocket subscriptions split, R8 keep rules",
        "section_headings": [
            "Codegen vs manual operations",
            "Normalized cache invalidation strategy",
            "Auth refresh in OkHttp interceptor chain",
            "GraphQL errors vs network errors",
            "Pagination with cache merge policies",
            "R8 and ProGuard for generated models",
            "Testing with mock web server",
        ],
        "faq": [
            ("Apollo normalized cache or Room?", "Apollo cache for GraphQL graph; Room for offline-first domain — many apps use both with clear boundaries."),
            ("How handle token refresh?", "Authenticator interceptor on OkHttp — single-flight refresh to avoid thundering herd on 401."),
            ("GraphQL returns 200 with errors array?", "Check response.errors explicitly — do not assume data non-null means success."),
            ("Subscriptions on mobile?", "WebSocket subscriptions drain battery — prefer push + query for most consumer apps."),
        ],
    },
    "android-graphql-subscriptions-websocket": {
        "title": "GraphQL Subscriptions over WebSocket on Android",
        "description": "Apollo subscription transport, reconnect backoff, auth on connection_init, and when push notifications replace live sockets.",
        "focus": "WebSocketSubscriptionTransport, connection_init payload, graphql-ws protocol, backoff, foreground requirement, battery",
        "section_headings": [
            "When subscriptions beat push+poll",
            "WebSocket lifecycle on mobile networks",
            "connection_init auth and token expiry",
            "Reconnect state machine",
            "Foreground service for trading apps",
            "Switching to SSE or FCM for scale",
            "Testing flaky networks with Charles",
        ],
        "faq": [
            ("Subscriptions in background?", "Unreliable — socket killed in Doze. Use FCM for wake + snapshot query for consumer apps."),
            ("Auth refresh on open socket?", "Close and reconnect with new connection_init payload — mid-connection refresh is server-specific."),
            ("Apollo vs custom WebSocket?", "Apollo handles protocol framing — custom only if server uses nonstandard subscription protocol."),
            ("How detect silent dead socket?", "Server ping/pong or client heartbeat with read timeout — OkHttp ping intervals help."),
        ],
    },
    "android-grpc-mobile-client-kotlin": {
        "title": "gRPC Mobile Clients in Kotlin",
        "description": "Grpc-Kotlin coroutine stubs, channel credentials, deadline timeouts, and protobuf lite for APK size on Android.",
        "focus": "ManagedChannel, coroutine stubs, protobuf lite, TLS, gzip, keepalive, R8 rules, grpc-android dependency",
        "section_headings": [
            "Coroutine stubs vs blocking stubs",
            "Channel lifecycle and shutdown",
            "Deadlines on every RPC",
            "Protobuf lite and APK size",
            "TLS pinning interaction",
            "Keepalive on cellular NAT",
            "R8 keep rules for generated code",
        ],
        "faq": [
            ("gRPC or REST for mobile?", "gRPC for high-throughput internal APIs with streaming; REST/GraphQL for broader client compatibility and CDN caching."),
            ("Must I use protobuf lite?", "Recommended on Android — full protobuf jars bloat DEX and method count."),
            ("How set RPC timeout?", "withDeadlineAfter on stub — never infinite wait on UI-critical paths."),
            ("Streaming RPC in background?", "Treat like WebSocket — foreground or user-visible sync; cancel on lifecycle stop."),
        ],
    },
    "android-handwriting-stylus-apis": {
        "title": "Handwriting Stylus APIs on Android",
        "description": "Stylus handwriting delegation, MotionEvent tool types, and when to use Ink API vs platform handwriting-to-text.",
        "focus": "HandwritingDelegator, MotionEvent.TOOL_TYPE_STYLUS, palm rejection, low latency ink, EditText handwriting bounds",
        "section_headings": [
            "Platform handwriting vs custom ink engine",
            "Tool type and button state on MotionEvent",
            "Palm rejection expectations",
            "Handwriting bounds on text fields",
            "Latency budgets users feel",
            "Samsung S Pen vs generic stylus",
            "Accessibility when ink is primary input",
        ],
        "faq": [
            ("HandwritingDelegator for note apps?", "Use when you want system handwriting conversion in text fields; custom canvas for drawing apps."),
            ("How detect stylus vs finger?", "MotionEvent getToolType and check historical pressure — do not assume all touches are finger."),
            ("Palm rejection guaranteed?", "OEM-dependent — still provide undo and eraser for false strokes."),
            ("Compose stylus support?", "PointerInput with stylus type filters — Ink API for low-latency rendering path."),
        ],
    },
    "android-haptic-feedback-compose": {
        "title": "Haptic Feedback in Jetpack Compose",
        "description": "LocalHapticFeedback, performHapticFeedback on interop views, and semantic haptics for Material 3 components.",
        "focus": "LocalHapticFeedback.current, HapticFeedbackType, remember interactionSource, Clickable ripple+haptic, user haptic disabled setting",
        "section_headings": [
            "LocalHapticFeedback vs View haptics",
            "Mapping UI events to HapticFeedbackType",
            "Toggle and slider confirmation buzz",
            "Respecting system haptic off setting",
            "Custom composable haptic guidelines",
            "Game vs utility haptic density",
            "Testing haptics on emulators",
        ],
        "faq": [
            ("How trigger haptic in Compose?", "LocalHapticFeedback.current.performHapticFeedback(HapticFeedbackType.Click) inside gesture callback."),
            ("Emulator haptics?", "No physical feedback — test on device; log haptic calls in debug."),
            ("User disabled haptics globally?", "System ignores calls — do not rely on haptic for sole confirmation; pair with visual state."),
            ("LongPress vs Click haptic?", "Use appropriate HapticFeedbackType — LongPress for drag start, Confirm for success actions."),
        ],
    },
    "android-haptics-vibration-effects": {
        "title": "VibrationEffect and Haptic Primitives on Android",
        "description": "Predefined effects, composition primitives, amplitude control, and VibrationManager on supported hardware.",
        "focus": "VibrationEffect.createPredefined, Composition primitives, amplitude, areEffectsSupported, VibrationManager, deprecated Vibrator API",
        "section_headings": [
            "Predefined effects catalog",
            "Composition for custom patterns",
            "Amplitude control hardware matrix",
            "VibrationManager vs legacy Vibrator",
            "Ringtone vs haptic separation",
            "Policy and Play restrictions on vibration",
            "Fallback when effects unsupported",
        ],
        "faq": [
            ("VibrationEffect vs Vibrator.vibrate(long)?", "VibrationEffect is the modern API with predefined semantic effects — legacy duration-only API is coarse."),
            ("Check device support?", "Vibrator.areEffectsSupported() before composition — degrade to Click predefined."),
            ("Can haptics drain battery?", "Short clicks negligible; long repeating patterns annoy users and fail policy — keep utility haptics brief."),
            ("Compose integration?", "Call through LocalHapticFeedback when possible — reaches system haptic layer without direct Vibrator."),
        ],
    },
    "android-heads-up-notification-control": {
        "title": "Heads-Up Notifications: Priority Without Abuse",
        "description": "NotificationChannel importance, fullScreenIntent fallback, rate limits, and avoiding notification spam that triggers user disables.",
        "focus": "IMPORTANCE_HIGH, setFullScreenIntent fallback, notification cooldown, group summary, FSI permission, bubble alternative",
        "section_headings": [
            "Channel importance is the gate",
            "When heads-up is appropriate",
            "Cooldown patterns for chat apps",
            "Grouping to reduce HUN spam",
            "fullScreenIntent without permission",
            "User disable cascade after spam",
            "Measuring notification-driven uninstalls",
        ],
        "faq": [
            ("How force heads-up display?", "High importance channel + priority category — cannot bypass user channel settings on modern Android."),
            ("Chat message every heads-up?", "Users disable channel — use summary notification and only HUN for mentions or active conversation."),
            ("Heads-up vs bubble?", "Bubbles for ongoing chat; heads-up for time-sensitive interrupt — different permission and UX contracts."),
            ("Importance HIGH on all channels?", "Trains users to ignore you — reserve HIGH for true interrupts."),
        ],
    },
    "android-health-connect-integration": {
        "title": "Health Connect Integration for Android Apps",
        "description": "Reading and writing health records with permission contracts, data origins, and migration from Google Fit direct reads.",
        "focus": "HealthConnectClient, permission controller, readRecords, insertRecords, aggregation, data origin filter, availability check",
        "section_headings": [
            "Availability and module install",
            "Permission request flow ordering",
            "Read vs write record types",
            "Data origin and deduplication",
            "Aggregation API for dashboards",
            "Background reads and change tokens",
            "Migration from legacy Fit reads",
        ],
        "faq": [
            ("Health Connect on all devices?", "Not guaranteed — check HealthConnectClient.getSdkStatus and prompt install on supported devices."),
            ("Write or read-only integration?", "Write requires stronger justification in Play — read-only analytics apps have lighter burden."),
            ("How get step count for today?", "Use aggregate API with time filter — not raw read of all StepRecord rows."),
            ("Multiple apps write same metric?", "Filter by dataOrigin or present combined view with source labels."),
        ],
    },
    "android-health-connect-permissions": {
        "title": "Health Connect Permissions and Play Policy",
        "description": "Manifest permission declarations, in-app rationale, granular record-type permissions, and audit-ready data handling.",
        "focus": "health_permissions.xml, PERMISSION_READ/WRITE constants, rationale Activity, Play health policy, data retention, export delete",
        "section_headings": [
            "Granular permissions per record type",
            "Manifest health_permissions block",
            "Rationale copy that passes review",
            "Request timing in onboarding",
            "Minimum necessary read set",
            "Data retention and deletion UX",
            "Audit logging without PHI in logs",
        ],
        "faq": [
            ("Request all permissions upfront?", "No — request minimum set for feature user is enabling; incremental requests convert better."),
            ("Where declare permissions?", "AndroidManifest health_permissions XML linked from manifest — record types explicit."),
            ("Can I cache health data on server?", "Requires disclosure, encryption, deletion on account erase — Play health policies apply."),
            ("User denies one record type?", "Degrade feature — do not block entire app unless critical."),
        ],
    },
    "android-hid-device-profile": {
        "title": "Android HID Device Profile for Custom Peripherals",
        "description": "BluetoothHidDevice, report descriptors, bonding, and building companion apps that emulate keyboards or game controllers.",
        "focus": "BluetoothHidDevice.registerApp, SDP record, report descriptor bytes, QoS, reconnect bonding, USB HID alternate path",
        "section_headings": [
            "HID device vs HID host roles",
            "Registering HID app with BluetoothHidDevice",
            "Report descriptor design",
            "Bonding and reconnect UX",
            "Latency for game controller use cases",
            "USB HID when BLE is not enough",
            "Security: who may connect",
        ],
        "faq": [
            ("Phone as Bluetooth keyboard?", "HID device profile allows — target device must pair; latency varies by OEM."),
            ("Report descriptor from scratch?", "Use standard descriptors for keyboard/mouse — custom descriptors need USB HID spec knowledge."),
            ("Requires special permission?", "BLUETOOTH_CONNECT and feature declaration — user pairs explicitly."),
            ("HID vs BLE GATT custom?", "HID for OS-level input compatibility; GATT for app-to-app proprietary protocols."),
        ],
    },
    "android-hilt-assisted-injection": {
        "title": "Hilt Assisted Injection for Runtime IDs",
        "description": "AssistedInject factories for ViewModels and workers needing nav args or user ids — wiring @AssistedFactory without Dagger graph explosions.",
        "focus": "AssistedInject, AssistedFactory, @Assisted parameter, ViewModel assisted, Worker assisted, testing with factory",
        "section_headings": [
            "When constructor injection stops working",
            "AssistedFactory interface pattern",
            "Assisted ViewModel with nav args",
            "Assisted Worker with job ids",
            "Avoiding duplicate bindings",
            "Testing with manual factory impl",
            "Common Dagger error messages decoded",
        ],
        "faq": [
            ("AssistedInject vs @HiltViewModel?", "Use assisted when runtime id required (orderId, threadId); plain @HiltViewModel when deps are static singletons only."),
            ("Can @Assisted be SavedStateHandle?", "Yes — common pattern for Navigation args hydration."),
            ("Factory not generated?", "Check @AssistedFactory on interface matching @AssistedInject constructor — KSP/KAPT must run."),
            ("Assisted in multibinding?", "Possible but rare — prefer explicit factory per assisted type for clarity."),
        ],
    },
    "android-hilt-multibindings": {
        "title": "Hilt Multibindings for Plugin Architectures",
        "description": "IntoSet, IntoMap, MapKey, and binding multiple implementations of analytics or deeplink handlers without god-modules.",
        "focus": "IntoSet, IntoMap, StringKey, Dagger multibinding, Set<Plugin>, Map<String, Handler>, testing fake sets",
        "section_headings": [
            "Set multibinding for handler lists",
            "Map multibinding for keyed routers",
            "MapKey design for deeplinks",
            "Module organization without cycles",
            "Order of Set iteration",
            "Testing with replaced bindings",
            "When multibinding is overkill",
        ],
        "faq": [
            ("IntoSet vs manual list in module?", "IntoSet scales when feature modules contribute handlers independently — manual list centralizes and breaks modularization."),
            ("Is Set order guaranteed?", "No — do not rely on iteration order; use explicit priority field if needed."),
            ("Map multibinding duplicate key?", "Compile error — one binding per key unless @IntoMap allows duplicates in advanced cases."),
            ("Replace binding in test?", "TestInstallIn with @TestModule replacing module — or bind empty set for isolation."),
        ],
    },
    "android-image-loading-coil3": {
        "title": "Coil 3 Image Loading on Android",
        "description": "Coil 3 Compose AsyncImage, memory/disk cache keys, transformations, and network interceptors for authenticated CDN images.",
        "focus": "AsyncImage, ImageLoader singleton, memoryCache, diskCache, crossfade, placeholder error, OkHttp network fetcher, SVG decoder",
        "section_headings": [
            "Singleton ImageLoader configuration",
            "Compose AsyncImage parameters",
            "Cache key strategy for signed URLs",
            "Transformations and scale cost",
            "Prefetching in Lazy lists",
            "Error and placeholder UX",
            "Migration from Coil 2 / Glide",
        ],
        "faq": [
            ("Coil 3 vs Glide in 2026?", "Coil 3 is Kotlin-first, Compose-native, lighter for typical app image loads — Glide if heavy custom cache logic exists."),
            ("Signed URL cache busting?", "Custom cacheKey ignoring query signature params — or short TTL disk cache."),
            ("Prefetch LazyColumn images?", "ImageLoader.enqueue ahead of scroll with snapshotFlow — respect memory on low-RAM devices."),
            ("SVG support?", "Add coil-svg decoder module — verify R8 keeps decoder registration."),
        ],
    },
    "android-in-app-review-api": {
        "title": "In-App Review API: Timing, Quota, and Restraint",
        "description": "ReviewManager flow, positive moment gating, and why launchReviewFlow success does not mean the dialog appeared.",
        "focus": "ReviewManagerFactory, requestReviewFlow, launchReviewFlow, quota, policy no incentives, DataStore asked flag, Activity requirement",
        "section_headings": [
            "Quota-gated dialog reality",
            "Positive moment selection",
            "Pre-prompt ethics and policy",
            "Persisting asked state per version",
            "Activity context requirement",
            "Analytics without star outcomes",
            "Fallback feedback path for unhappy users",
        ],
        "faq": [
            ("When show In-App Review?", "After proven value — completed task, streak, successful purchase — never first launch or error recovery."),
            ("Dialog did not appear but flow succeeded?", "Expected — Google controls display quota. Never loop prompt every session."),
            ("Can I offer reward for review?", "No — Play policy prohibits incentives for reviews."),
            ("Custom star rating dialog?", "Manipulative pre-filter ('rate 5 stars') violates policy — neutral feedback path only."),
        ],
    },
    "android-in-app-updates-api": {
        "title": "Play In-App Updates API on Android",
        "description": "Flexible vs immediate updates, UpdateAvailability checks, resume stalled downloads, and UX that does not trap users.",
        "focus": "AppUpdateManager, FLEXIBLE vs IMMEDIATE, InstallStatus, resumeUpdates, min supported version server gate, activity result",
        "section_headings": [
            "Flexible vs immediate choice matrix",
            "Checking update availability",
            "Immediate update for breaking API",
            "Flexible download progress UX",
            "Resume after user killed app mid-download",
            "Server-side min version gate pairing",
            "Testing with internal app sharing",
        ],
        "faq": [
            ("Flexible or immediate update?", "Immediate for critical security/breaking API; flexible for feature updates user can defer."),
            ("User dismissed update — retry?", "Respect cooldown — nagging triggers uninstalls; gate with server minVersion for hard blocks."),
            ("Test in-app updates locally?", "Internal testing track required — debug builds cannot fully simulate Play update flow."),
            ("Update while app backgrounded?", "Flexible completes download — prompt restart with snackbar; immediate blocks UI by design."),
        ],
    },
    "android-ink-api-stylus-low-latency": {
        "title": "Ink API and Low-Latency Stylus Rendering",
        "description": "androidx.ink rendering pipeline, prediction, stroke smoothing, and frame pacing for note-taking apps.",
        "focus": "InkView stroke, latency compensation, prediction, brush models, double buffering, stylus hover, Compose integration",
        "section_headings": [
            "Latency budget on 120Hz displays",
            "Ink stroke model vs Path in Canvas",
            "Prediction and smoothing tradeoffs",
            "Brush textures and pressure curves",
            "Memory for long sessions",
            "Export to PDF or image",
            "Samsung vs Pixel latency differences",
        ],
        "faq": [
            ("Ink API vs custom Canvas drawing?", "Ink API targets low-latency stylus with prediction — custom Canvas simpler for static drawing apps."),
            ("Does prediction misplace strokes?", "Tune prediction for speed vs accuracy — fast writers need more prediction."),
            ("Compose support for Ink?", "Interop InkView in AndroidView or dedicated Compose ink modules as they mature."),
            ("Palm rejection with Ink?", "Combine with MotionEvent cancel policies — Ink does not replace palm logic."),
        ],
    },
    "android-input-connection-custom-ime": {
        "title": "InputConnection and Custom IME Integration",
        "description": "InputConnection contract for custom editors, commitText, composing regions, and handoff with system IME.",
        "focus": "InputConnection, BaseInputConnection, commitText, setComposingRegion, InputMethodManager, EditorInfo, hardware keyboard",
        "section_headings": [
            "InputConnection contract basics",
            "Composing text and Korean/Japanese IME",
            "commitText vs setComposingText",
            "EditorInfo imeOptions alignment",
            "Custom View editors without EditText",
            "Hardware keyboard and key events",
            "Testing IME with Espresso",
        ],
        "faq": [
            ("When implement custom InputConnection?", "Custom text editor (code, markdown) needing fine control — not for standard TextField."),
            ("Why IME ignores my View?", "Must implement onCreateInputConnection and return non-null connection when focused."),
            ("Compose TextField need InputConnection?", "Compose handles internally — custom only for AndroidView interop editors."),
            ("Hardware keyboard without IME?", "Handle KeyEvent directly — InputConnection path may not run."),
        ],
    },
    "android-instant-apps-legacy": {
        "title": "Instant Apps Legacy and Modern Alternatives",
        "description": "Google Play Instant deprecation context, app links + install prompts, and Play Feature Delivery as replacement for try-before-install.",
        "focus": "instant app modules deprecated, Play Feature Delivery on-demand, deep link to install, size limits, user trust",
        "section_headings": [
            "What happened to Instant Apps",
            "Play Feature Delivery on-demand modules",
            "Deep link to full install funnel",
            "Size budget without instant split",
            "Analytics across try and install",
            "Enterprise sideload differences",
            "Migration checklist from instant",
        ],
        "faq": [
            ("Build instant apps in 2026?", "Deprecated path — use App Bundle dynamic features or full install with deferred onboarding."),
            ("Try feature without install?", "Web TWA or lightweight onboarding screen — true instant rare now."),
            ("Instant deep links still work?", "Legacy installs may exist — handle http links with app links to full app."),
            ("Dynamic feature vs instant?", "Dynamic feature installs module on demand after full app install — different UX contract."),
        ],
    },
    "android-intent-redirection-vulnerabilities": {
        "title": "Intent Redirection Vulnerabilities on Android",
        "description": "Unsafe startActivity from forwarded intents, grantUriPermissions traps, and exported Activity audit patterns.",
        "focus": "Intent redirection CVE class, getParcelableExtra untrusted, setComponent explicit, exported false, PendingIntent mutability, StrandHogg",
        "section_headings": [
            "How intent redirection chains work",
            "Exported Activity audit",
            "Never forward raw intents",
            "PendingIntent hijack surfaces",
            "URI permission grant leaks",
            "Lint and security scanner rules",
            "Pen test reproduction steps",
        ],
        "faq": [
            ("What is intent redirection?", "Malicious app sends intent to your exported component which blindly starts embedded intent — attacker reaches private components."),
            ("Fix pattern?", "Validate caller, strip sensitive extras, use explicit ComponentName for internal targets, set exported=false."),
            ("PendingIntent mutability risk?", "Immutable PendingIntent on API 31+ unless mutable required — fillInIntent attacks otherwise."),
            ("Google Play protect detection?", "Pre-launch security scans flag exported activities — fix before production."),
        ],
    },
    "android-jank-frame-metrics-jankstats": {
        "title": "JankStats and Frame Metrics in Production",
        "description": "FrameMetricsAggregator, JankStats library, reporting slow frames to analytics, and connecting jank to Compose recomposition.",
        "focus": "JankStats, FrameMetricsAggregator, jitterPercent, frozen frames, reporting pipeline, sampling rate, privacy",
        "section_headings": [
            "FrameMetrics vs JankStats API",
            "Instrumenting Activities and Compose",
            "Defining jank threshold per screen",
            "Sampling to control telemetry cost",
            "Correlating jank with releases",
            "Frozen frames vs slow frames",
            "Actionable dashboards for mobile teams",
        ],
        "faq": [
            ("JankStats in release builds?", "Yes with sampling — avoid full-rate frame logging on low-end devices."),
            ("What frame duration is jank?", "Typically >16.67ms for 60Hz — adjust for 90/120Hz displays using device refresh rate."),
            ("Compose jank measurement?", "JankStats Compose integration or manual frame clock — combine with recomposition counts."),
            ("Send frame data to analytics?", "Aggregate per screen session — not per-frame streams; watch PII in screen names."),
        ],
    },
    "android-jetpack-glance-appwidgets-state": {
        "title": "Glance App Widget State and Updates",
        "description": "GlanceAppWidget state, ActionCallback, WorkManager periodic refresh, and size-aware layouts without RemoteViews boilerplate.",
        "focus": "GlanceAppWidget, provideGlance, ActionCallback, stateDefinition, SizeMode, updatePeriodMillis limits, pinned widget",
        "section_headings": [
            "Glance vs classic RemoteViews",
            "StateDefinition for widget data",
            "ActionCallback and worker triggers",
            "Size buckets and responsive layout",
            "Update frequency system limits",
            "Process death and widget restore",
            "Preview and screenshot tests",
        ],
        "faq": [
            ("How often can Glance widgets update?", "System throttles — minimum updatePeriodMillis 30min for manifest; use WorkManager for event-driven."),
            ("Glance state persistence?", "stateDefinition with DataStore or file — survives widget process death."),
            ("Button click in widget?", "ActionCallback triggers in app process — keep work short, defer to WorkManager."),
            ("Glance on all launchers?", "Most modern launchers — test Samsung and Pixel launchers for sizing quirks."),
        ],
    },
    "android-jni-string-encoding-pitfalls": {
        "title": "JNI String Encoding Pitfalls on Android",
        "description": "Modified UTF-8, GetStringUTFChars vs GetStringCritical, NewStringUTF crashes, and Kotlin/NKD interop for C++ layers.",
        "focus": "Modified UTF-8, NewStringUTF invalid surrogate, GetStringUTFChars release, std::string conversion, @JvmName, native method registration",
        "section_headings": [
            "Modified UTF-8 is not UTF-8",
            "NewStringUTF crash on emoji",
            "GetStringUTFChars lifecycle",
            "Kotlin String to native boundary",
            "Performance of string copies",
            "FastUTF8 alternative patterns",
            "Debugging native string crashes",
        ],
        "faq": [
            ("Why NewStringUTF crashes?", "Invalid modified UTF-8 — emoji and some Unicode need NewString with UTF-16 chars array."),
            ("GetStringUTFChars when?", "When native code needs char* — always ReleaseStringUTFChars in finally path."),
            ("Pass byte array instead?", "For binary or UTF-8 bytes, jbyteArray avoids modified UTF-8 confusion."),
            ("NDK JNI helpers?", "Use RAII wrappers in C++ — manual Release easy to miss on exception paths."),
        ],
    },
    "android-jobscheduler-vs-workmanager": {
        "title": "JobScheduler vs WorkManager in Modern Android",
        "description": "When raw JobScheduler still fits, migrating JobService to Worker, and why WorkManager wins for deferrable guaranteed work.",
        "focus": "JobScheduler, JobService, WorkManager persistence, constraints, expedited work, migration dual-run, boot receiver removal",
        "section_headings": [
            "WorkManager as default choice",
            "Raw JobScheduler remaining use cases",
            "Migrating JobService to Worker",
            "Constraint mapping table",
            "Expedited work vs JobScheduler priority",
            "Observing work status in UI",
            "Removing BOOT_COMPLETED receivers",
        ],
        "faq": [
            ("Use JobScheduler directly in 2026?", "Rare — platform libraries or OEM-specific jobs; app deferrable work should use WorkManager."),
            ("WorkManager survives reboot?", "Yes — persisted in WorkDatabase; JobScheduler also persists but WorkManager adds chains and tags."),
            ("Replace JobService how?", "Implement Worker with same logic, enqueueUniqueWork, dual-run behind flag, remove JobService when traffic zero."),
            ("Immediate user work?", "Coroutine in ViewModel — not JobScheduler — unless true deferral acceptable."),
        ],
    },
    "android-keyboard-ime-insets-compose": {
        "title": "Keyboard IME Insets in Jetpack Compose",
        "description": "imePadding, WindowInsets.ime, bringIntoViewRequester, and edge-to-edge Activities where adjustResize alone fails.",
        "focus": "Modifier.imePadding, WindowInsetsCompat.Type.ime, bringIntoViewRequester, nested scroll, Scaffold padding, enableEdgeToEdge",
        "section_headings": [
            "Edge-to-edge broke my keyboard padding",
            "imePadding placement in hierarchy",
            "bringIntoViewRequester for focused fields",
            "NestedScrollConnection with IME animation",
            "Dialog and bottom sheet IME",
            "adjustResize vs inset-driven layout",
            "Testing keyboard on foldables",
        ],
        "faq": [
            ("TextField hidden under keyboard?", "Apply imePadding on scrollable parent, enableEdgeToEdge, avoid adjustPan-only with Compose."),
            ("Animated IME with edge-to-edge?", "WindowInsetsAnimationCompat or Compose inset animation APIs — test on API 30+."),
            ("Bottom sheet form fields?", "ModalBottomSheet with imePadding inside sheet content — not only root scaffold."),
            ("Hardware keyboard open?", "IME insets zero — layout should not collapse unnecessarily."),
        ],
    },
    "android-keystore-hardware-backed-keys": {
        "title": "Hardware-Backed Keys with Android Keystore",
        "description": "KeyGenParameterSpec, StrongBox, biometric-bound keys, and rotation when app signing or user enrolls new fingerprint.",
        "focus": "AndroidKeyStore, setUserAuthenticationRequired, StrongBox, KeyPermanentlyInvalidatedException, AES GCM, wrap secret pattern",
        "section_headings": [
            "TEE vs StrongBox availability",
            "Biometric-bound key generation",
            "KeyPermanentlyInvalidatedException handling",
            "Encrypt local tokens at rest",
            "Wrapping server secrets client-side",
            "Backup and restore implications",
            "Testing without biometrics enrolled",
        ],
        "faq": [
            ("StrongBox always available?", "No — check Security.getProviders and handle fallback to TEE."),
            ("New fingerprint invalidates keys?", "Yes if setInvalidatedByBiometricEnrollment true — plan re-enrollment UX."),
            ("Store API keys in Keystore?", "Prefer server-issued short-lived tokens — Keystore for client secrets only when necessary."),
            ("Keystore keys in backup?", "Exclude from backup — android:allowBackup false for key material or use EncryptedSharedPreferences pattern."),
        ],
    },
    "android-kotlin-multiplatform-migration-guide": {
        "title": "Kotlin Multiplatform Migration for Android Teams",
        "description": "Shared domain module first, expect/actual boundaries, Compose Multiplatform optional path, and Gradle module graph that does not stall the Android app.",
        "focus": "commonMain, expect actual, domain layer extraction, KMP Gradle plugin, iOS second target later, serialization, coroutines shared",
        "section_headings": [
            "Start with domain not UI",
            "Drawing expect/actual seams",
            "Gradle module graph evolution",
            "Testing shared code on JVM",
            "Compose Multiplatform timing",
            "Publishing shared library internally",
            "Team skill and CI implications",
        ],
        "faq": [
            ("Migrate UI or logic first?", "Logic — repositories, use cases, models — UI stays Android until shared design system justified."),
            ("expect/actual for what?", "Platform APIs — database, secure storage, date formatting edge cases — not every class."),
            ("KMP slows Android builds?", "Initial Gradle complexity increases — modularize and use fine-grained tasks to mitigate."),
            ("Need iOS day one?", "No — shared KMP module can serve Android-only until second target ready."),
        ],
    },
    "android-large-screen-optimization": {
        "title": "Large Screen Optimization Beyond Stretching Phone UI",
        "description": "WindowSizeClass, list-detail, canonical layouts, orientation unlock, and Play large-screen quality tier requirements.",
        "focus": "WindowSizeClass, Material adaptive layouts, list-detail activity embedding, resizable true, min width qualifiers, drag and drop",
        "section_headings": [
            "Stop locking orientation on tablets",
            "WindowSizeClass-driven navigation",
            "List-detail canonical layout",
            "Activity embedding without rewrite",
            "Drag and drop between panels",
            "Input: keyboard, stylus, trackpad",
            "Play large-screen quality checklist",
        ],
        "faq": [
            ("Required for Play badge?", "Resizable activities, no forced portrait on large screens, adaptive layouts — check current Play tier docs."),
            ("Phone layout on tablet?", "Play may downgrade quality — use at least list-detail or two-pane where width allows."),
            ("Compose adaptive libraries?", "Material3 adaptive NavigationSuiteScaffold — pair with WindowSizeClass."),
            ("Test large screens how?", "Emulator tablet, desktop mode on Samsung, Chromebook if applicable."),
        ],
    },
    "android-leakcanary-compose-watchers": {
        "title": "LeakCanary with Jetpack Compose Watchers",
        "description": "ObjectWatcher for Composition, retained Compose objects, ViewModel leaks vs composition leaks, and debug-only LeakCanary setup.",
        "focus": "LeakCanary 2, AppWatcher, CompositionLocal leaks, remember without keys, ViewModel scope, debugImplementation dependency",
        "section_headings": [
            "LeakCanary in debug builds only",
            "Compose-specific retention paths",
            "remember leaking captured contexts",
            "ViewModel vs composable scope",
            "ObjectWatcher custom watchers",
            "Heap dump analysis workflow",
            "CI does not run LeakCanary",
        ],
        "faq": [
            ("LeakCanary in release?", "No — debugImplementation only; never ship heap dumping to production."),
            ("Compose cause leaks?", "Capturing Activity in remember lambda, long-lived listeners in composable — same rules as Views."),
            ("LeakCanary slow?", "Heap dump on retained objects — acceptable in debug; disable for benchmark builds."),
            ("Integration with Hilt?", "Standard — leaks usually Activity/Fragment/ViewModel scope misuse not Dagger itself."),
        ],
    },
    "android-lifecycle-aware-components": {
        "title": "Lifecycle-Aware Components Beyond DefaultLifecycleObserver",
        "description": "DefaultLifecycleObserver, LifecycleEventObserver, repeatOnLifecycle, and Flow collection that stops when the UI is not STARTED.",
        "focus": "DefaultLifecycleObserver, repeatOnLifecycle STARTED, flowWithLifecycle, LifecycleService, ProcessLifecycleOwner",
        "section_headings": [
            "LifecycleOwner graph in Activity/Fragment",
            "DefaultLifecycleObserver vs annotations",
            "repeatOnLifecycle for Flow collection",
            "ProcessLifecycleOwner for app foreground",
            "LifecycleService patterns",
            "Compose DisposableEffect lifecycle bridge",
            "Common double-collection bugs",
        ],
        "faq": [
            ("collect Flow in onStart?", "Use repeatOnLifecycle(Lifecycle.State.STARTED) — cancels when STOPPED, prevents background collection."),
            ("DefaultLifecycleObserver vs @OnLifecycleEvent?", "Observer interface is modern — annotations deprecated."),
            ("ProcessLifecycleOwner use case?", "App foreground/background analytics — not per-Activity UI state."),
            ("Compose need repeatOnLifecycle?", "Often LaunchedEffect + lifecycleOwner.lifecycle — or collect in ViewModel with WhileSubscribed."),
        ],
    },
    "android-lifecycle-observer-patterns": {
        "title": "Lifecycle Observer Patterns for Listeners and Sensors",
        "description": "Register on ON_START, unregister on ON_STOP, avoid leaks from listeners that outlive the Activity when rotation is disabled.",
        "focus": "LifecycleEventObserver, ON_START ON_STOP pairing, sensor registration, location callback bind, configChanges trap",
        "section_headings": [
            "Symmetric register unregister",
            "Sensors and location lifecycle bind",
            "configChanges false rotation trap",
            "Fragment view lifecycle vs activity",
            "Multiple observers ordering",
            "Testing lifecycle with Robolectric",
            "Anti-pattern: Application-wide UI listeners",
        ],
        "faq": [
            ("Register listener in onCreate?", "If needs UI visible — prefer ON_START; if expensive — ON_RESUME for camera preview."),
            ("Rotation with configChanges?", "Activity not destroyed — listener may duplicate if not idempotent."),
            ("Fragment listener where?", "viewLifecycleOwner for view-bound; activity for shared across fragments carefully."),
            ("LifecycleObserver in Compose?", "DisposableEffect(onDispose) — or lifecycle observer in AndroidView bridge."),
        ],
    },
    "android-live-wallpaper-compose": {
        "title": "Live Wallpaper and Compose: Practical Boundaries",
        "description": "WallpaperService engine thread, SurfaceHolder rendering, battery limits, and why full Compose runtime in wallpaper is rare.",
        "focus": "WallpaperService, Engine onDraw, SurfaceHolder, battery impact, RenderThread, Compose not designed for wallpaper",
        "section_headings": [
            "WallpaperService engine lifecycle",
            "Drawing on SurfaceHolder",
            "Frame rate vs battery tradeoff",
            "User visibility and offset animations",
            "Compose interop limitations",
            "Play policy and battery warnings",
            "Alternative: static wallpaper + app",
        ],
        "faq": [
            ("Compose for live wallpaper?", "Generally no — WallpaperService expects Surface/engine loop; Compose targets Activity window."),
            ("Battery impact?", "High — cap frame rate, pause when not visible, warn users in settings."),
            ("Preview in wallpaper picker?", "Engine preview mode — lightweight draw path separate from full quality."),
            ("Distribution outside Play?", "Live wallpapers still on Play — subject to background execution limits."),
        ],
    },
    "android-local-first-architecture": {
        "title": "Local-First Architecture on Android",
        "description": "Room as source of truth, optimistic UI, sync engine outline, conflict resolution UX, and offline queues that replay safely.",
        "focus": "Room Flow, optimistic write, outbox pattern, sync worker, conflict merge UI, idempotent server API, CRDT when needed",
        "section_headings": [
            "UI reads local database always",
            "Optimistic updates and rollback",
            "Outbox table for pending mutations",
            "Sync scheduler and backoff",
            "Conflict resolution user experience",
            "Idempotent server endpoints",
            "When CRDTs are worth the complexity",
        ],
        "faq": [
            ("Local-first vs offline-first?", "Local-first treats local DB as primary UX path; offline-first often means cache with server authority — different conflict rules."),
            ("Show stale badge?", "Yes when sync pending or last sync failed — users forgive offline not silent wrong data."),
            ("Room alone enough?", "Room + WorkManager + clear sync protocol — Room is not sync engine by itself."),
            ("Delete propagation offline?", "Tombstone records in outbox — server must accept delete idempotently on replay."),
        ],
    },
    "android-localization-rtl-support": {
        "title": "RTL Localization on Android and Compose",
        "description": "layoutDirection, start/end margins, mirrored icons, bidirectional text, and locale testing beyond translation strings.",
        "focus": "supportsRtl, CompositionLocalProvider LayoutDirection, padding start end, mirrored icons policy, BidiFormatter, pseudolocale",
        "section_headings": [
            "Start/end vs left/right in XML and Compose",
            "Mirroring icons that must not flip",
            "Bidirectional text in Text composables",
            "Navigation transitions in RTL",
            "Number and phone LTR in RTL layout",
            "Pseudolocale and layout stress",
            "QA matrix for Arabic and Hebrew",
        ],
        "faq": [
            ("Compose RTL automatic?", "Most Material components mirror — custom layouts must use start/end modifiers explicitly."),
            ("Icons that should not mirror?", "Use autoMirrored=false on vector icons like media play arrows when semantic direction matters."),
            ("Numbers in RTL screens?", "Phone numbers and credit cards often need LTR span — BidiFormatter or unicode isolates."),
            ("Test without fluent speakers?", "Pseudolocale tools and forced RTL developer option — catch layout breaks early."),
        ],
    },
    "android-location-foreground-service": {
        "title": "Location Foreground Service Patterns",
        "description": "Location FGS notification, whileInUse vs always permission, batched updates in background, and transition off FGS when navigation ends.",
        "focus": "startForeground location type, FusedLocationProvider in FGS, notification ongoing, stopSelf on arrival, background location approval",
        "section_headings": [
            "When location FGS is mandatory",
            "Notification copy users accept",
            "Batched updates vs real-time track",
            "Stopping FGS when trip completes",
            "Background location approval sequence",
            "Map in foreground vs track in background",
            "Play policy location declarations",
        ],
        "faq": [
            ("Track delivery driver location?", "Location FGS with clear notification while on duty — background location permission if track when app not visible."),
            ("Can I hide location notification?", "No — ongoing location FGS requires visible notification — tampering violates policy."),
            ("Switch off FGS after geofence exit?", "stopForeground and stopSelf — unregister location callbacks to prevent zombie updates."),
            ("whileInUse enough for navigation?", "While app visible navigating yes — continuous invisible track needs always + approval."),
        ],
    },
    "android-log-redaction-production": {
        "title": "Log Redaction in Production Android Builds",
        "description": "Timber trees, BuildConfig.DEBUG gates, structured logging without PII, and Crashlytics breadcrumb hygiene.",
        "focus": "Timber ReleaseTree, ProGuard strip Log calls, structured logging, PII regex redaction, Crashlytics log limits, okhttp logging interceptor",
        "section_headings": [
            "Debug verbose vs release silent",
            "Timber forest and ReleaseTree",
            "OkHttp logging in production",
            "Crashlytics custom keys without PII",
            "ProGuard assumenosideeffects Log.d",
            "Structured logs for on-call",
            "Incident response when logs leaked",
        ],
        "faq": [
            ("Log.d in release builds?", "Strip via ProGuard or Timber no-op tree — never rely on developers remembering if (DEBUG)."),
            ("OkHttp Body logging?", "Debug only — bodies contain tokens and passwords."),
            ("Crashlytics breadcrumbs?", "User ids hashed — no email, phone, or auth headers in keys."),
            ("GDPR and logs?", "Retention policy and deletion on account erasure — logs in third parties count."),
        ],
    },
}
