"""EXTRA_SPECS for humanize_batch_02_part1 (indices 550-599)."""

EXTRA_SPECS = [{'description': 'Use Lottie in Jetpack Compose the right way: loading, caching, dynamic properties, controlling '
                 'playback with progress, and avoiding jank from oversized JSON files.',
  'faq': [('Why pass Lottie progress as a lambda in Compose?',
           'A lambda defers reading animated progress to the draw phase, avoiding 60+ recompositions per second that '
           'show up as jank when combined with list scroll or image loading.'),
          ('What makes a Lottie JSON too heavy for mobile?',
           'High layer counts, embedded rasters, animated masks, and 3D camera layers force expensive offscreen work. '
           'Merge layers in After Effects and cap inline UI animations around 150 KB.'),
          ('How do I load remote Lottie safely?',
           'Use rememberLottieComposition with Url spec, show a static placeholder while loading, handle parse '
           'failures, and never block checkout on a CDN animation.')],
  'focus': 'rememberLottieComposition, animateLottieCompositionAsState, progress lambda draw phase, dynamic '
           'properties, and list scroll jank',
  'slug': 'android-lottie-compose-animations',
  'title': 'Lottie Animations in Jetpack Compose Without Wrecking Performance'},
 {'description': 'Use Macrobenchmark to measure real Android performance: startup timing, frame/jank stats, and CI '
                 'regression gates that catch slowdowns before users feel them.',
  'faq': [('Macrobenchmark vs Microbenchmark — when to use which?',
           'Macrobenchmark measures full app flows (startup, scroll) on device with realistic ART state. '
           'Microbenchmark targets isolated Kotlin functions. Use Macrobenchmark for user-visible regressions.'),
          ('Which CompilationMode should CI gate on?',
           'Gate on Partial() with Baseline Profile when shipped; add None() nightly to catch first-install '
           'interpret-mode regressions new users hit.'),
          ('How do I share benchmark results across releases?',
           'Export JSON from measureRepeated, tag with commit SHA and device serial, graph medians — not single-run '
           'hero numbers.')],
  'focus': 'MacrobenchmarkRule, FrameTimingMetric, trace sections, CompilationMode matrix, and CI device pinning',
  'slug': 'android-macrobenchmark-profiling',
  'title': 'Macrobenchmark: Measuring Real Android Performance'},
 {'description': 'Measure cold/warm/hot startup: StartupTimingMetric, BaselineProfileRule, and comparing releases in '
                 'CI.',
  'faq': [('Cold vs warm vs hot startup — report separately?',
           'Yes. Baseline Profiles help cold; lazy DI fixes warm; onResume sync fixes hot. Averaging hides which '
           'commit broke which mode.'),
          ('When must I call reportFullyDrawn?',
           'When your critical content is ready — not when splash dismisses. Vitals and StartupTimingMetric '
           'timeToFullDisplay depend on it.'),
          ('Why do lab numbers beat Play vitals?',
           'Production includes slow storage, thermal throttling, and OEM tweaks. Benchmark on 3–4 GB RAM devices with '
           '80% storage full.')],
  'focus': 'StartupTimingMetric, StartupMode COLD WARM HOT, BaselineProfileRule, reportFullyDrawn, Perfetto alignment',
  'slug': 'android-macrobenchmark-startup-tracing',
  'title': 'Macrobenchmark Startup Tracing'},
 {'description': 'Use the Material 3 adaptive navigation suite in Compose to switch between bottom bar, navigation '
                 'rail, and drawer based on window size class across phones, foldables, tablets.',
  'faq': [('Bottom bar vs navigation rail — who decides?',
           'WindowSizeClass and Material adaptive components pick chrome from width and posture — do not hardcode '
           'phone-only bottom nav on tablets.'),
          ('How do foldables affect pane scaffolds?',
           'List-detail may span both displays; reset selection on fold/unfold if pane widths cross size-class '
           'thresholds.'),
          ('Can I keep legacy XML navigation during migration?',
           'Map slidingPaneLayout to ListDetailPaneScaffold incrementally — avoid rewriting nav and panes in one '
           'release.')],
  'focus': 'NavigationSuiteScaffold, WindowSizeClass, ListDetailPaneScaffold, foldable posture, debounced chrome '
           'switches',
  'slug': 'android-material3-adaptive-navigation',
  'title': 'Material 3 Adaptive Navigation Suite: One Nav for Every Form Factor'},
 {'description': 'Commission Matter devices from Android: QR and manual pairing, Google Home SDK integration, network '
                 'credentials, and failure recovery on real hardware.',
  'faq': [('What if commissioning fails mid-flow?',
           'Device OTA or weak Thread signal aborts sessions — advise power stable, retry, factory reset only as last '
           'resort with clear copy.'),
          ('Multi-admin fabric joins vs first device?',
           'Second household member scans different QR — separate UX from first-device commissioning to avoid dead '
           'ends.'),
          ('Border router offline — what to show?',
           'Explicit screen linking compatible hub SKUs beats generic timeout errors that flood support.')],
  'focus': 'Google Home Mobile SDK commissioning, QR pairing, Thread border router, multi-admin fabric, OTA '
           'mid-session',
  'slug': 'android-matter-commissioning',
  'title': 'Matter Device Commissioning on Android'},
 {'description': 'MediaSessionService with FGS mediaPlayback: notification controls, stopSelf on pause, and Bluetooth '
                 'disconnect handling.',
  'faq': [('When should I revisit media playback foreground service in production?',
           'After OS upgrades, permission policy changes, or when Vitals shows regression tied to releases touching '
           'media playback foreground service.'),
          ('What breaks media playback foreground service on low-RAM devices?',
           'Process death, deferred background work, and OEM battery savers — test with adb shell am kill and strict '
           'mode.'),
          ('How do I roll out media playback foreground service safely?',
           'Feature flag, staged percentage, kill switch, and structured client logging before 100%.')],
  'focus': 'media playback foreground service production patterns, lifecycle, permissions, testing, rollout',
  'slug': 'android-media-playback-foreground-service',
  'title': 'Media Playback Foreground Service'},
 {'description': 'MediaSessionCompat with Media3: lock screen controls, Bluetooth AVRCP, Android Auto, and '
                 'notification media style.',
  'faq': [('How do I stop lock-screen art flicker?',
           'Disk-cache album art URLs with LRU cap (~50 MB) instead of re-fetching on every skip.'),
          ('Android Auto search while driving?', 'Debounce server queries — head units ANR on rapid keystrokes.'),
          ('Media3 inactivity stop delay?',
           'Document expected service stop after pause so QA distinguishes policy from bugs.')],
  'focus': 'MediaSessionCompat Media3, lock screen controls, Android Auto, metadata art cache, queue APIs',
  'slug': 'android-media-session-controls',
  'title': 'MediaSession Controls and Platform Integration'},
 {'description': 'Query photos, video, and audio with MediaStore on Android 10+: scoped storage rules, content '
                 'resolver patterns, and permission-free access with the photo picker.',
  'faq': [('Photo Picker URI vs MediaStore read permission?',
           'Picker returns URI without broad storage access — call takePersistableUriPermission when offered or '
           'uploads break next day.'),
          ('Should I strip GPS EXIF on publish?',
           'Yes unless location is product intent — strip on background thread before insert.'),
          ('requestLegacyExternalStorage still?',
           'Remove deprecated flag — it gives false confidence during scoped storage audits.')],
  'focus': 'MediaStore queries, IS_PENDING, Photo Picker URIs, EXIF stripping, scoped storage migration',
  'slug': 'android-media-store-scoped',
  'title': 'Scoped Storage and MediaStore Queries'},
 {'description': 'A practical guide to migrating from the legacy ExoPlayer to AndroidX Media3: package mapping, the '
                 'migration script, MediaSession changes, and what to verify.',
  'faq': [('What breaks silently in ExoPlayer→Media3 migration?',
           'Custom ExtractorsFactory registration and Cronet extension artifact moves — verify playback of niche '
           'containers after package rename.'),
          ('Golden frame tests worth it?',
           'Grab frame at fixed timestamp in androidTest with pixel tolerance — catches renderer regressions unit '
           'tests miss.'),
          ('Keep ExoPlayer package imports?',
           'No — migrate imports to androidx.media3; R8 may strip wrong keep rules if mixed.')],
  'focus': 'androidx.media3 migration, ExtractorsFactory, Cronet extension, golden frame tests, Player listener wiring',
  'slug': 'android-media3-exoplayer-migration',
  'title': 'Migrating from ExoPlayer to Media3 Without Regressions'},
 {'description': 'Set up a Media3 MediaSession and MediaSessionService for reliable background audio: the '
                 'notification, MediaController, audio focus, and surviving process death.',
  'faq': [('How do I stop lock-screen art flicker?',
           'Disk-cache album art URLs with LRU cap (~50 MB) instead of re-fetching on every skip.'),
          ('Android Auto search while driving?', 'Debounce server queries — head units ANR on rapid keystrokes.'),
          ('Media3 inactivity stop delay?',
           'Document expected service stop after pause so QA distinguishes policy from bugs.')],
  'focus': 'MediaSessionCompat Media3, lock screen controls, Android Auto, metadata art cache, queue APIs',
  'slug': 'android-media3-media-session',
  'title': 'Media3 MediaSession and Background Playback'},
 {'description': 'Find and fix Android memory leaks with LeakCanary: read the leak trace, understand the shortest path '
                 'to GC root, and fix the common Activity and listener leaks.',
  'faq': [('LeakCanary trace points at SDK — now what?',
           'Third-party callback holding Activity — wrap Application context or unregister in onDestroy; file vendor '
           'ticket with trace.'),
          ('Compose remember without keys?',
           'Large remembered objects retain memory — prefer ViewModel or keyed remember.'),
          ('Fail CI on leak detection?',
           'Aggressive but catches callback regressions before release for leak-sensitive apps.')],
  'focus': 'LeakCanary 2 heap dumps, retained object analysis, Compose watchers, SDK callback leaks, CI '
           'instrumentation',
  'slug': 'android-memory-leaks-leakcanary',
  'title': 'Hunting Memory Leaks with LeakCanary'},
 {'description': 'Skip prefetch on metered networks: WorkManager constraints, Coil cache policy, and user-visible '
                 'download prompts.',
  'faq': [('How to explain paused sync to users?',
           "Show 'Waiting for Wi‑Fi to back up 120 photos (~340 MB)' not vague 'Sync paused' — numbers build trust."),
          ('Roaming always equals foreign country?',
           'Enterprise plans may be NOT_ROAMING internationally — re-evaluate on NetworkCapabilities callback.'),
          ('ExoPlayer on cellular?',
           'Cap max bitrate via trackSelector separately from disabling prefetch — unlimited users still appreciate SD '
           'default.')],
  'focus': 'NetworkCapabilities NOT_METERED, WorkManager constraints, Coil network observer, ExoPlayer bitrate caps',
  'slug': 'android-metered-connection-optimization',
  'title': 'Metered Connection Optimization'},
 {'description': 'Benchmark Kotlin code on device: MicrobenchmarkRule, dead code elimination traps, and statistical '
                 'rigor.',
  'faq': [('Why did inline function benchmark show no gain?',
           'ART may already inline — compare across commits on same device, not intuition.'),
          ('Kotlin value classes for hot collections?', 'Microbenchmark before/after — results vary by ART version.'),
          ('Multithreaded lock perf?',
           'AndroidX MicrobenchmarkRule is single-threaded — do not infer contended lock cost from one thread.')],
  'focus': 'MicrobenchmarkRule, BenchmarkRule overhead, inline value classes, baseline JSON in CI',
  'slug': 'android-microbenchmark-inline-methods',
  'title': 'Microbenchmark for Inline Methods'},
 {'description': 'Run computer vision on-device with ML Kit: which APIs are free and offline, bundled vs Play Services '
                 'models, feeding CameraX frames, and when to reach for a custom model.',
  'faq': [('Front camera mirrored but detection wrong?',
           'InputImage rotation must match sensor, not mirrored preview — common face bounds bug.'),
          ('GPU mode for continuous scan?',
           'Test 10-minute warehouse scan thermal throttling before enabling GPU detectors.'),
          ('Unbundled model first launch?',
           'Show honest download size on cellular before starting large model fetch.')],
  'focus': 'InputImage rotation, bundled vs unbundled models, GPU delegate thermal, barcode face detection',
  'slug': 'android-mlkit-on-device-vision',
  'title': 'On-Device Vision with ML Kit'},
 {'description': 'Modularize Android apps pragmatically: module types, dependency rules, feature modules, and '
                 'incremental extraction without stopping feature development.',
  'faq': [('Extract module behind flag?',
           'Ship extracted :feature behind Remote Config while old path remains until parity proven.'),
          ('Developers not feeling compile win?',
           'Modularization needs Gradle remote cache — monitor hit rate when splitting.'),
          ('Who owns :feature:checkout?', 'CODEOWNERS per module — social contract as important as Gradle graph.')],
  'focus': 'feature modules, dependency rules, :core :data :feature, Gradle configuration cache, CODEOWNERS',
  'slug': 'android-modularization-strategy',
  'title': 'A Pragmatic Android Modularization Strategy'},
 {'description': 'Wire navigation across Android feature modules with Compose Navigation: typed routes, module-owned '
                 'graphs, deep links, and keeping feature modules independent.',
  'faq': [('How do feature modules register routes without coupling?',
           'Publish :navigation artifact with typed route interfaces — feature UI depends on contracts not sibling '
           'modules.'),
          ('Deep links outlive app versions?',
           'Version routes in path `/v2/product/` while registering both during migration window.'),
          ('Shared element transitions across modules?',
           'Place transition spec in core:ui or nav contract — not duplicated per feature.')],
  'focus': 'Compose Navigation typed routes, NavHostBuilder per module, deep link versioning, public navigation API',
  'slug': 'android-multi-module-navigation-compose',
  'title': 'Multi-Module Navigation with Compose'},
 {'description': 'Implement drag and drop across split-screen and foldable windows: ClipData, View.DragShadowBuilder, '
                 'Compose drag modifiers, and cross-app content sharing.',
  'faq': [('Drag coordinates jump when folding?',
           'Reset drag state on CONFIGURATION_CHANGED — window space changes across displays.'),
          ('Expensive drag shadow?',
           'Custom DragShadowBuilder drawing icon only — default screenshot shadow janks large images.'),
          ('TalkBack path for drag?', 'Duplicate with overflow menu actions — announce programmatic moves.')],
  'focus': 'DragAndDrop, ClipData, View.DragShadowBuilder, foldable coordinates, ChromeOS freeform',
  'slug': 'android-multi-window-drag-drop',
  'title': 'Multi-Window Drag and Drop on Android'},
 {'description': 'Model MVI on Android with sealed intents, immutable state, and single reducer pipelines in ViewModel '
                 '— compared to MVVM and when strict unidirectional flow pays off.',
  'faq': [('Navigation from ViewModel?',
           'Keep nav as effect consumed in UI — direct NavController in ViewModel breaks tests and couples framework.'),
          ('Search-as-you-type choking reducer?',
           'Debounce in UI or distinctUntilChanged before reduce for QueryChanged intents.'),
          ('SavedStateHandle vs full MVI state?',
           'SavedState for ids; MVI for derived UI — avoid duplicating entire tree.')],
  'focus': 'sealed Intent, Reducer, StateFlow, effect channel, SavedStateHandle merge, debounced search intents',
  'slug': 'android-mvi-unidirectional-data-flow',
  'title': 'MVI and Unidirectional Data Flow on Android'},
 {'description': 'Call C/C++ from Kotlin through JNI: CMake setup, external functions, string encoding pitfalls, and '
                 'when native code earns its maintenance cost.',
  'faq': [('16 KB page size readiness?',
           'Follow NDK release notes for linker flags when packaging .so for future Play device requirements.'),
          ('JNI string encoding pitfalls?',
           'GetStringUTFChars vs modified UTF-8 — emoji and supplementary chars corrupt if wrong API chosen.'),
          ('Duplicate STL from vendor AAR?',
           'Align c++_shared vs static STL per vendor doc — duplicate symbols fail link.')],
  'focus': 'CMake externalNativeBuild, JNI_OnLoad, GetStringUTFChars, suspendCancellableCoroutine native callbacks, '
           '16KB pages',
  'slug': 'android-ndk-jni-basics-kotlin',
  'title': 'NDK and JNI Basics for Kotlin Android Developers'},
 {'description': 'Transfer data between Android devices without internet using Nearby Connections: discovery, '
                 'connection lifecycle, bandwidth negotiation, and payload patterns.',
  'faq': [('Bluetooth to Wi‑Fi upgrade mid-transfer?',
           "UI should not disconnect when radio switches — explain 'Transfer speeding up' for large files."),
          ('Mixed app versions in field?',
           'Protocol version byte in first control payload — refuse unsupported with upgrade prompt.'),
          ('Nearby vs Bluetooth OBEX?',
           'Keep OBEX branch for rugged devices without Play services if user base requires.')],
  'focus': 'ConnectionsClient, STRATEGY_P2P_CLUSTER, bandwidth upgrade, encrypted payloads, protocol versioning',
  'slug': 'android-nearby-connections-api',
  'title': 'Nearby Connections API for Offline Peer Transfer'},
 {'description': 'Let users share content through Nearby Share: ShareCompat intents, direct share targets, and '
                 'preparing content URIs with correct permissions.',
  'faq': [('Share sheet title matters?',
           "Contextual title 'Share receipt with accountant' reduces wrong taps vs generic 'Share'."),
          ('Share before MediaStore IS_PENDING clears?',
           'Receiver may see zero-byte file — gate share until pending cleared.'),
          ('Work profile share targets?', 'QA managed devices — corporate policy may block cross-profile share.')],
  'focus': 'ShareCompat, FileProvider, content URI grants, work profile QA, analytics without URI logging',
  'slug': 'android-nearby-share-api',
  'title': 'Integrating with Nearby Share on Android'},
 {'description': 'Detect VPN, metered, unmetered, and captive portal: download policy, video quality, and sync '
                 'scheduling.',
  'faq': [('Default data SIM switch mid-session?',
           'Capabilities callback refires — re-evaluate prefetch without app restart.'),
          ('VPN means all traffic encrypted?', 'Split tunnel may route some bytes outside VPN despite TRANSPORT_VPN.'),
          ('Log SSID in analytics?', 'Never — BSSID/SSID are location-sensitive; log transport types only.')],
  'focus': 'ConnectivityManager registerDefaultNetworkCallback, NET_CAPABILITY_NOT_METERED, VPN split tunnel, dual SIM',
  'slug': 'android-network-capabilities-detection',
  'title': 'NetworkCapabilities Detection Patterns'},
 {'description': 'Pin certificates, block cleartext, and debug safely with Android Network Security Config: XML '
                 'patterns, rotation, and common production mistakes.',
  'faq': [('NSC pinning replaces server CT?',
           'No — pins help client MITM after trust; server still needs certificate transparency monitoring.'),
          ('Staging pins in production?',
           'Variant merge verification in CI — staging cert must not ship in release artifact.'),
          ('WebView mixed content after strict NSC?', 'Fix CMS http assets — not client workarounds.')],
  'focus': 'network_security_config.xml, certificate pinning, debug-overrides, cleartext opt-in, WebView audit',
  'slug': 'android-network-security-config',
  'title': 'Network Security Config for Android Apps'},
 {'description': 'Understand NEW_TASK, document launch mode, and task affinities: fix broken back stacks, deep links, '
                 'and multi-window document tasks.',
  'faq': [('Deep link from browser vs launcher?', 'Centralize DeepLinkRouter — flags differ by entry source.'),
          ('allowTaskReparenting?', 'Rarely needed — breaks predictable back; document if enabled for widget entry.'),
          ('Predictive back with document tasks?', 'Test Recents swipe on Android 13+ with multiple document tasks.')],
  'focus': 'FLAG_ACTIVITY_NEW_TASK, document launch mode, task affinity, DeepLinkRouter, predictive back',
  'slug': 'android-new-task-document-launch',
  'title': 'FLAG_ACTIVITY_NEW_TASK and Document Launch Modes'},
 {'description': 'Build HCE payment apps: AID registration, APDU command handling, tokenization boundaries, and PCI '
                 'scope realities on Android.',
  'faq': [('Wrong AID at terminal?', 'Terminal ignores phone — AIDs must match issuer program registration exactly.'),
          ('Store PAN in encrypted prefs?',
           'Never — payment networks require TSP tokenization; PCI scope explodes otherwise.'),
          ('Default payment app requirement?',
           'User must pick app in Settings → Contactless payments or Google Wallet intercepts tap.')],
  'focus': 'HostApduService, payment AID apduservice.xml, tokenization TSP, default wallet, PDOL responses',
  'slug': 'android-nfc-hce-payment',
  'title': 'NFC Host Card Emulation for Payments'},
 {'description': 'Implement HostApduService for non-payment HCE: loyalty cards, access badges, and APDU protocol '
                 'design on Android.',
  'faq': [('HCE without payment category?',
           'Use non-payment AID groups for loyalty and access — different apduservice.xml category.'),
          ('Foreground required for HCE?',
           'Some OEMs require foreground for non-payment tap — test Samsung/Huawei background.'),
          ('Multiple overlapping AIDs?', 'Priority in apduservice.xml — first match wins; order carefully.')],
  'focus': 'non-payment HCE, loyalty AIDs, HostApduService foreground, AID priority, power saving NFC off',
  'slug': 'android-nfc-host-card-emulation',
  'title': 'NFC Host Card Emulation Basics'},
 {'description': 'Conversation bubbles with BubbleMetadata: floating chat UI, suppressed foreground notification, and '
                 'when bubbles beat legacy overlays.',
  'faq': [('User dismissed bubble — re-post on next message?',
           'Respect suppressed state per conversation unless user opts back in.'),
          ('Third-party launcher support?', 'Degrade to standard notification without error when bubbles unsupported.'),
          ('Shortcuts sync with bubbles?',
           'Dynamic shortcuts must match conversations or bubble metadata goes stale.')],
  'focus': 'BubbleMetadata, suppressed notification, conversation shortcuts, launcher degradation',
  'slug': 'android-notification-bubbles-api',
  'title': 'Notification Bubbles on Android'},
 {'description': 'Create notification channels users understand: importance levels, grouping, migration when channel '
                 'IDs change, and settings deep links.',
  'faq': [('Change channel importance in code?',
           'Sticky after first create — migrate via new channel ids with in-app explanation.'),
          ('OEM merges channels visually?', 'Still create logical separation for stock Android and policy clarity.'),
          ('Custom channel sounds?', 'Use raw resource URIs — verify copyright on bundled sounds.')],
  'focus': 'NotificationChannel importance, migration ids, OEM batching, custom sounds',
  'slug': 'android-notification-channels-best-practices',
  'title': 'Notification Channels: Design and Migration'},
 {'description': 'Group related notifications with NotificationCompat group key, inbox style summaries, and avoiding '
                 'notification spam.',
  'faq': [('FCM collapse key vs client group key?',
           'Align server collapse key namespace with NotificationCompat group key or duplicates appear.'),
          ('Silent batch updates?', 'setSilent(true) on children when updating marketing batch without sound.'),
          ('Badge count with groups?', 'Verify OEM launcher aggregates group badge differently from children.')],
  'focus': 'setGroup, summary notification, inbox style, FCM collapse key alignment',
  'slug': 'android-notification-grouping-summary',
  'title': 'Notification Grouping and Summary Notifications'},
 {'description': 'RemoteInput inline replies: mutable PendingIntent patterns, dispatching replies to WorkManager, and '
                 'Android 12 mutability rules.',
  'faq': [('RemoteInput on lock screen with E2E?',
           'Ciphertext previews may leak policy — many E2E apps disable inline reply on lock screen.'),
          ('Failed send retry?', 'Optional draft persistence locally when RemoteInput send fails.'),
          ('Smart reply vs RemoteInput?', 'On-device smart reply is separate feature — do not conflate code paths.')],
  'focus': 'RemoteInput, mutable PendingIntent, MessagingStyle, draft persistence, E2E lock screen',
  'slug': 'android-notification-inline-replies',
  'title': 'Inline Replies in Android Notifications'},
 {'description': 'Request POST_NOTIFICATIONS permission: when to ask, fallback UX when denied, and FCM implications '
                 'for new installs.',
  'faq': [('POST_NOTIFICATIONS vs SCHEDULE_EXACT_ALARM?', 'Separate permissions — do not merge rationale screens.'),
          ('Family Link supervised accounts?', 'Parental settings may override grant — test manual entry paths.'),
          ('Pre-permission rationale localization?',
           'Grant rates drop on non-English users when rationale is English-only.')],
  'focus': 'POST_NOTIFICATIONS permission, rationale timing, settings deep link, Family Link',
  'slug': 'android-notification-runtime-permission',
  'title': 'POST_NOTIFICATIONS Runtime Permission on Android 13+'},
 {'description': 'Android 12+ blocks notification trampolines: start activities directly from FCM, use full-screen '
                 'intents sparingly, and comply with BAL restrictions.',
  'faq': [('Android 12+ trampoline blocked — fix?',
           'Use full-screen intent only when eligible; otherwise PendingIntent to Activity with trampoline removed.'),
          ('Wear notification tap path?', 'Watch may differ from phone — test paired devices.'),
          ('Fake incoming call full screen?', 'Play rejects abuse patterns — do not replicate deprecated tricks.')],
  'focus': 'trampoline restrictions API 31, full-screen intent eligibility, direct activity PendingIntent',
  'slug': 'android-notification-trampoline-restrictions',
  'title': 'Notification Trampoline Restrictions'},
 {'description': 'NotificationCompat.WearableExtender: pages, background, and bridging to Wear OS complication '
                 'updates.',
  'faq': [('How many Wear pages?', 'Cap at two defensively — older watches ignore beyond two.'),
          ('Large map preview in extender?', 'Compress JPEG ~quality 80 — bridge transfer costs battery.'),
          ('Voice reply on Wear?', 'Uses same mutable PendingIntent path as phone inline reply.')],
  'focus': 'WearableExtender pages, background bitmap compression, bridged voice reply',
  'slug': 'android-notification-wearable-extender',
  'title': 'Wearable Extender for Notifications'},
 {'description': 'R8 and ProGuard shrink and rename your code, but hardcoded strings stay readable in the APK. Learn '
                 'what obfuscation actually protects, when string encryption helps, and how to avoid breaking '
                 'reflection.',
  'faq': [('R8 renames classes — strings still leak secrets?',
           'Yes — API keys in strings survive shrinking; use backend proxy or Play Integrity attestation.'),
          ('String encryption libraries?',
           'Often break with R8 updates and give false security — prefer server-side secrets.'),
          ('Mapping file for Crashlytics?', 'Upload on every release build — obfuscated stacks are useless without.')],
  'focus': 'R8 shrinker, ProGuard rules, string literal secrets, mapping files, reflection keep rules',
  'slug': 'android-obfuscation-string-encryption',
  'title': 'Obfuscation and String Encryption on Android'},
 {'description': 'Design offline-first mobile apps: local source of truth, sync queue, conflict resolution, and '
                 'optimistic UI.',
  'faq': [('Hard delete vs tombstone on server delete?',
           'Tombstone with deletedAt for sync propagation — hard delete breaks multi-device convergence.'),
          ('Outbox during Room migration?', 'Never drop outbox table — version schema separately if needed.'),
          ('Pending outbox badge?',
           'Power users trust app when they see pending count drop after connectivity returns.')],
  'focus': 'Room outbox, tombstones, sync status UX, conflict resolution, WorkManager sync',
  'slug': 'android-offline-first-sync-strategy',
  'title': 'Offline-First Sync Strategy for Mobile'},
 {'description': 'OkHttp interceptor patterns for Android: application vs network interceptors, auth token refresh '
                 'with Authenticator, retries, logging, and the ordering that bites you.',
  'faq': [('Application vs network interceptor?',
           'Application sees cached responses; network runs after cache miss — auth refresh belongs carefully to avoid '
           'loops.'),
          ('Logging interceptor in release?',
           'Redact Authorization and cookies — okhttp logging has burned teams in production.'),
          ('Coroutine vs blocking interceptors?',
           'Blocking interceptors run on OkHttp thread pool — keep fast; defer heavy work.')],
  'focus': 'Interceptor chain order, auth refresh, logging redaction, caching, EventListener metrics',
  'slug': 'android-okhttp-interceptors-patterns',
  'title': 'OkHttp Interceptor Patterns That Survive Production'},
 {'description': 'Embed GLSurfaceView in Compose via AndroidView: render thread lifecycle, EGL context, and touch '
                 'forwarding.',
  'faq': [('When should I revisit opengl es basics compose in production?',
           'After OS upgrades, permission policy changes, or when Vitals shows regression tied to releases touching '
           'opengl es basics compose.'),
          ('What breaks opengl es basics compose on low-RAM devices?',
           'Process death, deferred background work, and OEM battery savers — test with adb shell am kill and strict '
           'mode.'),
          ('How do I roll out opengl es basics compose safely?',
           'Feature flag, staged percentage, kill switch, and structured client logging before 100%.')],
  'focus': 'opengl es basics compose production patterns, lifecycle, permissions, testing, rollout',
  'slug': 'android-opengl-es-basics-compose',
  'title': 'OpenGL ES Basics with Jetpack Compose'},
 {'description': 'SYSTEM_ALERT_WINDOW abuse: detect overlay attacks, guide users away from malicious screen overlays, '
                 'banking app patterns.',
  'faq': [('SYSTEM_ALERT_WINDOW for legit features?',
           'Guide users carefully — malware history makes Play and users suspicious.'),
          ('FLAG_SECURE vs overlays?',
           'Combine for high-value flows — secure blocks recording not all overlay classes.'),
          ('Enterprise MDM blocks overlay?',
           'Handle Settings.canDrawOverlays false globally with degraded UX message.')],
  'focus': 'SYSTEM_ALERT_WINDOW, tapjacking, FLAG_SECURE, accessibility overlay confusion, MDM blocks',
  'slug': 'android-overlay-permission-security',
  'title': 'Overlay Permission Security Risks'},
 {'description': 'Integrate Paging 3 with Jetpack Compose: PagingSource, LazyPagingItems, load states, error handling, '
                 'and header/footer with Paging 3.3+.',
  'faq': [('LazyPagingItems load state in Compose?',
           'Handle LoadState.Error with retry — empty initial load looks like bug without placeholder.'),
          ('PagingSource invalidate storm?', 'Debounce invalidations from multiple collectors — thrashes database.'),
          ('Different prefetch distance phone vs tablet?',
           'WindowSizeClass can tune prefetchWindowSize in PagingConfig.')],
  'focus': 'LazyPagingItems, LoadState UI, PagingSource invalidation, prefetchWindowSize, combinedLoadStates',
  'slug': 'android-paging3-compose',
  'title': 'Paging 3 with Jetpack Compose'},
 {'description': 'Build offline-first paginated lists with Paging 3 RemoteMediator: network-database coordination, '
                 'REFRESH/PREPEND/APPEND loads, and error handling.',
  'faq': [('RemoteMediator END_OF_PAGINATION?',
           'Return without more pages when API signals end — avoid infinite spinners.'),
          ('Database as source of truth?',
           'Mediator writes network pages to Room; UI reads PagingSource from DB only.'),
          ('Conflict on refresh?',
           'Clear remote keys and re-fetch from scratch on pull-to-refresh vs append — document strategy.')],
  'focus': 'RemoteMediator, Room remote keys, network refresh strategy, END_OF_PAGINATION',
  'slug': 'android-paging3-remote-mediator',
  'title': 'Paging 3 RemoteMediator for Offline Lists'},
 {'description': 'Safe PendingIntent creation: request codes, explicit intents, and avoiding intent hijacking with '
                 'immutable flags.',
  'faq': [('Widget click request codes?',
           'Hash appWidgetId into requestCode — same layout multiple widgets need distinct PendingIntents.'),
          ('TaskStackBuilder depths?', 'Unique requestCode per stack level with immutable flags.'),
          ('Cancel when conversation deleted?',
           'Cancel obsolete notification PendingIntents — stale tap opens wrong thread.')],
  'focus': 'PendingIntent.getActivity requestCode, TaskStackBuilder, immutable flags, cancel on delete',
  'slug': 'android-pending-intent-immutable-patterns',
  'title': 'PendingIntent Immutable Patterns'},
 {'description': 'FLAG_IMMUTABLE vs FLAG_MUTABLE: fill-in intents, inline replies, and Android 12+ enforcement '
                 'crashes.',
  'faq': [('FLAG_MUTABLE when required?',
           'Inline reply and fill-in intents need mutable — everything else immutable on API 31+.'),
          ('Target SDK 34 on minSdk 24 device?',
           'Mutability enforced at runtime when targeting modern SDK — test old devices.'),
          ('SuppressLint on PendingIntent?', 'Avoid without security review ticket link in comment.')],
  'focus': 'FLAG_IMMUTABLE FLAG_MUTABLE, inline reply fill-in, Android 12 backport behavior',
  'slug': 'android-pending-intent-mutability-flags',
  'title': 'PendingIntent Mutability Flags on Android 12+'},
 {'description': "Let users pick a language just for your app using AppCompat's per-app language APIs, locale config "
                 'XML, and the system settings integration that backs it.',
  'faq': [('AppCompat vs per-app locale API 33?',
           'AppCompat backports for older devices — use AppCompatDelegate.setApplicationLocales.'),
          ('LocaleList vs single Locale?', 'Prefer LocaleList for regional variants user expects.'),
          ('Restart activity after locale change?',
           'recreate() or navigate to root — partial recomposition misses some resources.')],
  'focus': 'AppCompatDelegate setApplicationLocales, LocaleListCompat, activity recreate, resource qualifiers',
  'slug': 'android-per-app-language-appcompat',
  'title': 'Per-App Language Preferences with AppCompat'},
 {'description': 'Per-app language preferences on Android let users pick a language for one app independent of the '
                 'system locale, using LocaleManager and a small resources config.',
  'faq': [('System language change vs in-app?',
           'Per-app setting overrides system for your package only — document in settings UX.'),
          ('Play Store listing language?', 'Store listing locale separate from in-app locale — align support docs.'),
          ('RTL layout after switch?', 'Test layoutDirection on Arabic Hebrew after in-app switch without reinstall.')],
  'focus': 'LocaleManager per-app language API 33, settings UI, RTL layoutDirection, Play listing locale',
  'slug': 'android-per-app-language',
  'title': 'Per-App Language Preferences on Android'},
 {'description': 'Photo Picker Only: Dropping Storage Permissions: scoped storage migration using system Photo Picker '
                 'without broad READ_MEDIA permissions.',
  'faq': [('READ_MEDIA_IMAGES still needed?',
           'For broad gallery access yes; Photo Picker returns selected URIs without broad permission for one-shot '
           'pick.'),
          ('Partial access on Android 14?',
           'Selected photos access — re-prompt when user adds more; handle revoked URIs.'),
          ('Camera capture without storage permission?',
           'Write to app-specific dir or MediaStore insert — not legacy external storage.')],
  'focus': 'Photo Picker contract, READ_MEDIA partial access, persistable URI, camera without storage',
  'slug': 'android-permission-photopicker-only',
  'title': 'Photo Picker Only: Dropping Storage Permissions'},
 {'description': 'Google Play services Phone Number Hint: reduce friction at signup without READ_PHONE_STATE or SMS '
                 'permissions.',
  'faq': [('Hint number verified?', 'No until OTP — rate limit OTP per hinted number to prevent enumeration abuse.'),
          ('eSIM-only devices?', 'Hint may return eSIM profile — normalize E.164 before API submit.'),
          ('Family supervised accounts?', 'Hint may block — manual entry path must work.')],
  'focus': 'Identity.getSignInClient hint request, E.164 normalization, OTP rate limits, supervised accounts',
  'slug': 'android-phone-number-hint-api',
  'title': 'Phone Number Hint API Integration'},
 {'description': 'How the Android photo picker and granular media permissions work: selected photos access, READ_MEDIA '
                 'scopes, and why most apps should stop requesting storage.',
  'faq': [('Persistable URI permission?',
           'takePersistableUriPermission when flag offered — uploads fail next day without.'),
          ('Granular media permissions UX?',
           'Explain why limited selection — users think app is broken when photos missing.'),
          ('Picker vs custom gallery?',
           'Picker is privacy-preserving default; custom gallery needs stronger justification for Play.')],
  'focus': 'PickVisualMedia contract, granular permissions Android 14, persistableUriPermission, UX copy',
  'slug': 'android-photo-picker-media-permissions',
  'title': 'The Photo Picker and Granular Media Permissions'},
 {'description': 'Enter PiP mode from Compose: aspect ratio, remote actions, and media playback controls in PiP '
                 'window.',
  'faq': [('User disabled auto-PiP?', 'Detect and show in-app hint to re-enable for video category apps.'),
          ('Widevine L1 and PiP?', 'DRM content may disable PiP — handle ExoPlayer error with user message.'),
          ('setSeamlessResizeEnabled false?',
           'When aspect must hold during transition — letterbox vs crop product choice.')],
  'focus': 'PictureInPictureParams, Compose PiP, auto-enter, DRM Widevine, seamless resize',
  'slug': 'android-picture-in-picture-compose',
  'title': 'Picture-in-Picture with Jetpack Compose'},
 {'description': 'Ship large game and media assets with Play Asset Delivery: install-time, fast-follow, and on-demand '
                 'asset packs, plus how to fetch and cache them at runtime.',
  'faq': [('On-demand pack first open delay?',
           'Prefetch fast-follow packs on Wi‑Fi after install — level load mid-game fails without.'),
          ('Pack size limits?', 'Monitor Play Console reports — split across multiple on-demand packs by level band.'),
          ('Delta patch QA?', 'Verify patch from N-2 version — corrupt assets mid-level if patch broken.')],
  'focus': 'AssetPackManager, install-time fast-follow on-demand, pack size limits, delta updates',
  'slug': 'android-play-asset-delivery',
  'title': 'Play Asset Delivery for Large Games and Media Apps'}]
