#!/usr/bin/env python3
"""Generate 989 unique wave-2 blog topics not in content/blog/."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BLOG = ROOT / "content" / "blog"
existing = {f.stem for f in BLOG.glob("*.md")}

# (slug, title, category)
TOPICS = [
    # Kotlin / JVM (40)
    ("kotlin-context-receivers-practical", "Kotlin Context Receivers in Practice", "Kotlin"),
    ("kotlin-value-class-serialization", "Serializing Kotlin Value Classes", "Kotlin"),
    ("kotlin-flow-buffer-overflow", "Kotlin Flow Buffer and Overflow Strategies", "Kotlin"),
    ("kotlin-channel-select-multiplex", "Multiplexing with Kotlin Channel select", "Kotlin"),
    ("kotlin-coroutine-test-advance", "Testing Coroutines with runTest and advanceUntilIdle", "Kotlin"),
    ("kotlin-multiplatform-compose-resources", "Compose Multiplatform Resources in KMP", "Kotlin"),
    ("kotlin-multiplatform-navigation", "Navigation Patterns in Kotlin Multiplatform", "Kotlin"),
    ("kotlin-multiplatform-room-database", "Room Database in Kotlin Multiplatform", "Kotlin"),
    ("kotlin-multiplatform-datastore", "DataStore in Kotlin Multiplatform Apps", "Kotlin"),
    ("kotlin-multiplatform-analytics", "Analytics Abstraction in KMP", "Kotlin"),
    ("kotlin-multiplatform-push-notifications", "Push Notifications in Kotlin Multiplatform", "Kotlin"),
    ("kotlin-multiplatform-deep-linking", "Deep Linking Across KMP Targets", "Kotlin"),
    ("kotlin-multiplatform-file-io", "File I/O Abstractions in Kotlin Multiplatform", "Kotlin"),
    ("kotlin-multiplatform-crypto-common", "Cryptography in Kotlin Multiplatform", "Kotlin"),
    ("kotlin-multiplatform-logging", "Structured Logging in KMP Projects", "Kotlin"),
    ("kotlin-multiplatform-testing-shared", "Shared Test Logic in Kotlin Multiplatform", "Kotlin"),
    ("kotlin-multiplatform-mock-engine", "Mock Engines for KMP Network Tests", "Kotlin"),
    ("kotlin-multiplatform-build-cache", "Build Cache Optimization for KMP", "Kotlin"),
    ("kotlin-multiplatform-cocoapods", "CocoaPods Integration in KMP iOS Targets", "Kotlin"),
    ("kotlin-multiplatform-spm", "Swift Package Manager with Kotlin Multiplatform", "Kotlin"),
    ("kotlin-compose-multiplatform-desktop", "Compose Multiplatform Desktop Apps", "Kotlin"),
    ("kotlin-compose-multiplatform-web", "Compose Multiplatform for Web (Wasm)", "Kotlin"),
    ("kotlin-wasm-js-interop", "Kotlin Wasm and JavaScript Interop", "Kotlin"),
    ("kotlin-scripting-gradle-plugins", "Kotlin Scripting for Custom Gradle Plugins", "Kotlin"),
    ("kotlin-dsl-gradle-conventions", "Gradle Convention Plugins with Kotlin DSL", "Kotlin"),
    ("kotlin-gradle-version-catalogs", "Gradle Version Catalogs in Kotlin Projects", "Kotlin"),
    ("kotlin-build-reports-performance", "Analyzing Kotlin Build Performance Reports", "Kotlin"),
    ("kotlin-incremental-compilation", "Incremental Compilation in Kotlin", "Kotlin"),
    ("kotlin-k2-compiler-migration", "Migrating to the K2 Kotlin Compiler", "Kotlin"),
    ("kotlin-metadata-jvm-annotations", "Kotlin Metadata and JVM Annotations", "Kotlin"),
    ("kotlin-java-interop-nullability", "Nullability Interop Between Kotlin and Java", "Kotlin"),
    ("kotlin-sam-conversions-lambdas", "SAM Conversions and Functional Interfaces", "Kotlin"),
    ("kotlin-sealed-when-exhaustive", "Exhaustive when with Sealed Classes", "Kotlin"),
    ("kotlin-destructuring-data-classes", "Destructuring Declarations in Kotlin", "Kotlin"),
    ("kotlin-scope-functions-let-apply", "Kotlin Scope Functions: let, apply, run, also, with", "Kotlin"),
    ("kotlin-lateinit-vs-lazy", "lateinit vs lazy: Initialization Patterns", "Kotlin"),
    ("kotlin-delegated-properties-observable", "Observable Properties with Delegates", "Kotlin"),
    ("kotlin-operator-overloading-guidelines", "Operator Overloading Guidelines in Kotlin", "Kotlin"),
    ("kotlin-infix-functions-readability", "Infix Functions for Readable APIs", "Kotlin"),
    ("kotlin-typealiases-domain-language", "Type Aliases for Domain-Specific Language", "Kotlin"),
    # Compose (35)
    ("compose-material3-expressive-design", "Material 3 Expressive Design in Compose", "Compose"),
    ("compose-adaptive-layout-canonical", "Canonical Adaptive Layouts in Compose", "Compose"),
    ("compose-navigation3-type-safe", "Type-Safe Navigation 3 in Compose", "Compose"),
    ("compose-lifecycle-viewmodel-scoping", "ViewModel Scoping in Compose Navigation", "Compose"),
    ("compose-hilt-navigation-compose", "Hilt and Navigation Compose Integration", "Compose"),
    ("compose-koin-compose-scoping", "Koin Scoping in Compose Apps", "Compose"),
    ("compose-retained-state-savable", "Retained State with rememberSaveable", "Compose"),
    ("compose-derived-state-optimization", "derivedStateOf for Compose Performance", "Compose"),
    ("compose-stability-strong-skipping", "Strong Skipping Mode in Compose Compiler", "Compose"),
    ("compose-recomposition-count-debug", "Debugging Recomposition Counts in Compose", "Compose"),
    ("compose-layout-inspector-tools", "Layout Inspector for Compose Debugging", "Compose"),
    ("compose-ui-test-semantics", "Semantics and Accessibility Testing in Compose", "Compose"),
    ("compose-screenshot-testing-paparazzi", "Screenshot Testing with Paparazzi", "Compose"),
    ("compose-preview-parameter-providers", "Preview Parameter Providers in Compose", "Compose"),
    ("compose-interactive-previews", "Interactive Previews in Android Studio", "Compose"),
    ("compose-animation-shared-element", "Shared Element Transitions in Compose", "Compose"),
    ("compose-animation-animated-content", "AnimatedContent for State Transitions", "Compose"),
    ("compose-lottie-compose-integration", "Lottie Animations in Jetpack Compose", "Compose"),
    ("compose-rive-vector-animations", "Rive Vector Animations in Compose", "Compose"),
    ("compose-canvas-custom-drawing", "Custom Drawing with Compose Canvas", "Compose"),
    ("compose-graphics-layer-effects", "GraphicsLayer Effects in Compose", "Compose"),
    ("compose-blur-modifier-effects", "Blur and Visual Effects in Compose", "Compose"),
    ("compose-webview-accompanist", "Embedding WebViews in Compose", "Compose"),
    ("compose-map-compose-integration", "Google Maps Compose Integration", "Compose"),
    ("compose-camera-camerax-compose", "CameraX with Jetpack Compose", "Compose"),
    ("compose-barcode-scanner-compose", "Barcode Scanning in Compose Apps", "Compose"),
    ("compose-biometric-prompt-compose", "Biometric Prompt in Compose", "Compose"),
    ("compose-permissions-accompanist", "Runtime Permissions in Compose", "Compose"),
    ("compose-location-permissions-flow", "Location Permission Flows in Compose", "Compose"),
    ("compose-notification-permission-android13", "Notification Permission UX in Compose", "Compose"),
    ("compose-in-app-update-compose", "In-App Updates UI with Compose", "Compose"),
    ("compose-review-manager-compose", "In-App Review Prompts in Compose", "Compose"),
    ("compose-play-integrity-check", "Play Integrity Checks in Compose Apps", "Compose"),
    ("compose-feature-delivery-ui", "Feature Delivery UI Patterns in Compose", "Compose"),
    ("compose-app-shortcuts-compose", "App Shortcuts with Compose Deep Links", "Compose"),
    # Android platform (45)
    ("android-16-edge-to-edge-enforcement", "Android 16 Edge-to-Edge Enforcement", "Android"),
    ("android-predictive-back-gesture", "Predictive Back Gesture Implementation", "Android"),
    ("android-permission-photopicker-only", "Photo Picker Only: Dropping Storage Permissions", "Android"),
    ("android-foreground-service-restrictions", "Foreground Service Restrictions on Android 15+", "Android"),
    ("android-broadcast-receiver-exported", "Exported vs Non-Exported Broadcast Receivers", "Android"),
    ("android-safer-intents-validation", "Safer Intents and PendingIntent Flags", "Android"),
    ("android-splashscreen-api-migration", "SplashScreen API Migration Guide", "Android"),
    ("android-window-insets-handling", "Window Insets Handling on Modern Android", "Android"),
    ("android-display-cutout-notches", "Display Cutout and Notch Handling", "Android"),
    ("android-foldable-state-posture", "Foldable Posture and State Detection", "Android"),
    ("android-large-screen-optimization", "Large Screen Optimization for Android", "Android"),
    ("android-desktop-mode-support", "Desktop Mode Support on Android", "Android"),
    ("android-chromeos-app-optimization", "ChromeOS Android App Optimization", "Android"),
    ("android-automotive-app-design", "Designing Apps for Android Automotive", "Android"),
    ("android-wear-os-compose-tiles", "Wear OS Compose and Tiles", "Android"),
    ("android-tv-leanback-compose", "Android TV with Compose for TV", "Android"),
    ("android-xr-headset-development", "Android XR Headset Development Basics", "Android"),
    ("android-health-connect-permissions", "Health Connect Permissions and Data Types", "Android"),
    ("android-fitness-api-integration", "Fitness API Integration on Android", "Android"),
    ("android-sensor-batch-processing", "Batch Processing Android Sensor Data", "Android"),
    ("android-activity-recognition-api", "Activity Recognition API on Android", "Android"),
    ("android-geofencing-battery-efficient", "Battery-Efficient Geofencing on Android", "Android"),
    ("android-fused-location-provider", "Fused Location Provider Best Practices", "Android"),
    ("android-background-location-policy", "Background Location Policy Compliance", "Android"),
    ("android-wifi-scanning-privacy", "Wi-Fi Scanning and Privacy on Android", "Android"),
    ("android-bluetooth-le-scanning", "BLE Scanning Patterns on Android", "Android"),
    ("android-nfc-hce-payment", "NFC Host Card Emulation for Payments", "Android"),
    ("android-uwb-ranging-api", "UWB Ranging API on Android", "Android"),
    ("android-thread-border-router", "Thread Border Router on Android", "Android"),
    ("android-matter-commissioning", "Matter Device Commissioning on Android", "Android"),
    ("android-usb-accessory-mode", "USB Accessory Mode on Android", "Android"),
    ("android-serial-port-communication", "Serial Port Communication on Android", "Android"),
    ("android-hid-device-profile", "HID Device Profile on Android", "Android"),
    ("android-print-framework-integration", "Android Print Framework Integration", "Android"),
    ("android-document-provider-files", "Document Provider for File Sharing", "Android"),
    ("android-storage-access-framework", "Storage Access Framework Patterns", "Android"),
    ("android-media-store-scoped", "Scoped Storage and MediaStore Queries", "Android"),
    ("android-download-manager-resume", "DownloadManager with Resume Support", "Android"),
    ("android-share-sheet-direct-share", "Direct Share Targets on Android", "Android"),
    ("android-shortcuts-static-dynamic", "Static and Dynamic App Shortcuts", "Android"),
    ("android-widgets-glance-complications", "Glance Widgets and Complications", "Android"),
    ("android-live-wallpaper-compose", "Live Wallpaper with Compose Rendering", "Android"),
    ("android-dream-service-screensaver", "Dream Service Screensaver Apps", "Android"),
    ("android-voice-interaction-service", "Voice Interaction Service on Android", "Android"),
    ("android-assist-structure-extraction", "Assist Structure for Context Extraction", "Android"),
    # Flutter / Dart (40)
    ("flutter-impeller-rendering-engine", "Impeller Rendering Engine in Flutter", "Flutter"),
    ("flutter-web-wasm-compilation", "Flutter Web Wasm Compilation", "Flutter"),
    ("flutter-desktop-multi-window", "Multi-Window Support in Flutter Desktop", "Flutter"),
    ("flutter-platform-views-hybrid", "Hybrid Composition Platform Views", "Flutter"),
    ("flutter-texture-layer-hybrid", "Texture Layer Hybrid Composition", "Flutter"),
    ("flutter-isolate-compute-heavy", "Isolates for Compute-Heavy Flutter Work", "Flutter"),
    ("flutter-ffi-native-interop", "FFI Native Interop in Flutter", "Flutter"),
    ("flutter-pigeon-code-generation", "Pigeon for Type-Safe Platform Channels", "Flutter"),
    ("flutter-method-channel-patterns", "Method Channel Patterns in Flutter", "Flutter"),
    ("flutter-event-channel-streams", "Event Channels for Native Streams", "Flutter"),
    ("flutter-basic-message-channels", "Basic Message Channels in Flutter", "Flutter"),
    ("flutter-plugin-federated-architecture", "Federated Plugin Architecture", "Flutter"),
    ("flutter-plugin-platform-interface", "Platform Interface Pattern for Plugins", "Flutter"),
    ("flutter-integration-test-patrol", "Integration Testing with Patrol", "Flutter"),
    ("flutter-golden-test-comparison", "Golden File Testing in Flutter", "Flutter"),
    ("flutter-widget-test-finders", "Widget Test Finders and Matchers", "Flutter"),
    ("flutter-mockito-riverpod-test", "Mockito with Riverpod Testing", "Flutter"),
    ("flutter-bloc-test-patterns", "bloc_test Patterns for Flutter", "Flutter"),
    ("flutter-flutter-driver-e2e", "Flutter Driver E2E Testing", "Flutter"),
    ("flutter-firebase-app-check", "Firebase App Check in Flutter", "Flutter"),
    ("flutter-firebase-crashlytics-setup", "Crashlytics Setup in Flutter Apps", "Flutter"),
    ("flutter-firebase-analytics-events", "Firebase Analytics Events in Flutter", "Flutter"),
    ("flutter-firebase-remote-config-ab", "Remote Config A/B Tests in Flutter", "Flutter"),
    ("flutter-firebase-messaging-topics", "FCM Topic Messaging in Flutter", "Flutter"),
    ("flutter-supabase-auth-realtime", "Supabase Auth and Realtime in Flutter", "Flutter"),
    ("flutter-appwrite-backend", "Appwrite Backend Integration in Flutter", "Flutter"),
    ("flutter-pocketbase-integration", "PocketBase Integration in Flutter", "Flutter"),
    ("flutter-strapi-headless-cms", "Strapi Headless CMS with Flutter", "Flutter"),
    ("flutter-sanity-cms-content", "Sanity CMS Content in Flutter Apps", "Flutter"),
    ("flutter-contentful-delivery-api", "Contentful Delivery API in Flutter", "Flutter"),
    ("flutter-algolia-search-integration", "Algolia Search in Flutter Apps", "Flutter"),
    ("flutter-typesense-search", "Typesense Search Integration in Flutter", "Flutter"),
    ("flutter-meilisearch-integration", "Meilisearch in Flutter Applications", "Flutter"),
    ("flutter-elasticsearch-dart-client", "Elasticsearch Dart Client in Flutter", "Flutter"),
    ("flutter-mapbox-maps-flutter", "Mapbox Maps SDK for Flutter", "Flutter"),
    ("flutter-google-maps-clustering", "Google Maps Marker Clustering in Flutter", "Flutter"),
    ("flutter-geolocator-permissions", "Geolocator Permissions in Flutter", "Flutter"),
    ("flutter-background-geolocation", "Background Geolocation in Flutter", "Flutter"),
    ("flutter-local-notifications-scheduling", "Local Notifications Scheduling in Flutter", "Flutter"),
    ("flutter-awesome-notifications", "Awesome Notifications Plugin Patterns", "Flutter"),
]

# Continue adding topics in categories until we have 989+ candidates, then filter

MORE = Path(__file__).with_name("gen-wave2-topics-extra.json")
if MORE.exists():
    TOPICS.extend(json.loads(MORE.read_text()))

# Dedupe and filter existing
seen = set()
unique = []
for slug, title, cat in TOPICS:
    if slug in existing or slug in seen:
        continue
    seen.add(slug)
    unique.append({"slug": slug, "title": title, "category": cat})

out = ROOT / "scripts" / "wave2-topics.json"
out.write_text(json.dumps(unique, indent=2))
print(f"Existing posts: {len(existing)}")
print(f"New topics in seed: {len(unique)}")
print(f"Need: {989 - len(unique)} more from extra file")
