#!/usr/bin/env python3
"""Topic list for Batch A: Android / Kotlin / Jetpack posts."""

# Each: (slug, title, description, tags, keywords)
TOPICS = [
    ("android-compose-material-theme-customization", "Material Theme Customization in Jetpack Compose",
     "Build a production Material 3 theme in Compose: color roles, typography scale, shape tokens, and CompositionLocal patterns that survive dark mode and dynamic color.",
     ["Android", "Jetpack Compose", "Material 3"], "Compose Material theme, Material 3 customization, color roles, typography scale, dynamic color Android"),
    ("android-compose-navigation-animated-graph", "Animated Navigation Graphs in Compose",
     "Animate transitions between Compose destinations: NavHost enter/exit, shared elements, and predictive back integration without janky recomposition.",
     ["Android", "Jetpack Compose", "Navigation"], "Compose navigation animation, NavHost transitions, animated graph, predictive back Compose"),
    ("android-room-type-converters-dates", "Room Type Converters for Dates and Enums",
     "Type converters for Room: Instant, LocalDate, enums, and JSON columns — migration-safe patterns and testing converter round-trips.",
     ["Android", "Room", "Kotlin"], "Room type converters, Instant Room, enum converter, Room custom types"),
    ("android-room-transaction-patterns", "Room Transaction Patterns That Avoid Deadlocks",
     "Multi-table writes with @Transaction, runInTransaction, and coroutine dispatchers — patterns that stay correct under concurrent readers.",
     ["Android", "Room", "Architecture"], "Room transactions, @Transaction Room, concurrent Room writes, database deadlock Android"),
    ("android-workmanager-unique-work-chains", "WorkManager Unique Work and Chains",
     "Enqueue unique work, build dependency chains, and handle REPLACE vs KEEP policies for reliable background sync on Android.",
     ["Android", "WorkManager", "Background"], "WorkManager unique work, work chains Android, ExistingWorkPolicy, background sync"),
    ("android-play-billing-subscription-lifecycle", "Play Billing Subscription Lifecycle",
     "Google Play Billing Library 7+: purchase flow, subscription states, grace periods, and server-side validation with Real-Time Developer Notifications.",
     ["Android", "Play Billing", "Monetization"], "Play Billing subscriptions, BillingClient lifecycle, subscription grace period, RTDN Android"),
    ("android-play-billing-consumables-testing", "Testing Play Billing Consumables",
     "Test consumable in-app purchases: license testers, static responses, pending purchases, and CI-friendly billing fakes.",
     ["Android", "Play Billing", "Testing"], "Play Billing testing, consumable IAP test, BillingClient test, license tester Android"),
    ("android-espresso-idling-resource-patterns", "Espresso Idling Resource Patterns",
     "Synchronize Espresso with async work: CountingIdlingResource, OkHttp IdlingResource, and Compose test idle policies without flaky waits.",
     ["Android", "Testing", "Espresso"], "Espresso idling resource, CountingIdlingResource, async Espresso tests, OkHttp idling"),
    ("android-mvi-unidirectional-data-flow", "MVI and Unidirectional Data Flow on Android",
     "Model-View-Intent on Android: sealed UiState, intent reducers, and testing pure state transitions in ViewModels.",
     ["Android", "Architecture", "MVI"], "MVI Android, unidirectional data flow, ViewModel MVI, sealed UiState Kotlin"),
    ("android-clean-architecture-layers-practical", "Clean Architecture Layers in Practice",
     "Practical Clean Architecture for Android: domain use cases, repository boundaries, and when not to add another module.",
     ["Android", "Architecture", "Clean Architecture"], "Clean Architecture Android, domain layer, repository pattern, modular Android"),
    ("android-view-binding-vs-compose-migration", "View Binding vs Compose Migration Strategy",
     "Migrate screens from View Binding to Compose incrementally: interop, feature flags, and avoiding dual UI stacks forever.",
     ["Android", "Jetpack Compose", "Migration"], "View Binding to Compose, Android UI migration, Compose interop, incremental migration"),
    ("android-fragment-result-api-patterns", "Fragment Result API Patterns",
     "Pass results between fragments with Fragment Result API — replacing target fragments and avoiding stale listener leaks.",
     ["Android", "Fragments", "Navigation"], "Fragment Result API, setFragmentResult, fragment communication Android"),
    ("android-recyclerview-diffutil-performance", "DiffUtil Performance for RecyclerView",
     "ListAdapter, AsyncListDiffer, and DiffUtil.ItemCallback — keep scroll smooth on large lists without blocking the main thread.",
     ["Android", "RecyclerView", "Performance"], "DiffUtil Android, ListAdapter, AsyncListDiffer, RecyclerView performance"),
    ("android-coordinatorlayout-behavior-custom", "Custom CoordinatorLayout Behaviors",
     "Write custom Behavior classes for CoordinatorLayout: scroll-linked toolbars, FAB hide-on-scroll, and nested scrolling fixes.",
     ["Android", "UI", "Views"], "CoordinatorLayout Behavior, custom Behavior Android, AppBarLayout scroll"),
    ("android-servicelocator-antipattern-di", "Why Service Locator Is an Anti-Pattern on Android",
     "Service locator vs constructor injection: testability, compile-time safety, and migrating legacy singletons to Hilt.",
     ["Android", "Architecture", "Hilt"], "Service locator anti-pattern, dependency injection Android, Hilt migration"),
    ("android-proguard-rules-compose", "ProGuard Rules for Jetpack Compose",
     "R8 keep rules for Compose, Kotlin serialization, and reflection — shrink release builds without runtime ClassNotFoundException.",
     ["Android", "R8", "Jetpack Compose"], "ProGuard Compose, R8 keep rules Kotlin, Compose obfuscation, shrink release Android"),
    ("android-ndk-jni-basics-kotlin", "NDK and JNI Basics with Kotlin",
     "Call native C++ from Kotlin: JNI naming, jstring handling, and loading .so libraries with CMake and ABI splits.",
     ["Android", "NDK", "JNI"], "Android NDK Kotlin, JNI basics, native library Android, CMake NDK"),
    ("android-jni-string-encoding-pitfalls", "JNI String Encoding Pitfalls",
     "UTF-8 vs Modified UTF-8 in JNI: GetStringUTFChars leaks, NewStringUTF crashes, and safe string marshaling patterns.",
     ["Android", "JNI", "NDK"], "JNI string encoding, NewStringUTF, JNI UTF-8, native string Android"),
    ("android-opengl-es-basics-compose", "OpenGL ES Basics with Compose",
     "Embed GLSurfaceView in Compose via AndroidView: render thread lifecycle, EGL context, and touch forwarding.",
     ["Android", "OpenGL", "Jetpack Compose"], "OpenGL ES Android, GLSurfaceView Compose, AndroidView OpenGL, EGL Android"),
    ("android-vulkan-mobile-basics", "Vulkan on Mobile Android Basics",
     "When to choose Vulkan over OpenGL ES: swap chains, validation layers in debug, and battery trade-offs on mid-range devices.",
     ["Android", "Vulkan", "Graphics"], "Vulkan Android mobile, Vulkan vs OpenGL ES, Android graphics API"),
    ("android-gpu-profiling-renderthread", "GPU Profiling and the RenderThread",
     "Profile GPU overdraw, RenderThread blocking, and HWUI with Perfetto — fix jank that Systrace alone won't explain.",
     ["Android", "Performance", "Profiling"], "RenderThread Android, GPU profiling, Perfetto Android, overdraw debugging"),
    ("android-battery-historian-analysis", "Battery Historian Analysis for Android Apps",
     "Use Battery Historian and bugreports to find wakelocks, alarm storms, and GPS abuse — actionable fixes for background work.",
     ["Android", "Battery", "Performance"], "Battery Historian, wakelock analysis Android, battery drain debugging"),
    ("android-wakelock-modern-alternatives", "Modern Alternatives to WakeLocks",
     "Replace partial wakelocks with WorkManager, FGS types, and AlarmManager setAndAllowWhileIdle — stay compliant on Android 14+.",
     ["Android", "Battery", "Background"], "WakeLock alternatives, partial wakelock Android, background battery optimization"),
    ("android-alarmmanager-exact-vs-inexact", "AlarmManager Exact vs Inexact Alarms",
     "Schedule alarms correctly: SCHEDULE_EXACT_ALARM permission, inexact batching for battery, and migrating from setRepeating.",
     ["Android", "AlarmManager", "Background"], "AlarmManager exact alarm, inexact alarm Android, SCHEDULE_EXACT_ALARM permission"),
    ("android-jobscheduler-vs-workmanager", "JobScheduler vs WorkManager Decision Guide",
     "When JobScheduler still matters, when WorkManager wins, and how to unify constraints across OEM-specific battery savers.",
     ["Android", "WorkManager", "JobScheduler"], "JobScheduler vs WorkManager, background work Android, JobInfo constraints"),
    ("android-syncadapter-legacy-migration", "Migrating Legacy SyncAdapter to WorkManager",
     "Retire SyncAdapter: account sync settings UX, periodic sync with network constraints, and content observer replacements.",
     ["Android", "Migration", "WorkManager"], "SyncAdapter migration, legacy sync Android, WorkManager periodic sync"),
    ("android-account-authenticator-patterns", "AccountAuthenticator Patterns on Android",
     "Custom AccountAuthenticator for enterprise SSO: addAccount flow, token refresh, and AccountManager security boundaries.",
     ["Android", "Security", "Accounts"], "AccountAuthenticator Android, AccountManager, custom account type Android"),
    ("android-contacts-provider-integration", "Contacts Provider Integration",
     "Read and write contacts with ContactsContract: batch operations, aggregation, and scoped permission on modern Android.",
     ["Android", "ContentProvider", "Contacts"], "ContactsContract Android, contacts provider, READ_CONTACTS permission"),
    ("android-calendar-provider-sync", "Calendar Provider Sync Patterns",
     "Insert events via CalendarContract, handle time zones, and sync recurring events without duplicate calendar entries.",
     ["Android", "Calendar", "ContentProvider"], "CalendarContract Android, calendar sync, calendar provider integration"),
    ("android-sms-retriever-api-otp", "SMS Retriever API for OTP Auto-Fill",
     "Implement SMS Retriever for one-tap OTP: app hash generation, 11-character hash in SMS body, and fallback manual entry.",
     ["Android", "Security", "UX"], "SMS Retriever API, OTP auto-fill Android, app hash SMS, User Consent API"),
    ("android-phone-number-hint-api", "Phone Number Hint API Integration",
     "Google Play services Phone Number Hint: reduce friction at signup without READ_PHONE_STATE or SMS permissions.",
     ["Android", "Identity", "UX"], "Phone Number Hint API, Identity API Android, signup friction reduction"),
    ("android-credential-manager-passkeys", "Credential Manager and Passkeys on Android",
     "Implement passkeys with Credential Manager: createCredential, getCredential, and syncing with password managers.",
     ["Android", "Security", "Passkeys"], "Credential Manager Android, passkeys Android, WebAuthn mobile, passwordless Android"),
    ("android-webview-security-hardening", "WebView Security Hardening",
     "Secure WebView: disable file access, validate SSL, restrict JavaScript bridges, and sandbox WebView processes.",
     ["Android", "WebView", "Security"], "WebView security Android, JavaScript interface security, WebView hardening"),
    ("android-chrome-custom-tabs-auth", "Chrome Custom Tabs for OAuth Flows",
     "OAuth in Custom Tabs vs WebView: redirect handling, warm-up, and session sharing with Trusted Web Activity patterns.",
     ["Android", "OAuth", "Chrome Custom Tabs"], "Chrome Custom Tabs OAuth, Custom Tabs auth flow, Android OAuth best practice"),
    ("android-trusted-web-activity-pwa", "Trusted Web Activity for PWAs on Android",
     "Ship a PWA in the Play Store with TWA: Digital Asset Links, splash screens, and notification delegation.",
     ["Android", "PWA", "Play Store"], "Trusted Web Activity, TWA Android, PWA Play Store, Digital Asset Links"),
    ("android-app-bundle-size-optimization", "Android App Bundle Size Optimization",
     "Shrink AAB size: language splits, density splits, R8 full mode, resource shrinking, and unused native ABI removal.",
     ["Android", "Performance", "Play Store"], "App bundle size optimization, AAB splits, R8 shrink Android, APK size reduction"),
    ("android-dynamic-feature-module-testing", "Testing Dynamic Feature Modules",
     "Test on-demand modules: SplitInstallManager fakes, Play Feature Delivery in internal testing, and baseline module coverage.",
     ["Android", "Modularization", "Testing"], "Dynamic feature module testing, SplitInstallManager, on-demand delivery test"),
    ("android-instant-apps-legacy", "Legacy Instant Apps and App Links Migration",
     "Instant Apps deprecation path: migrate to Play Instant or full install flows with deferred deep linking.",
     ["Android", "Play Store", "Deep Links"], "Instant Apps legacy, Google Play Instant, deferred deep link Android"),
    ("android-play-feature-delivery-on-demand", "Play Feature Delivery On-Demand Modules",
     "Configure on-demand and conditional modules: user country, device RAM, and install-time vs on-demand trade-offs.",
     ["Android", "Play Store", "Modularization"], "Play Feature Delivery, on-demand modules, conditional modules Android"),
    ("android-play-console-vitals-debugging", "Debugging Play Console Vitals",
     "Interpret Android Vitals: ANR clusters, slow cold start, excessive wakeups — map clusters to code paths with tags.",
     ["Android", "Play Console", "Performance"], "Play Console vitals, ANR cluster Android, vitals debugging, slow start Play"),
    ("android-pre-launch-report-fixes", "Fixing Pre-Launch Report Issues",
     "Address Pre-Launch Report crashes: Crawler-specific bugs, login walls, and content description gaps before production.",
     ["Android", "Play Store", "Testing"], "Pre-Launch Report, Play Store testing, pre-launch crash fix Android"),
    ("android-store-listing-experiments", "Play Store Listing Experiments",
     "Run store listing experiments: icon, short description, and screenshot variants with statistical significance guidance.",
     ["Android", "Play Store", "Growth"], "Play Store experiments, store listing A/B test, ASO Android experiments"),
    ("android-app-signing-play-app-signing", "Play App Signing and Upload Keys",
     "Manage upload keys vs app signing keys: key rotation, PEPK export, and recovery when upload key is lost.",
     ["Android", "Play Store", "Security"], "Play App Signing, upload key rotation, app signing key Android"),
    ("android-keystore-hardware-backed-keys", "Hardware-Backed Keystore Keys",
     "Generate keys in StrongBox or TEE: setUserAuthenticationRequired, key attestation, and biometric-bound crypto.",
     ["Android", "Security", "Keystore"], "Android Keystore hardware, StrongBox, key attestation Android, biometric crypto"),
    ("android-safety-net-play-integrity-migration", "Migrating SafetyNet to Play Integrity API",
     "Replace SafetyNet Attestation with Play Integrity: standard vs classic requests, server-side verdict parsing.",
     ["Android", "Security", "Play Integrity"], "Play Integrity API, SafetyNet migration, device attestation Android"),
    ("android-device-attestation-verification", "Device Attestation Verification Server-Side",
     "Verify Android key attestation certificates on your backend: root of trust, certificate chain, and tamper signals.",
     ["Android", "Security", "Backend"], "device attestation verification, key attestation server, Android root of trust"),
    ("android-tamper-detection-runtime-checks", "Runtime Tamper Detection on Android",
     "Detect root, debuggers, and repackaged APKs: Play Integrity, signature checks, and avoiding false positives on emulators.",
     ["Android", "Security", "Anti-Tamper"], "tamper detection Android, root detection, APK signature verification runtime"),
    ("android-ssl-pinning-rotation", "SSL Pinning Rotation Strategy",
     "Pin OkHttp certificates with backup pins, rotation windows, and crash-safe updates via remote config.",
     ["Android", "Security", "Networking"], "SSL pinning rotation, OkHttp certificate pinning, network security pinning Android"),
    ("android-certificate-transparency-android", "Certificate Transparency on Android",
     "CT log verification with network_security_config and OkHttp — detect misissued certs without breaking corporate proxies.",
     ["Android", "Security", "TLS"], "Certificate Transparency Android, CT logs mobile, TLS verification Android"),
    ("android-encrypted-file-storage", "Encrypted File Storage on Android",
     "Encrypt files at rest with EncryptedFile, Jetpack Security, and streaming encryption for large media downloads.",
     ["Android", "Security", "Storage"], "EncryptedFile Android, encrypted storage mobile, Jetpack Security crypto"),
    ("android-biometric-crypto-object", "BiometricPrompt with CryptoObject",
     "Bind BiometricPrompt to Keystore Cipher: Class 3 biometrics, invalidation on enrollment change, and fallback PIN.",
     ["Android", "Security", "Biometrics"], "BiometricPrompt CryptoObject, biometric encryption Android, Class 3 biometric"),
    ("android-screen-capture-prevention", "Screen Capture Prevention on Android",
     "FLAG_SECURE for sensitive screens: compliance trade-offs, screenshot detection API, and screen recording on Android 14+.",
     ["Android", "Security", "Compliance"], "FLAG_SECURE Android, screen capture prevention, screenshot detection API"),
    ("android-overlay-permission-security", "Overlay Permission Security Risks",
     "SYSTEM_ALERT_WINDOW abuse: detect overlay attacks, guide users away from malicious screen overlays, banking app patterns.",
     ["Android", "Security", "UX"], "overlay permission Android, SYSTEM_ALERT_WINDOW security, tapjacking prevention"),
    ("android-task-hijacking-prevention", "Task Hijacking and StrandHogg Prevention",
     "Prevent task affinity hijacking: singleTask launch modes, allowTaskReparenting=false, and intent filter audit.",
     ["Android", "Security", "Activities"], "task hijacking Android, StrandHogg prevention, launch mode security"),
    ("android-intent-redirection-vulnerabilities", "Intent Redirection Vulnerabilities",
     "Audit exported components for intent redirection: validate caller, strip sensitive extras, and use PendingIntent flags.",
     ["Android", "Security", "Intents"], "intent redirection Android, exported component security, PendingIntent security"),
    ("android-content-provider-sql-injection", "Content Provider SQL Injection Prevention",
     "Parameterized queries in ContentProvider, URI permission grants, and avoiding path traversal in openFile.",
     ["Android", "Security", "ContentProvider"], "ContentProvider SQL injection, URI permissions Android, provider security"),
    ("android-webview-javascript-bridge-security", "WebView JavaScript Bridge Security",
     "@JavascriptInterface exposure rules, validate origins, and remove addJavascriptInterface on API 17+ pitfalls.",
     ["Android", "WebView", "Security"], "JavascriptInterface security, WebView bridge Android, addJavascriptInterface safe"),
    ("android-log-redaction-production", "Log Redaction in Production Android Apps",
     "Strip PII from Timber/Logcat: ProGuard log removal, remote logging filters, and crash report scrubbing.",
     ["Android", "Security", "Logging"], "log redaction Android, PII logging prevention, production logging Android"),
    ("android-debuggable-flag-risks", "Debuggable Flag Risks in Release Builds",
     "Ensure android:debuggable=false in release: Gradle checks, Play Console warnings, and runtime detection.",
     ["Android", "Security", "Build"], "debuggable flag Android, release build security, debuggable detection"),
    ("android-backup-rules-exclude-secrets", "Backup Rules to Exclude Secrets",
     "Configure backup_rules.xml and data_extraction_rules: exclude SharedPreferences tokens, Keystore, and database keys.",
     ["Android", "Security", "Backup"], "backup rules Android, data extraction rules, exclude secrets backup Android"),
    ("android-autofill-framework-integration", "Autofill Framework Integration",
     "Optimize for Autofill: importantForAutofill, AutofillValue hints, and password manager compatibility.",
     ["Android", "UX", "Autofill"], "Autofill framework Android, importantForAutofill, password autofill integration"),
    ("android-clipboard-sensitive-data", "Clipboard Sensitive Data Handling",
     "Clear clipboard on background, disable copy on OTP fields, and Android 13+ clipboard overlay notifications.",
     ["Android", "Security", "UX"], "clipboard security Android, sensitive data clipboard, clipboard overlay Android 13"),
    ("android-screenshot-detection-api", "Screenshot Detection API on Android",
     "Detect screenshots with Activity.ScreenCaptureCallback: audit logging, DLP compliance, and user education UX.",
     ["Android", "Security", "API"], "screenshot detection Android, ScreenCaptureCallback, DLP mobile Android"),
    ("android-picture-in-picture-compose", "Picture-in-Picture with Jetpack Compose",
     "Enter PiP mode from Compose: aspect ratio, remote actions, and media playback controls in PiP window.",
     ["Android", "Jetpack Compose", "Media"], "Picture in Picture Compose, PiP mode Android, Compose PiP controls"),
    ("android-multi-window-drag-drop", "Multi-Window Drag and Drop on Android",
     "DragAndDrop across split-screen apps: ClipData, DropHelper, and Compose drag modifiers for tablets.",
     ["Android", "Tablet", "UX"], "multi-window drag drop Android, split screen drag, DropHelper Android"),
    ("android-split-screen-state-restoration", "Split-Screen State Restoration",
     "Save state across multi-window resize: ViewModel retention, configChanges, and Compose saveable in split mode.",
     ["Android", "Multi-Window", "State"], "split screen state Android, multi-window state restoration, resize handling"),
    ("android-keyboard-ime-insets-compose", "Keyboard IME Insets in Compose",
     "WindowInsets.ime animation: bring fields into view, nested scroll, and edge-to-edge with keyboard open.",
     ["Android", "Jetpack Compose", "IME"], "IME insets Compose, keyboard insets animation, WindowInsets.ime Compose"),
    ("android-soft-input-mode-handling", "softInputMode Handling for Android Forms",
     "adjustResize vs adjustPan: manifest vs WindowCompat, and fixing keyboard covering inputs on edge-to-edge.",
     ["Android", "IME", "Views"], "softInputMode Android, adjustResize adjustPan, keyboard form Android"),
    ("android-input-connection-custom-ime", "InputConnection for Custom IME Integration",
     "Build custom input editors: InputConnection, EditorInfo, and Compose BasicTextField IME callbacks.",
     ["Android", "IME", "Compose"], "InputConnection Android, custom IME integration, EditorInfo Compose"),
    ("android-handwriting-stylus-apis", "Handwriting Stylus APIs on Android",
     "Stylus handwriting: MotionEvent tool type, palm rejection, and Ink API integration for note-taking apps.",
     ["Android", "Stylus", "Input"], "handwriting stylus Android, stylus input API, palm rejection Android"),
    ("android-ink-api-stylus-low-latency", "Ink API for Low-Latency Stylage Drawing",
     "Android Ink API: stroke prediction, latency compensation, and Canvas vs OpenGL for drawing apps.",
     ["Android", "Stylus", "Graphics"], "Android Ink API, low latency drawing, stylus latency Android"),
    ("android-haptic-feedback-compose", "Haptic Feedback in Jetpack Compose",
     "LocalHapticFeedback, HapticFeedbackType, and composition-based haptics for toggles and success confirmations.",
     ["Android", "Jetpack Compose", "UX"], "haptic feedback Compose, LocalHapticFeedback, vibration UX Android"),
    ("android-vibration-composition-effects", "Vibration Composition Effects API",
     "VibrationEffect.Composition for rich haptics: PRIMITIVE_CLICK, customizable amplitudes, and hardware capability checks.",
     ["Android", "Haptics", "API"], "VibrationEffect composition, rich haptics Android, haptic primitives API"),
    ("android-audio-focus-management", "Audio Focus Management on Android",
     "Request/abandon audio focus: AUDIOFOCUS_LOSS_TRANSIENT, ducking, and Media3 AudioFocusRequest integration.",
     ["Android", "Media", "Audio"], "audio focus Android, AudioManager focus, Media3 audio focus"),
    ("android-exoplayer-offline-download", "ExoPlayer Offline Download Management",
     "DownloadManager with Media3: progressive and HLS offline, license renewal for DRM, and storage quota UX.",
     ["Android", "Media3", "Offline"], "ExoPlayer offline download, Media3 DownloadManager, HLS offline Android"),
    ("android-media-session-controls", "MediaSession Controls and Platform Integration",
     "MediaSessionCompat with Media3: lock screen controls, Bluetooth AVRCP, Android Auto, and notification media style.",
     ["Android", "Media3", "MediaSession"], "MediaSession Android, lock screen media controls, Media3 session"),
    ("android-cast-google-cast-integration", "Google Cast Integration on Android",
     "Cast SDK with Media3: receiver app ID, expanded controls, and local playback fallback when Cast unavailable.",
     ["Android", "Cast", "Media"], "Google Cast Android, Cast SDK Media3, Chromecast integration mobile"),
    ("android-bluetooth-a2dp-profiles", "Bluetooth A2DP Audio Profiles",
     "Route audio to Bluetooth A2DP: BluetoothAdapter profiles, connection state, and latency considerations for media apps.",
     ["Android", "Bluetooth", "Audio"], "Bluetooth A2DP Android, audio routing Bluetooth, A2DP profile Android"),
    ("android-bluetooth-gatt-server", "Bluetooth GATT Server on Android",
     "Implement a GATT server: advertise services, notify characteristics, and handle MTU negotiation for IoT peripherals.",
     ["Android", "Bluetooth", "IoT"], "GATT server Android, BLE peripheral mode, Bluetooth LE server Kotlin"),
    ("android-wifi-direct-p2p", "Wi-Fi Direct P2P on Android",
     "WifiP2pManager for peer discovery and group formation: permissions, connection info, and large file transfer UX.",
     ["Android", "Wi-Fi", "Networking"], "Wi-Fi Direct Android, WifiP2pManager, P2P file transfer Android"),
    ("android-nearby-share-api", "Nearby Share API Integration",
     "Share files with Nearby Share intents: Fast Share compatibility, large payload handling, and privacy UX.",
     ["Android", "Nearby", "UX"], "Nearby Share Android, share sheet Android, direct share nearby"),
    ("android-uwb-secure-ranging", "UWB Secure Ranging Sessions",
     "Ultra-wideband secure ranging: session keys, distance measurement accuracy, and accessory tracking patterns.",
     ["Android", "UWB", "Security"], "UWB secure ranging Android, ultra wideband distance, UWB session Android"),
    ("android-5g-network-slicing-awareness", "5G Network Slicing Awareness on Android",
     "Detect 5G NR capabilities: NetworkCapabilities transport info, URSP policies, and bandwidth-sensitive downloads.",
     ["Android", "Networking", "5G"], "5G network slicing Android, NetworkCapabilities 5G, NR capability Android"),
    ("android-connectivity-manager-callbacks", "ConnectivityManager Network Callbacks",
     "Register NetworkCallback for validated internet: onAvailable, onLost, and multi-network request patterns.",
     ["Android", "Networking", "Connectivity"], "NetworkCallback Android, ConnectivityManager, network availability Kotlin"),
    ("android-network-capabilities-detection", "NetworkCapabilities Detection Patterns",
     "Detect VPN, metered, unmetered, and captive portal: download policy, video quality, and sync scheduling.",
     ["Android", "Networking", "Offline"], "NetworkCapabilities Android, metered network detection, VPN detection Android"),
    ("android-captive-portal-detection", "Captive Portal Detection Handling",
     "Respond to NET_CAPABILITY_CAPTIVE_PORTAL: custom login flow, avoid sync storms on hotel Wi-Fi.",
     ["Android", "Networking", "Wi-Fi"], "captive portal Android, captive portal detection, hotel Wi-Fi app Android"),
    ("android-vpn-service-basics", "VpnService Basics for Android Apps",
     "Build a VPN tunnel app: VpnService.Builder, TUN interface, foreground service type VPN, and user consent.",
     ["Android", "VPN", "Networking"], "VpnService Android, VPN app development, TUN interface Android"),
    ("android-dns-over-https-config", "DNS over HTTPS Configuration on Android",
     "Private DNS settings vs app-level DoH: network_security_config cleartext, and resolver fallback behavior.",
     ["Android", "Networking", "Security"], "DNS over HTTPS Android, Private DNS Android, DoH mobile configuration"),
    ("android-traffic-stats-monitoring", "TrafficStats Monitoring for Data Usage",
     "Track uid rx/tx bytes: TrafficStats API, subscriber ID deprecation, and user-facing data saver UI.",
     ["Android", "Networking", "Analytics"], "TrafficStats Android, data usage monitoring app, network bytes uid"),
    ("android-data-saver-mode-handling", "Data Saver Mode Handling",
     "Respect CONNECTIVITY_ACTION and restrictBackgroundStatus: defer uploads, lower image quality, user override settings.",
     ["Android", "Networking", "Battery"], "data saver mode Android, restrict background data, metered connection policy"),
    ("android-metered-connection-optimization", "Metered Connection Optimization",
     "Skip prefetch on metered networks: WorkManager constraints, Coil cache policy, and user-visible download prompts.",
     ["Android", "Networking", "Performance"], "metered connection Android, unmetered constraint WorkManager, mobile data optimization"),
    ("android-offline-first-sync-strategy", "Offline-First Sync Strategy for Mobile",
     "Design offline-first mobile apps: local source of truth, sync queue, conflict resolution, and optimistic UI.",
     ["Android", "Architecture", "Offline"], "offline-first Android, mobile sync strategy, local source of truth"),
    ("android-crdt-offline-sync-mobile", "CRDT Offline Sync on Mobile",
     "Apply CRDTs on Android clients: Automerge, Yjs bridges, and merge semantics for collaborative editing offline.",
     ["Android", "Offline", "Sync"], "CRDT mobile sync, offline collaborative Android, conflict-free replicated data"),
    ("android-event-sourcing-mobile-client", "Event Sourcing on Mobile Clients",
     "Event-sourced mobile architecture: append-only local log, projections in Room, and sync with server event store.",
     ["Android", "Architecture", "Event Sourcing"], "event sourcing mobile, Android event store, CQRS mobile client"),
    ("android-local-first-architecture", "Local-First Architecture on Android",
     "Local-first software on Android: zero-latency reads, background sync, and ownership of user data on device.",
     ["Android", "Architecture", "Local-First"], "local-first Android, offline-first architecture mobile, device-owned data"),
    ("android-sync-engine-custom-design", "Designing a Custom Sync Engine",
     "Build a sync engine: change feeds, cursor tokens, idempotent push, and exponential backoff with jitter.",
     ["Android", "Sync", "Architecture"], "custom sync engine Android, mobile sync engine design, change feed sync"),
    ("android-conflict-resolution-strategies", "Conflict Resolution Strategies for Mobile Sync",
     "Last-write-wins vs operational transform: version vectors, server authority, and user merge UI for conflicts.",
     ["Android", "Sync", "Offline"], "conflict resolution mobile, sync conflict Android, last write wins mobile"),
    ("android-timestamp-vector-clocks", "Vector Clocks for Mobile Sync",
     "Implement vector clocks on Android clients: causal ordering, Room storage, and detecting concurrent edits.",
     ["Android", "Sync", "Distributed Systems"], "vector clocks mobile, causal ordering sync, concurrent edit detection Android"),
    ("android-delta-sync-pagination", "Delta Sync with Pagination",
     "Incremental sync APIs: since_token cursors, paginated delta feeds, and checkpoint persistence across process death.",
     ["Android", "Sync", "API"], "delta sync pagination, incremental sync Android, sync cursor token"),
    ("android-graphql-apollo-android", "GraphQL with Apollo Android Client",
     "Apollo Kotlin on Android: normalized cache, watchers, offline mutations, and codegen with R8 keep rules.",
     ["Android", "GraphQL", "Apollo"], "Apollo Android, GraphQL mobile client, Apollo normalized cache Kotlin"),
    ("android-graphql-subscriptions-websocket", "GraphQL Subscriptions over WebSocket",
     "Apollo subscription transport: WebSocket reconnect, auth headers refresh, and battery-aware subscription lifecycle.",
     ["Android", "GraphQL", "WebSocket"], "GraphQL subscriptions Android, Apollo WebSocket, subscription reconnect mobile"),
    ("android-grpc-mobile-client-kotlin", "gRPC Mobile Client in Kotlin",
     "grpc-kotlin on Android: OkHttp channel, TLS, streaming RPC, and protobuf lite for smaller APK footprint.",
     ["Android", "gRPC", "Networking"], "gRPC Android Kotlin, grpc-kotlin mobile, protobuf lite Android"),
    ("android-websocket-okhttp-reconnection", "OkHttp WebSocket Reconnection Patterns",
     "Resilient WebSocket client: exponential backoff, heartbeat pings, auth token refresh, and ForegroundService for chat.",
     ["Android", "WebSocket", "OkHttp"], "OkHttp WebSocket reconnect, WebSocket Android Kotlin, chat WebSocket mobile"),
    ("android-sse-server-sent-events", "Server-Sent Events on Android",
     "Consume SSE with OkHttp: EventSource listener, parsing id/data fields, and fallback to long polling.",
     ["Android", "Networking", "SSE"], "Server-Sent Events Android, SSE OkHttp, EventSource mobile Kotlin"),
    ("android-long-polling-battery-tradeoffs", "Long Polling Battery Trade-offs on Android",
     "When long polling beats push: FCM delays, Doze impact, adaptive intervals, and WorkManager hybrid patterns.",
     ["Android", "Networking", "Battery"], "long polling Android battery, push vs poll mobile, adaptive polling Android"),
    ("android-push-fcm-data-messages", "FCM Data Messages vs Notification Messages",
     "Handle FCM data payloads in background: onMessageReceived, notification delegation, and high-priority trade-offs.",
     ["Android", "FCM", "Push"], "FCM data messages, notification messages Android, Firebase Cloud Messaging background"),
    ("android-fcm-topic-subscriptions", "FCM Topic Subscriptions at Scale",
     "Subscribe to topics: conditional topics, unsubscribe on logout, and avoiding topic explosion for personalization.",
     ["Android", "FCM", "Push"], "FCM topic subscription, Firebase topics Android, push topic management"),
    ("android-notification-channels-best-practices", "Notification Channels Best Practices",
     "Design notification channels: importance levels, user education, channel grouping, and settings deep links.",
     ["Android", "Notifications", "UX"], "notification channels Android, NotificationChannel best practices, channel importance"),
    ("android-notification-grouping-summary", "Notification Grouping and Summary Text",
     "Group notifications with setGroup, InboxStyle summary, and silent group children for messaging apps.",
     ["Android", "Notifications", "UX"], "notification grouping Android, InboxStyle summary, notification group key"),
    ("android-notification-bubbles-api", "Notification Bubbles API",
     "Implement conversation bubbles: BubbleMetadata, suppressBubble, and chat UX on Android 11+.",
     ["Android", "Notifications", "UX"], "notification bubbles Android, BubbleMetadata, conversation bubbles API"),
    ("android-notification-inline-replies", "Notification Inline Replies",
     "RemoteInput for inline reply: direct reply without opening app, PendingIntent mutability, and wear extender sync.",
     ["Android", "Notifications", "Messaging"], "notification inline reply, RemoteInput Android, direct reply notification"),
    ("android-notification-wearable-extender", "Wearable Extender for Notifications",
     "NotificationCompat.WearableExtender: pages, background, and bridging to Wear OS complication updates.",
     ["Android", "Notifications", "Wear OS"], "WearableExtender notification, Wear OS notification bridge, watch notification pages"),
    ("android-alarm-notification-scheduling", "Alarm-Based Notification Scheduling",
     "Schedule local notifications with AlarmManager and WorkManager: exact alarm permission UX and timezone/DST bugs.",
     ["Android", "Notifications", "AlarmManager"], "scheduled notifications Android, AlarmManager notification, local notification schedule"),
    ("android-exact-alarm-permission-flow", "Exact Alarm Permission User Flow",
     "SCHEDULE_EXACT_ALARM and USE_EXACT_ALARM: Settings intent, graceful degradation, and Play policy compliance.",
     ["Android", "AlarmManager", "Permissions"], "exact alarm permission Android, SCHEDULE_EXACT_ALARM UX, alarm permission flow"),
    ("android-do-not-disturb-policy-access", "Do Not Disturb Policy Access",
     "NotificationManager policy access: priority categories, automatic rule respect, and alarm bypass for critical alerts.",
     ["Android", "Notifications", "System"], "Do Not Disturb Android, notification policy access, DND priority Android"),
    ("android-full-screen-intent-permission", "Full-Screen Intent Permission on Android 14+",
     "USE_FULL_SCREEN_INTENT: alarm/call apps eligibility, permission revocation handling, and high-priority notification fallback.",
     ["Android", "Notifications", "Permissions"], "full screen intent permission, USE_FULL_SCREEN_INTENT Android 14, incoming call notification"),
    ("android-heads-up-notification-control", "Heads-Up Notification Control",
     "When heads-up shows: fullScreenIntent, high priority FCM, category CALL, and avoiding notification fatigue.",
     ["Android", "Notifications", "UX"], "heads-up notification Android, high priority notification, notification heads up control"),
    ("android-notification-trampoline-restrictions", "Notification Trampoline Restrictions",
     "Android 12+ trampoline limits: start activities from BroadcastReceiver, Activity PendingIntent patterns, and BAL exceptions.",
     ["Android", "Notifications", "Security"], "notification trampoline Android, BAL restrictions, PendingIntent activity launch"),
    ("android-foreground-service-notification-types", "Foreground Service Notification Types",
     "Map FGS types to user-visible disclosures: dataSync, mediaPlayback, location — and Android 14+ timeout rules.",
     ["Android", "Foreground Service", "Notifications"], "foreground service types Android, FGS notification, dataSync foreground service"),
    ("android-media-playback-foreground-service", "Media Playback Foreground Service",
     "MediaSessionService with FGS mediaPlayback: notification controls, stopSelf on pause, and Bluetooth disconnect handling.",
     ["Android", "Media", "Foreground Service"], "media playback foreground service, MediaSessionService Android, media FGS"),
    ("android-location-foreground-service", "Location Foreground Service Patterns",
     "FGS type location: background location approval, notification content, and fused provider batching for battery.",
     ["Android", "Location", "Foreground Service"], "location foreground service, FGS location type, background location Android"),
    ("android-short-service-exemption", "Short Foreground Service Exemption",
     "Android 15 short FGS: six-minute window, eligible use cases, and migrating long tasks to WorkManager.",
     ["Android", "Foreground Service", "Android 15"], "short foreground service Android, FGS timeout Android 15, six minute FGS"),
    ("android-boot-completed-receiver-limits", "BOOT_COMPLETED Receiver Limits",
     "Restricted boot receivers on Android 15+: direct boot, lazy initialization, and WorkManager deferral after boot.",
     ["Android", "BroadcastReceiver", "Background"], "BOOT_COMPLETED Android, boot receiver restrictions, direct boot aware Android"),
    ("android-receiver-exported-security", "Broadcast Receiver Exported Security",
     "android:exported audit: implicit intents, signature permissions, and LocalBroadcastManager replacements.",
     ["Android", "Security", "BroadcastReceiver"], "exported receiver security, BroadcastReceiver exported Android, implicit broadcast"),
    ("android-pending-intent-mutability-flags", "PendingIntent Mutability Flags",
     "FLAG_IMMUTABLE vs FLAG_MUTABLE: fill-in intents, inline replies, and Android 12+ enforcement crashes.",
     ["Android", "Security", "PendingIntent"], "PendingIntent mutability, FLAG_IMMUTABLE Android, PendingIntent flags Android 12"),
    ("android-pending-intent-immutable-patterns", "PendingIntent Immutable Patterns",
     "Safe PendingIntent creation: request codes, explicit intents, and avoiding intent hijacking with immutable flags.",
     ["Android", "Security", "PendingIntent"], "immutable PendingIntent patterns, PendingIntent security Android, explicit intent PendingIntent"),
    ("android-activity-launch-modes-deep-dive", "Activity Launch Modes Deep Dive",
     "standard, singleTop, singleTask, singleInstance: back stack behavior, deep link interactions, and task affinity.",
     ["Android", "Activities", "Navigation"], "activity launch modes Android, singleTask singleTop, back stack launch mode"),
    ("android-task-affinity-back-stack", "Task Affinity and Back Stack Control",
     "taskAffinity, allowTaskReparenting, and clearing tasks: multi-task apps, document launch mode, and recents UX.",
     ["Android", "Activities", "Tasks"], "task affinity Android, back stack control, allowTaskReparenting Android"),
    ("android-single-top-launch-behavior", "singleTop Launch Behavior Explained",
     "onNewIntent vs onCreate: notification deep links, search result stacking, and intent extra refresh patterns.",
     ["Android", "Activities", "Deep Links"], "singleTop Android, onNewIntent, launch mode singleTop deep link"),
    ("android-clear-top-intent-flags", "CLEAR_TOP and Intent Flag Combinations",
     "FLAG_ACTIVITY_CLEAR_TOP with singleTop/singleTask: predictable back stack when navigating from notifications.",
     ["Android", "Intents", "Navigation"], "FLAG_ACTIVITY_CLEAR_TOP, intent flags Android, clear top navigation"),
    ("android-new-task-document-launch", "documentLaunchMode and New Task Patterns",
     "Into existing document, always, never: multi-document apps, Chrome-like tabs, and recent tasks entries.",
     ["Android", "Activities", "Multi-Window"], "documentLaunchMode Android, new document launch, multi document Android app"),
    ("android-process-death-state-restoration", "Process Death State Restoration",
     "Survive process death: SavedStateHandle, rememberSaveable, persistent cache, and idempotent reload on cold start.",
     ["Android", "State", "Process Death"], "process death Android, SavedStateHandle process death, state restoration mobile"),
    ("android-saved-state-registry-custom", "Custom SavedStateRegistry Owners",
     "Register custom SavedStateProvider: non-Activity owners, Compose rememberSaveable bridges, and test fakes.",
     ["Android", "State", "Architecture"], "SavedStateRegistry custom, SavedStateProvider Android, state registry Compose"),
    ("android-viewmodel-factory-hilt-assist", "ViewModel Factory with Hilt Assisted Inject",
     "AssistedInject ViewModels: runtime parameters with @HiltViewModel, SavedStateHandle, and navigation args.",
     ["Android", "Hilt", "ViewModel"], "Hilt assisted inject ViewModel, AssistedInject Android, ViewModel factory Hilt"),
    ("android-viewmodel-savedstate-combined", "ViewModel Plus SavedStateHandle Combined",
     "Combine ViewModel business state with SavedStateHandle UI state: scroll positions, form drafts, and tab selection.",
     ["Android", "ViewModel", "State"], "SavedStateHandle ViewModel, ViewModel UI state, form draft SavedStateHandle"),
    ("android-lifecycle-observer-patterns", "Lifecycle Observer Patterns",
     "DefaultLifecycleObserver vs LifecycleEventObserver: start/stop camera, pause polling, and leak-free registration.",
     ["Android", "Lifecycle", "Architecture"], "LifecycleObserver Android, DefaultLifecycleObserver, lifecycle aware polling"),
    ("android-default-lifecycle-owner-compose", "LocalLifecycleOwner in Compose",
     "Lifecycle effects in Compose: DisposableEffect, LifecycleResumeEffect, and collecting flows with lifecycle awareness.",
     ["Android", "Jetpack Compose", "Lifecycle"], "LocalLifecycleOwner Compose, lifecycle Compose, LifecycleResumeEffect"),
    ("android-compose-lifecycle-effects", "Compose Lifecycle Effects Compared",
     "LaunchedEffect vs DisposableEffect vs SideEffect: when each runs, cleanup guarantees, and key selection.",
     ["Android", "Jetpack Compose", "Side Effects"], "Compose lifecycle effects, LaunchedEffect vs DisposableEffect, SideEffect Compose"),
    ("android-disposableeffect-cleanup", "DisposableEffect Cleanup Patterns",
     "Register/unregister listeners in DisposableEffect: BroadcastReceiver, SensorManager, and NavController observers.",
     ["Android", "Jetpack Compose", "Side Effects"], "DisposableEffect cleanup, Compose listener registration, DisposableEffect onDispose"),
    ("android-sideeffect-vs-launchedeffect", "SideEffect vs LaunchedEffect Decision Guide",
     "SideEffect for publish snapshot state to non-Compose APIs; LaunchedEffect for suspend work — avoid mixing concerns.",
     ["Android", "Jetpack Compose", "Side Effects"], "SideEffect vs LaunchedEffect, Compose side effects guide, publish state SideEffect"),
    ("android-remember-coroutine-scope-pitfalls", "rememberCoroutineScope Pitfalls",
     "UI-triggered coroutines: scope cancellation on leave, structured concurrency, and when to use viewModelScope instead.",
     ["Android", "Jetpack Compose", "Coroutines"], "rememberCoroutineScope pitfalls, Compose coroutine scope, UI coroutine launch"),
    ("android-compose-state-hoisting-patterns", "State Hoisting Patterns in Compose",
     "Stateful vs stateless composables: hoisting, unidirectional data flow, and event callbacks up the tree.",
     ["Android", "Jetpack Compose", "State"], "state hoisting Compose, stateless composable, Compose UDF patterns"),
    ("android-compose-slot-api-design", "Slot API Design in Compose",
     "Design flexible Compose APIs with slot parameters: header/content/footer slots without prop drilling explosion.",
     ["Android", "Jetpack Compose", "API Design"], "slot API Compose, composable slot pattern, flexible Compose API"),
    ("android-compose-polymorphic-composables", "Polymorphic Composables with Generics",
     "Generic list items, sealed UI models, and type-safe composable dispatch without runtime class checks everywhere.",
     ["Android", "Jetpack Compose", "Kotlin"], "polymorphic composables, generic Compose list, sealed class UI Compose"),
    ("android-compose-generic-list-items", "Generic List Items in Compose",
     "Reusable LazyColumn item composables: keyed items, content types, and item-specific padding without recomposition storms.",
     ["Android", "Jetpack Compose", "Lists"], "generic list Compose, LazyColumn reusable item, contentType LazyColumn"),
    ("android-compose-keyboard-actions-ime", "Keyboard Actions and IME Navigation",
     "KeyboardActions, ImeAction.Next/Done, focus traversal between fields, and hiding keyboard on submit.",
     ["Android", "Jetpack Compose", "IME"], "KeyboardActions Compose, ImeAction Next Done, focus traversal Compose form"),
    ("android-compose-focus-order-custom", "Custom Focus Order in Compose",
     "focusProperties, focusRequester chain, and TV/D-pad focus traversal for form accessibility compliance.",
     ["Android", "Jetpack Compose", "Accessibility"], "focus order Compose, focusProperties traversal, D-pad focus Compose"),
    ("android-compose-accessibility-custom-actions", "Custom Accessibility Actions in Compose",
     "semantics { customActions } for swipe actions, custom controls, and TalkBack discoverability beyond click.",
     ["Android", "Jetpack Compose", "Accessibility"], "custom accessibility actions Compose, semantics customActions, TalkBack Compose"),
    ("android-compose-live-region-announcements", "Live Region Announcements in Compose",
     "liveRegion politeness for dynamic content: form errors, chat messages, and loading completion announcements.",
     ["Android", "Jetpack Compose", "Accessibility"], "liveRegion Compose, accessibility announcements, TalkBack live region"),
    ("android-compose-large-font-scaling", "Large Font Scaling in Compose",
     "Support 200% font scale: flexible layouts, max lines, vertical scroll, and avoiding text clipping in toolbars.",
     ["Android", "Jetpack Compose", "Accessibility"], "font scaling Compose, large text accessibility, 200 percent font scale Android"),
    ("android-compose-locale-layout-mirror", "Locale Layout Mirroring in Compose",
     "RTL layouts: LayoutDirection, start/end modifiers, and testing Arabic/Hebrew mirroring without hard-coded left/right.",
     ["Android", "Jetpack Compose", "RTL"], "RTL Compose layout, LayoutDirection Rtl, locale mirroring Android"),
    ("android-compose-bidi-text-handling", "BiDi Text Handling in Compose",
     "Mixed LTR/RTL text: Unicode bidi, TextAlign.Start, and email/URL rendering in RTL locales.",
     ["Android", "Jetpack Compose", "Localization"], "BiDi text Compose, mixed direction text Android, RTL text rendering"),
    ("android-compose-animation-spec-tuning", "Animation Spec Tuning in Compose",
     "tween, spring, keyframes: damping/stiffness selection, interruptible animations, and reduced motion respect.",
     ["Android", "Jetpack Compose", "Animation"], "animation spec Compose, spring animation tuning, keyframes Compose animation"),
    ("android-compose-infinite-transition", "InfiniteTransition for Loading Indicators",
     "InfiniteTransition vs rememberInfiniteTransition: pulse, rotation, shimmer — and pausing when not visible.",
     ["Android", "Jetpack Compose", "Animation"], "InfiniteTransition Compose, loading animation infinite, shimmer Compose"),
    ("android-compose-animate-as-state", "animate*AsState for Smooth UI Transitions",
     "animateColorAsState, animateDpAsState: interruptible state transitions and avoiding animation churn on rapid updates.",
     ["Android", "Jetpack Compose", "Animation"], "animateAsState Compose, animateColorAsState, smooth UI transition Compose"),
    ("android-compose-transition-spec-compose", "Transition Spec in Compose Animation",
     "UpdateTransition with ChildTransition: shared element prep, tab indicator slide, and enter/exit together.",
     ["Android", "Jetpack Compose", "Animation"], "Transition Compose animation, UpdateTransition, enter exit transition Compose"),
    ("android-compose-motion-scheme-material3", "Material 3 Motion Scheme in Compose",
     "MaterialMotion: shared axis, fade through, container transform — matching M3 motion tokens in Compose.",
     ["Android", "Jetpack Compose", "Material 3"], "Material motion Compose, M3 motion scheme, container transform Compose"),
    ("android-compose-material-motion-patterns", "Material Motion Patterns in Compose",
     "Navigation transitions with AnimatedContent and Material easing: hierarchy, elevation, and z-order during motion.",
     ["Android", "Jetpack Compose", "UX"], "Material motion patterns Compose, navigation animation Material, AnimatedContent navigation"),
    ("android-compose-bottom-app-bar-fab", "Bottom App Bar with FAB Cutout",
     "BottomAppBar with cutout FAB: scroll behavior, snackbar anchor, and Material 3 bottom bar migration.",
     ["Android", "Jetpack Compose", "Material 3"], "BottomAppBar Compose, FAB cutout Compose, bottom bar scroll behavior"),
    ("android-compose-navigation-rail-adaptive", "Navigation Rail Adaptive Layouts",
     "NavigationRail with list-detail scaffold: WindowSizeClass breakpoints, canonical layouts, and foldable support.",
     ["Android", "Jetpack Compose", "Adaptive"], "NavigationRail Compose, adaptive layout Compose, list detail tablet Compose"),
    ("android-compose-list-detail-pane-scaffold", "List-Detail Pane Scaffold in Compose",
     "ListDetailPaneScaffold: two-pane on tablet, single pane on phone, and state restoration across form factors.",
     ["Android", "Jetpack Compose", "Adaptive"], "ListDetailPaneScaffold Compose, two pane layout Android, adaptive list detail"),
    ("android-compose-supporting-pane-layout", "Supporting Pane Layout Patterns",
     "Three-pane layouts: list, detail, supplementary — tooling panel, filters, and collapsing supporting pane.",
     ["Android", "Jetpack Compose", "Tablet"], "supporting pane Compose, three pane layout Android, supplementary pane tablet"),
    ("android-compose-window-size-class", "WindowSizeClass in Compose",
     "CalculateWindowSizeClass: Compact/Medium/Expanded width and height, orientation, and responsive typography.",
     ["Android", "Jetpack Compose", "Adaptive"], "WindowSizeClass Compose, responsive Compose layout, compact medium expanded"),
    ("android-compose-material3-dynamic-schemes", "Material 3 Dynamic Color Schemes",
     "dynamicLightColorScheme/dynamicDarkColorScheme: wallpaper colors, brand override, and contrast enforcement.",
     ["Android", "Jetpack Compose", "Material 3"], "dynamic color Compose, Material 3 dynamic scheme, wallpaper colors Android"),
    ("android-compose-extended-fab-menu", "Extended FAB and Speed Dial Menu",
     "Animated FAB expansion, speed dial accessibility, and replacing deprecated speed dial with explicit menus.",
     ["Android", "Jetpack Compose", "Material 3"], "extended FAB Compose, speed dial menu Compose, FAB menu animation"),
    ("android-compose-search-bar-material3", "Material 3 Search Bar in Compose",
     "SearchBar with animated expand: DockedSearchBar, query state, and predictive back from search overlay.",
     ["Android", "Jetpack Compose", "Material 3"], "SearchBar Compose Material 3, DockedSearchBar, search overlay Compose"),
    ("android-compose-date-picker-dialog", "Date Picker Dialog in Compose",
     "DatePickerDialog state: date range limits, locale calendars, and form integration with validation errors.",
     ["Android", "Jetpack Compose", "Material 3"], "DatePickerDialog Compose, Material 3 date picker, date selection Compose"),
    ("android-compose-time-picker-material3", "Material 3 Time Picker in Compose",
     "TimePicker dial vs input mode, 24h locale, and TimePickerDialog with rememberTimePickerState.",
     ["Android", "Jetpack Compose", "Material 3"], "TimePicker Compose Material 3, time picker dialog Compose, dial time picker"),
    ("android-compose-range-slider-patterns", "Range Slider Patterns in Compose",
     "RangeSlider for filters: value labels, steps, haptic ticks, and syncing with ViewModel filter state.",
     ["Android", "Jetpack Compose", "Material 3"], "RangeSlider Compose, dual thumb slider Android, filter range slider"),
    ("android-compose-segmented-button-bar", "Segmented Button Bar in Compose",
     "Single-select SegmentedButtonRow: icon segments, accessibility selected state, and replacing legacy TabRow toggles.",
     ["Android", "Jetpack Compose", "Material 3"], "SegmentedButton Compose, segmented control Material 3, toggle segment bar"),
    ("android-compose-filter-chip-selection", "Filter Chip Selection Patterns",
     "FilterChip multi-select: suggestion chips, input chips with delete, and chip row horizontal scroll.",
     ["Android", "Jetpack Compose", "Material 3"], "FilterChip Compose, chip selection Android, input chip delete Compose"),
    ("android-compose-suggestion-chip-input", "Suggestion and Input Chips in Compose",
     "AssistChip, SuggestionChip, InputChip: search suggestions, tag entry, and keyboard submit handling.",
     ["Android", "Jetpack Compose", "Material 3"], "InputChip Compose, SuggestionChip, chip input field Compose"),
    ("android-compose-exposed-dropdown-menu", "Exposed Dropdown Menu in Compose",
     "ExposedDropdownMenuBox: read-only field trigger, menu width, and error state with keyboard dismissal.",
     ["Android", "Jetpack Compose", "Material 3"], "ExposedDropdownMenu Compose, dropdown menu box Compose, select field Compose"),
    ("android-compose-modal-bottom-sheet", "Modal Bottom Sheet in Compose",
     "ModalBottomSheet with sheet state: partial expand, confirm dismiss, and nested scroll connection for lists.",
     ["Android", "Jetpack Compose", "Material 3"], "ModalBottomSheet Compose, bottom sheet state Compose, partial expand sheet"),
    ("android-compose-bottom-sheet-drag-handle", "Bottom Sheet Drag Handle UX",
     "DragHandle semantics, swipe-to-dismiss thresholds, and TalkBack sheet role announcements.",
     ["Android", "Jetpack Compose", "UX"], "bottom sheet drag handle Compose, sheet dismiss gesture, ModalBottomSheet UX"),
    ("android-compose-navigation-drawer-modal", "Modal Navigation Drawer in Compose",
     "ModalNavigationDrawer gestures: edge swipe width, predictive back, and permanent vs modal drawer selection.",
     ["Android", "Jetpack Compose", "Navigation"], "ModalNavigationDrawer Compose, navigation drawer gesture, drawer predictive back"),
    ("android-compose-permanent-drawer-tablet", "Permanent Drawer for Tablet Layouts",
     "PermanentNavigationDrawer with compact rail fallback: adaptive drawer patterns for large screens.",
     ["Android", "Jetpack Compose", "Tablet"], "PermanentNavigationDrawer Compose, tablet drawer layout, navigation drawer tablet"),
    ("android-compose-top-app-bar-scroll", "Top App Bar Scroll Behavior",
     "TopAppBar scroll behaviors: enterAlways, exitUntilCollapsed, nested scroll connection with LazyColumn.",
     ["Android", "Jetpack Compose", "Material 3"], "TopAppBar scroll behavior Compose, collapsing toolbar Compose, enterAlways app bar"),
    ("android-compose-collapsing-toolbar-lazy", "Collapsing Toolbar with LazyColumn",
     "Large top app bar collapse: offset tracking, parallax header, and pinned tabs below collapsing region.",
     ["Android", "Jetpack Compose", "UI"], "collapsing toolbar Compose, large top app bar LazyColumn, parallax header Compose"),
    ("android-compose-nested-scroll-toolbar", "Nested Scroll Toolbar Coordination",
     "NestedScrollConnection for coordinated app bar and content scroll: fling transfer and snap positions.",
     ["Android", "Jetpack Compose", "Scrolling"], "nested scroll toolbar Compose, NestedScrollConnection app bar, fling coordination Compose"),
    ("android-compose-lazy-grid-staggered", "Staggered Grid in Compose",
     "LazyVerticalStaggeredGrid: Pinterest layouts, variable height items, and prefetch tuning for image grids.",
     ["Android", "Jetpack Compose", "Lists"], "LazyVerticalStaggeredGrid Compose, staggered grid Android, masonry layout Compose"),
    ("android-compose-lazy-column-prefetch", "LazyColumn Prefetch Tuning",
     "LazyListPrefetchStrategy, beyondBoundsItemCount, and measuring prefetch impact with Macrobenchmark.",
     ["Android", "Jetpack Compose", "Performance"], "LazyColumn prefetch Compose, list prefetch strategy, beyondBoundsItemCount"),
    ("android-compose-lazy-list-item-animation", "Lazy List Item Animation",
     "Modifier.animateItem(): insert/remove/move animations, item placement spec, and avoiding jank on fast scroll.",
     ["Android", "Jetpack Compose", "Animation"], "animateItem LazyColumn, list item animation Compose, item placement animation"),
    ("android-compose-paging-placeholder-shimmer", "Paging Placeholder Shimmer in Compose",
     "Shimmer placeholders for Paging LoadState.Loading: item count estimation and transition to real content.",
     ["Android", "Jetpack Compose", "Paging"], "paging shimmer Compose, LazyPagingItems placeholder, loading skeleton paging"),
    ("android-compose-swipeable-list-actions", "Swipeable List Actions in Compose",
     "SwipeToDismissBox, anchoredDraggable for mail/archive actions, and accessibility custom swipe actions.",
     ["Android", "Jetpack Compose", "UX"], "swipe to dismiss Compose, list swipe actions Android, SwipeToDismissBox"),
    ("android-compose-pullrefresh-custom-indicator", "Custom Pull Refresh Indicator",
     "PullToRefreshBox customization: indicator offset, nested scroll, and Material 3 pull refresh migration.",
     ["Android", "Jetpack Compose", "Material 3"], "pull refresh Compose custom, PullToRefreshBox indicator, pull to refresh Material 3"),
    ("android-compose-snackbar-host-state", "SnackbarHostState Patterns in Compose",
     "Show snackbar from ViewModel events: Scaffold host state, action handling, and queue vs replace policy.",
     ["Android", "Jetpack Compose", "UX"], "SnackbarHostState Compose, snackbar from ViewModel, Scaffold snackbar Compose"),
    ("android-compose-scaffold-slot-patterns", "Scaffold Slot Patterns in Compose",
     "Compose Scaffold slots: FAB positioning, snackbar host, innerPadding consumption, and edge-to-edge insets.",
     ["Android", "Jetpack Compose", "Layout"], "Scaffold slots Compose, innerPadding Scaffold, FAB snackbar scaffold pattern"),
    ("android-compose-dialog-alert-patterns", "Alert Dialog Patterns in Compose",
     "AlertDialog confirm/cancel: state hoisting, back dismiss, and destructive action color semantics.",
     ["Android", "Jetpack Compose", "Material 3"], "AlertDialog Compose, confirmation dialog pattern, destructive dialog Compose"),
    ("android-compose-fullscreen-dialog", "Full-Screen Dialog in Compose",
     "Dialog with fillMaxSize: immersive flows, predictive back, and replacing DialogFragment migration path.",
     ["Android", "Jetpack Compose", "Navigation"], "fullscreen dialog Compose, Dialog fillMaxSize, DialogFragment migration Compose"),
    ("android-compose-popup-dropdown-positioning", "Popup and Dropdown Positioning",
     "DropdownMenu popupPositionProvider: avoid clipping, RTL alignment, and keyboard overlap adjustment.",
     ["Android", "Jetpack Compose", "UI"], "DropdownMenu positioning Compose, popupPositionProvider, menu clipping Compose"),
    ("android-compose-tooltip-material3", "Tooltip Implementation in Material 3 Compose",
     "PlainTooltipBox, RichTooltip: long-press vs hover, accessibility descriptions, and TV focus tooltips.",
     ["Android", "Jetpack Compose", "Material 3"], "Tooltip Compose Material 3, PlainTooltipBox, rich tooltip Android"),
    ("android-compose-badge-indicator-patterns", "Badge Indicator Patterns in Compose",
     "BadgedBox with notification counts: max display 99+, accessibility unread count, and animated badge show/hide.",
     ["Android", "Jetpack Compose", "Material 3"], "BadgedBox Compose, notification badge Android, badge count accessibility"),
    ("android-compose-progress-indicators-linear", "Linear Progress Indicators in Compose",
     "LinearProgressIndicator determinate/indeterminate: download progress, multi-step forms, and accessibility progress.",
     ["Android", "Jetpack Compose", "Material 3"], "LinearProgressIndicator Compose, determinate progress Android, progress accessibility"),
    ("android-compose-circular-progress-custom", "Custom Circular Progress in Compose",
     "CircularProgressIndicator with track color, stroke cap, and Canvas-based ring progress for fitness apps.",
     ["Android", "Jetpack Compose", "UI"], "CircularProgressIndicator Compose, ring progress Canvas, custom progress indicator"),
    ("android-compose-skeleton-loading-shimmer", "Skeleton Loading Shimmer in Compose",
     "Shimmer effect with Modifier.graphicsLayer and infinite animation — respect reduced motion with static skeleton.",
     ["Android", "Jetpack Compose", "UX"], "shimmer skeleton Compose, loading placeholder shimmer, skeleton loading Android"),
    ("android-compose-image-coil-composable", "Coil AsyncImage in Compose",
     "Coil 3 AsyncImage: crossfade, placeholders, memory/disk cache keys, and size resolution for Recycler-free lists.",
     ["Android", "Jetpack Compose", "Images"], "Coil Compose AsyncImage, image loading Compose, Coil 3 Compose integration"),
    ("android-compose-async-image-caching", "Async Image Caching Strategy in Compose",
     "Size-aware requests, memory pressure callbacks, cache invalidation on auth change, and GIF/WebP decoding.",
     ["Android", "Jetpack Compose", "Performance"], "image cache Compose, Coil cache strategy, async image memory Android"),
    ("android-compose-svg-vector-image", "SVG and Vector Images in Compose",
     "VectorDrawable in Compose, Coil SVG decoder, and tinting icons with MaterialTheme color roles.",
     ["Android", "Jetpack Compose", "Graphics"], "SVG Compose Android, vector image Compose, VectorDrawable Compose"),
    ("android-compose-form-validation-state", "Form Validation State in Compose",
     "Field-level errors, form-wide submit gating, debounced validation, and accessibility error announcements.",
     ["Android", "Jetpack Compose", "Forms"], "form validation Compose, field error state Compose, accessible form errors Android"),
    ("android-compose-debounced-search-field", "Debounced Search Field in Compose",
     "Search with debounce: snapshotFlow, distinctUntilChanged, and cancel previous search jobs on query change.",
     ["Android", "Jetpack Compose", "Search"], "debounced search Compose, snapshotFlow debounce, search field Compose"),
    ("android-compose-navigation-compose-testing", "Navigation Compose Testing",
     "Test NavHost routes: createComposeRule, navController test harness, and asserting back stack state.",
     ["Android", "Testing", "Navigation"], "Navigation Compose testing, NavHost test, compose navigation test rule"),
    ("android-compose-ui-test-wait-idle", "Compose UI Test Wait For Idle",
     "waitForIdle, waitUntil, idling policies for animations, and eliminating Thread.sleep flakiness.",
     ["Android", "Testing", "Compose"], "Compose test waitForIdle, waitUntil Compose test, idle policy Compose UI test"),
    ("android-compose-test-rule-hilt", "Hilt Test Rule for Compose Tests",
     "HiltAndroidTest with createAndroidComposeRule: replace bindings, test ViewModels, and fake repositories.",
     ["Android", "Testing", "Hilt"], "Hilt Compose test, createAndroidComposeRule Hilt, Android instrumented test Hilt"),
    ("android-compose-semantics-merge-descendants", "Semantics Merge Descendants in Compose",
     "mergeDescendants for clickable rows: TalkBack grouping, toggle semantics, and testing merged trees.",
     ["Android", "Jetpack Compose", "Accessibility"], "mergeDescendants Compose, semantics merge TalkBack, clickable row accessibility"),
    ("android-compose-test-tag-practices", "Compose Test Tag Best Practices",
     "Modifier.testTag naming conventions, semantic vs test tags, and not breaking accessibility with test-only tags.",
     ["Android", "Testing", "Compose"], "testTag Compose, Compose test tag conventions, semantics testTag Android"),
    ("android-compose-collect-as-state-lifecycle", "collectAsStateWithLifecycle in Compose",
     "Replace collectAsState with lifecycle-aware collection: STARTED vs RESUMED, and stopping collectors in background.",
     ["Android", "Jetpack Compose", "Lifecycle"], "collectAsStateWithLifecycle, lifecycle aware Flow Compose, Flow collection lifecycle"),
    ("android-compose-flow-collect-with-lifecycle", "Flow Collection With Lifecycle in Compose",
     "repeatOnLifecycle in Compose: LaunchedEffect + lifecycleOwner, and avoiding duplicate collectors.",
     ["Android", "Jetpack Compose", "Coroutines"], "repeatOnLifecycle Compose, Flow collect lifecycle, LaunchedEffect lifecycle Flow"),
    ("android-compose-derived-state-performance", "derivedStateOf Performance in Compose",
     "Use derivedStateOf for expensive list filtering: skip recomposition when inputs unchanged, measurement pitfalls.",
     ["Android", "Jetpack Compose", "Performance"], "derivedStateOf Compose, recomposition optimization, derived state performance"),
    ("android-compose-stability-configuration-file", "Compose Stability Configuration File",
     "compose_compiler_config.conf: mark classes stable, diagnose stability issues, and strong skipping mode tuning.",
     ["Android", "Jetpack Compose", "Performance"], "Compose stability configuration, compose compiler config, strong skipping Compose"),
    ("android-compose-performance-baseline-profile", "Baseline Profiles for Compose Apps",
     "Generate baseline profiles for Compose startup: Macrobenchmark, profileinstaller, and dex layout optimization.",
     ["Android", "Jetpack Compose", "Performance"], "baseline profile Compose, Compose startup optimization, profileinstaller Compose"),
    ("android-compose-jankstats-integration", "JankStats Integration with Compose",
     "FrameMetricsReporter with Compose: detect janky frames, tag UI surfaces, and correlate with recomposition counts.",
     ["Android", "Jetpack Compose", "Performance"], "JankStats Compose, frame jank Compose, Compose performance monitoring"),
    ("android-compose-interop-androidview-binding", "AndroidView Interop with View Binding",
     "Embed legacy XML via AndroidView: update block, dispose, MutableState synchronization, and focus handoff.",
     ["Android", "Jetpack Compose", "Interop"], "AndroidView Compose, View Binding interop, legacy view Compose integration"),
    ("android-compose-mapview-interop", "MapView Interop in Compose",
     "Google Maps Compose vs AndroidView MapView: lifecycle, cluster rendering, and gesture nested scroll conflicts.",
     ["Android", "Jetpack Compose", "Maps"], "MapView Compose interop, Google Maps Compose, map nested scroll Android"),
    ("android-compose-videoview-exoplayer", "ExoPlayer Surface in Compose",
     "AndroidView PlayerView with ExoPlayer: lifecycle pause, PiP handoff, and Compose state for playback controls.",
     ["Android", "Jetpack Compose", "Media"], "ExoPlayer Compose, PlayerView AndroidView, video playback Compose"),
    ("android-compose-back-handler-predictive", "Predictive Back Handler in Compose",
     "PredictiveBackHandler: animated back preview, commit/ cancel, and integration with NavController pop.",
     ["Android", "Jetpack Compose", "Navigation"], "PredictiveBackHandler Compose, predictive back gesture Compose, back animation Android"),
    ("android-compose-activity-result-contracts", "Activity Result Contracts in Compose",
     "rememberLauncherForActivityResult: photo picker, permissions, and document contracts with state restoration.",
     ["Android", "Jetpack Compose", "Activity Result"], "rememberLauncherForActivityResult Compose, activity result Compose, photo picker Compose"),
    ("android-compose-permission-launcher-compose", "Permission Launcher Patterns in Compose",
     "Request permissions with rationale UI: shouldShowRequestPermissionRationale and settings deep link fallback.",
     ["Android", "Jetpack Compose", "Permissions"], "permission launcher Compose, request permission Compose, rationale permission Android"),
    ("android-compose-biometric-auth-compose", "Biometric Auth UI in Compose",
     "BiometricPrompt from Compose: CryptoObject unlock flow, error mapping to UI, and fallback PIN navigation.",
     ["Android", "Jetpack Compose", "Security"], "biometric auth Compose, BiometricPrompt Compose UI, fingerprint login Compose"),
    ("android-compose-wear-rotary-input-scroll", "Wear OS Rotary Input Scroll in Compose",
     "Rotary scrollable modifiers: focusGroup, rotaryScrollable, and crown input on Wear Compose.",
     ["Android", "Wear OS", "Compose"], "Wear rotary input Compose, rotaryScrollable Wear, crown scroll Wear OS"),
    ("android-compose-wear-complication-data", "Wear Complication Data in Compose",
     "ComplicationDataSourceService with Compose previews: timeline entries, short text complications, and updates.",
     ["Android", "Wear OS", "Compose"], "Wear complication Compose, ComplicationDataSourceService, watch face complication data"),
    ("android-compose-wear-tiles-timeline", "Wear Tiles Timeline in Compose",
     "Tiles with ProtoLayout: timeline entries, refresh intervals, and resource limits on Wear OS 5.",
     ["Android", "Wear OS", "Tiles"], "Wear Tiles timeline, ProtoLayout tiles, Wear OS tile refresh"),
    ("android-compose-wear-standalone-app-architecture", "Wear Standalone App Architecture",
     "Standalone vs companion Wear apps: data sync, OAuth on watch, and network on LTE Wear devices.",
     ["Android", "Wear OS", "Architecture"], "Wear standalone app, companion app architecture, LTE Wear app design"),
    ("android-compose-wear-data-layer-sync", "Wear Data Layer Sync Patterns",
     "Wearable Data Layer API: MessageClient, DataClient, capability detection, and conflict resolution with phone.",
     ["Android", "Wear OS", "Sync"], "Wear Data Layer API, WearableListenerService, phone watch sync Android"),
    ("android-compose-wear-health-services", "Health Services on Wear Compose",
     "ExerciseClient, PassiveMonitoringClient: permissions, battery impact, and foreground service on Wear.",
     ["Android", "Wear OS", "Health"], "Health Services Wear OS, ExerciseClient, passive monitoring watch Android"),
    ("android-compose-wear-always-on-display", "Always-On Display on Wear Compose",
     "Ambient mode lifecycle: burn-in safe layouts, low-bit ambient, and transition between interactive and ambient.",
     ["Android", "Wear OS", "Display"], "always on display Wear, ambient mode Compose, burn in protection Wear OS"),
    ("android-room-fts-search-ranking", "Room FTS Search Ranking",
     "Rank FTS matches with bm25 weights in Room: MATCH queries, snippet extraction, and pagination of search results.",
     ["Android", "Room", "Search"], "Room FTS ranking, FTS4 MATCH Room, full text search ranking Android"),
    ("android-room-paging-source-local", "Room PagingSource for Local Database",
     "PagingSource over Room queries: invalidation, LIMIT/OFFSET vs key paging, and search result paging.",
     ["Android", "Room", "Paging"], "Room PagingSource, local database paging, Room LIMIT OFFSET paging"),
    ("android-room-auto-migrations", "Room Auto Migrations",
     "AutoMigrationSpec for additive schema changes: export schema, verify migrations, and when manual SQL still wins.",
     ["Android", "Room", "Database"], "Room auto migration, AutoMigrationSpec, schema export Room Android"),
    ("android-room-relations-multimap", "Room Relations and Multimap Queries",
     "@Relation with @Junction for many-to-many: multimap results, ordering, and avoiding N+1 query explosions.",
     ["Android", "Room", "Database"], "Room Relation Junction, multimap Room query, many to many Room"),
    ("android-room-flow-dispatchers", "Room Flow and Dispatcher Choice",
     "Observe queries as Flow: invalidation tracker, withTransaction dispatcher rules, and main-safe collection.",
     ["Android", "Room", "Coroutines"], "Room Flow observe, Room coroutine dispatcher, invalidation tracker Flow"),
    ("android-workmanager-expedited-work", "WorkManager Expedited Work",
     "Expedited jobs for user-initiated tasks: quota limits, fallback to regular work, and OutOfQuotaPolicy.",
     ["Android", "WorkManager", "Background"], "WorkManager expedited work, expedited quota Android, OutOfQuotaPolicy"),
    ("android-workmanager-coroutine-worker", "CoroutineWorker Best Practices",
     "CoroutineWorker vs Worker: suspend doWork, foreground info, progress reporting, and cancellation handling.",
     ["Android", "WorkManager", "Coroutines"], "CoroutineWorker Android, suspend doWork WorkManager, worker progress reporting"),
    ("android-workmanager-hilt-integration", "WorkManager Hilt Integration",
     "HiltWorkerFactory, @AssistedInject workers, and injecting repositories into background jobs safely.",
     ["Android", "WorkManager", "Hilt"], "WorkManager Hilt, HiltWorkerFactory, assisted inject worker Android"),
    ("android-workmanager-test-driver", "Testing WorkManager with TestDriver",
     "WorkManagerTestInitHelper: TestDriver advance time, run synchronously in instrumented tests, and idempotency checks.",
     ["Android", "WorkManager", "Testing"], "WorkManager TestDriver, WorkManager testing Android, TestInitHelper WorkManager"),
    ("android-play-billing-acknowledge-purchases", "Acknowledge and Consume Purchases",
     "BillingClient acknowledgePurchase, consumeAsync for consumables, and pending transaction handling on resume.",
     ["Android", "Play Billing", "Monetization"], "acknowledge purchase Android, consume purchase billing, pending purchases Play Billing"),
    ("android-play-billing-offer-tags", "Play Billing Offer Tags and Pricing",
     "Subscription offer tags, pricing phases, upgrade/downgrade proration, and regional price experiments.",
     ["Android", "Play Billing", "Monetization"], "Play Billing offer tags, subscription pricing phases, proration Android billing"),
    ("android-play-integrity-standard-request", "Play Integrity Standard Request Flow",
     "Standard integrity token requests: cloud project number, retry on transient errors, and server decoding.",
     ["Android", "Play Integrity", "Security"], "Play Integrity standard request, integrity token Android, Play Integrity API flow"),
    ("android-espresso-compose-interop", "Espresso and Compose Test Interop",
     "composeTestRule + Espresso on same screen: idling synchronizing, hybrid View/Compose hierarchies in tests.",
     ["Android", "Testing", "Espresso"], "Espresso Compose interop test, hybrid UI test Android, Compose Espresso same screen"),
    ("android-robolectric-compose-tests", "Robolectric Tests for Compose",
     "Robolectric + Compose UI tests on JVM: shadows, SDK config, and faster feedback for UI logic.",
     ["Android", "Testing", "Robolectric"], "Robolectric Compose test, JVM Compose UI test, Robolectric Android Compose"),
    ("android-macrobenchmark-startup-tracing", "Macrobenchmark Startup Tracing",
     "Measure cold/warm/hot startup: StartupTimingMetric, BaselineProfileRule, and comparing releases in CI.",
     ["Android", "Performance", "Benchmark"], "Macrobenchmark startup, StartupTimingMetric Android, cold start benchmark"),
    ("android-microbenchmark-inline-methods", "Microbenchmark for Inline Methods",
     "Benchmark Kotlin code on device: MicrobenchmarkRule, dead code elimination traps, and statistical rigor.",
     ["Android", "Performance", "Benchmark"], "Microbenchmark Android, MicrobenchmarkRule Kotlin, Android method benchmarking"),
    ("android-leakcanary-compose-watchers", "LeakCanary Watchers for Compose",
     "Detect Compose-related leaks: rememberCoroutineScope, NavController, and custom RetainedObjectWatcher hooks.",
     ["Android", "Performance", "LeakCanary"], "LeakCanary Compose, memory leak Compose Android, LeakCanary watchers"),
    ("android-strictmode-compose-disk-reads", "StrictMode Disk Reads with Compose",
     "Catch accidental blocking I/O during composition: StrictMode policy, remember blocking calls anti-pattern.",
     ["Android", "Performance", "StrictMode"], "StrictMode Compose, disk read main thread Compose, StrictMode debug Android"),
    ("kotlin-coroutines-android-main-immediate", "Main.immediate on Android",
     "Dispatchers.Main.immediate vs Main: reentrant UI updates, test dispatchers, and avoiding double frame delay.",
     ["Kotlin", "Coroutines", "Android"], "Main.immediate Android, Dispatchers Main immediate, reentrant coroutine UI"),
    ("kotlin-flow-statein-sharing-started", "StateIn SharingStarted Policies on Android",
     "WhileSubscribed(5000) vs Eagerly: screen lifecycle, config change, and multi-collector ViewModels.",
     ["Kotlin", "Flow", "Android"], "SharingStarted WhileSubscribed, stateIn ViewModel Android, Flow stateIn policy"),
    ("kotlin-coroutines-viewmodel-scope-patterns", "viewModelScope Coroutine Patterns",
     "Structured concurrency in ViewModels: supervisorJob, async parallel loads, and cancellation on navigate away.",
     ["Kotlin", "Coroutines", "ViewModel"], "viewModelScope patterns, ViewModel coroutine Android, structured concurrency ViewModel"),
    ("kotlin-suspend-callback-adapter", "Suspend Callback Adapter for Legacy APIs",
     "Wrap Callback/Future APIs with suspendCoroutine and cancellable continuations — Retrofit, Firebase, GMS.",
     ["Kotlin", "Coroutines", "Interop"], "suspendCoroutine Android, callback to suspend Kotlin, cancellable continuation legacy API"),
    ("kotlin-channel-event-bus-replacement", "Replace Event Bus with Channel Flow",
     "BroadcastChannel is deprecated — Channel, SharedFlow events, and avoiding memory leaks from sticky events.",
     ["Kotlin", "Coroutines", "Architecture"], "Channel event bus Kotlin, SharedFlow events Android, BroadcastChannel replacement"),
    ("kotlin-flow-retry-backoff-mobile", "Flow Retry with Backoff on Mobile",
     "retryWhen with exponential backoff and jitter on flaky mobile networks — cap attempts and respect lifecycle.",
     ["Kotlin", "Flow", "Networking"], "Flow retryWhen backoff, exponential backoff Kotlin Flow, mobile network retry"),
    ("kotlin-result-retrofit-wrapper", "Result Type Wrapper for Retrofit",
     "Sealed network results: success, HTTP error, network error — map to UI without exceptions as control flow.",
     ["Kotlin", "Retrofit", "Error Handling"], "Result Retrofit Kotlin, network result sealed class, Retrofit error handling Kotlin"),
    ("kotlin-inline-reified-navigation", "Inline Reified Navigation Arguments",
     "Type-safe navigation with inline reified serializers — JSON nav args, custom NavType, and R8 keep rules.",
     ["Kotlin", "Navigation", "Android"], "reified navigation args, type safe navigation Kotlin, NavType custom serializer"),
    ("kotlin-duration-api-android-ui", "Kotlin Duration API in Android UI",
     "kotlin.time.Duration for timeouts, debounce, and animation specs — avoid raw Long milliseconds confusion.",
     ["Kotlin", "Android", "API"], "kotlin Duration Android, duration debounce Compose, time API Kotlin mobile"),
    ("kotlin-uuid-random-android", "UUID and Secure Random on Android",
     "Generate client IDs with UUID.randomUUID vs SecureRandom — collision risk, persistence, and analytics device IDs.",
     ["Kotlin", "Security", "Android"], "UUID Android Kotlin, SecureRandom mobile, client ID generation Android"),
    ("kotlin-collections-android-performance", "Kotlin Collections Performance on Android",
     "PersistentList vs List on hot paths: allocation pressure, lazy sequences, and when immutable copies hurt GC.",
     ["Kotlin", "Performance", "Android"], "Kotlin collections Android performance, persistent list mobile, allocation GC Android"),
]

assert len(TOPICS) >= 250, f"Need 250 topics, got {len(TOPICS)}"
