TOPICS = {
  "variable-fonts-performance-ux": (
    "We switched six static WOFF2 files to one variable Inter file and cut font payload from 420 KB to 180 KB after subsetting—LCP improved 180 ms on mobile.",
    "variable fonts performance ux",
    "when variable fonts performance ux affects users on critical paths",
    "Rolling out variable fonts performance ux without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with variable fonts performance ux?', 'Teams ship without field measurement—variable fonts performance ux failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize variable fonts performance ux?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate variable fonts performance ux changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "vector-databases-in-production": (
    "The team evaluated Pinecone and Qdrant, then asked: can we use Postgres? Eight hundred thousand chunks with permission joins made pgvector the right tool—not a compromise.",
    "vector databases in production",
    "when vector databases in production affects users on critical paths",
    "Rolling out vector databases in production without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with vector databases in production?', 'Teams ship without field measurement—vector databases in production failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize vector databases in production?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate vector databases in production changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "vector-db-filtering-pre-post": (
    "Our RAG pipeline returned wrong-tenant documentation for three weeks because post-filtering discarded global neighbors that failed tenant_id checks.",
    "vector db filtering pre post",
    "when vector db filtering pre post affects users on critical paths",
    "Rolling out vector db filtering pre post without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with vector db filtering pre post?', 'Teams ship without field measurement—vector db filtering pre post failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize vector db filtering pre post?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate vector db filtering pre post changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "vector-db-pgvector-postgres": (
    "Adding pgvector took an afternoon; operating a second vector database would have taken a quarter.",
    "vector db pgvector postgres",
    "when vector db pgvector postgres affects users on critical paths",
    "Rolling out vector db pgvector postgres without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with vector db pgvector postgres?', 'Teams ship without field measurement—vector db pgvector postgres failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize vector db pgvector postgres?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate vector db pgvector postgres changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "vector-db-sharding-scaling": (
    "At thirty million vectors our Qdrant node started swapping—sharding was survival, not optimization.",
    "vector db sharding scaling",
    "when vector db sharding scaling affects users on critical paths",
    "Rolling out vector db sharding scaling without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with vector db sharding scaling?', 'Teams ship without field measurement—vector db sharding scaling failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize vector db sharding scaling?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate vector db sharding scaling changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "vector-search-hnsw-tuning": (
    "We celebrated 12 ms p50 queries until recall@10 against brute force came back at 71%.",
    "vector search hnsw tuning",
    "when vector search hnsw tuning affects users on critical paths",
    "Rolling out vector search hnsw tuning without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with vector search hnsw tuning?', 'Teams ship without field measurement—vector search hnsw tuning failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize vector search hnsw tuning?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate vector search hnsw tuning changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "vector-search-ivf-pq-index": (
    "HNSW ate 38 GB RAM; IVF-PQ cut memory to 6 GB at 93% recall—good enough for recommendations, not for legal RAG.",
    "vector search ivf pq index",
    "when vector search ivf pq index affects users on critical paths",
    "Rolling out vector search ivf pq index without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with vector search ivf pq index?', 'Teams ship without field measurement—vector search ivf pq index failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize vector search ivf pq index?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate vector search ivf pq index changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "vex-vulnerability-triage-sbom": (
    "Our scanner reported 847 critical CVEs on one image; VEX assertions dropped actionable issues to 23.",
    "vex vulnerability triage sbom",
    "when vex vulnerability triage sbom affects users on critical paths",
    "Rolling out vex vulnerability triage sbom without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with vex vulnerability triage sbom?', 'Teams ship without field measurement—vex vulnerability triage sbom failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize vex vulnerability triage sbom?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate vex vulnerability triage sbom changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "view-transitions-api": (
    "We replaced a 14 KB transition library with forty lines of CSS and startViewTransition.",
    "view transitions api",
    "when view transitions api affects users on critical paths",
    "Rolling out view transitions api without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with view transitions api?', 'Teams ship without field measurement—view transitions api failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize view transitions api?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate view transitions api changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "voice-agents-stt-tts-pipelines": (
    "End-to-end voice latency was 2.4 seconds until we streamed STT, LLM tokens, and TTS audio chunks.",
    "voice agents stt tts pipelines",
    "when voice agents stt tts pipelines affects users on critical paths",
    "Rolling out voice agents stt tts pipelines without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with voice agents stt tts pipelines?', 'Teams ship without field measurement—voice agents stt tts pipelines failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize voice agents stt tts pipelines?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate voice agents stt tts pipelines changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "vue-3-composition-api-patterns": (
    "Three mixins had colliding data() keys until composables made dependencies explicit.",
    "vue 3 composition api patterns",
    "when vue 3 composition api patterns affects users on critical paths",
    "Rolling out vue 3 composition api patterns without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with vue 3 composition api patterns?', 'Teams ship without field measurement—vue 3 composition api patterns failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize vue 3 composition api patterns?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate vue 3 composition api patterns changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "wasm-workloads-kubernetes": (
    "Two thousand container cold starts per minute became WASM Spin pods at 35 ms median cold start.",
    "wasm workloads kubernetes",
    "when wasm workloads kubernetes affects users on critical paths",
    "Rolling out wasm workloads kubernetes without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with wasm workloads kubernetes?', 'Teams ship without field measurement—wasm workloads kubernetes failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize wasm workloads kubernetes?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate wasm workloads kubernetes changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "wcag-22-new-criteria-implementation": (
    "Forty-seven new violations appeared the week WCAG 2.2 became the procurement standard—mostly sticky headers and 20px icon buttons.",
    "wcag 22 new criteria implementation",
    "when wcag 22 new criteria implementation affects users on critical paths",
    "Rolling out wcag 22 new criteria implementation without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with wcag 22 new criteria implementation?', 'Teams ship without field measurement—wcag 22 new criteria implementation failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize wcag 22 new criteria implementation?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate wcag 22 new criteria implementation changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-accessibility-aria-patterns": (
    "Three hundred forty ARIA attributes made NVDA harder to use until we stripped redundant roles and fixed three composite widgets.",
    "web accessibility aria patterns",
    "when web accessibility aria patterns affects users on critical paths",
    "Rolling out web accessibility aria patterns without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web accessibility aria patterns?', 'Teams ship without field measurement—web accessibility aria patterns failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web accessibility aria patterns?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web accessibility aria patterns changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-accessibility-keyboard-navigation": (
    "Tab order jumped through four hundred grid cells before the save button until we fixed roving tabindex on the data table.",
    "web accessibility keyboard navigation",
    "when web accessibility keyboard navigation affects users on critical paths",
    "Rolling out web accessibility keyboard navigation without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web accessibility keyboard navigation?', 'Teams ship without field measurement—web accessibility keyboard navigation failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web accessibility keyboard navigation?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web accessibility keyboard navigation changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-accessibility-screen-reader-testing": (
    "Axe passed checkout; NVDA users got lost in the autocomplete until we tested with real screen readers.",
    "web accessibility screen reader testing",
    "when web accessibility screen reader testing affects users on critical paths",
    "Rolling out web accessibility screen reader testing without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web accessibility screen reader testing?', 'Teams ship without field measurement—web accessibility screen reader testing failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web accessibility screen reader testing?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web accessibility screen reader testing changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-color-functions-oklch": (
    "HSL gray steps looked identical on one monitor and miles apart on another until we migrated neutrals to OKLCH.",
    "web color functions oklch",
    "when web color functions oklch affects users on critical paths",
    "Rolling out web color functions oklch without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web color functions oklch?', 'Teams ship without field measurement—web color functions oklch failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web color functions oklch?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web color functions oklch changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-components-2026": (
    "One ds-button ships in React, Vue, and Angular apps because web components beat three framework copies.",
    "web components 2026",
    "when web components 2026 affects users on critical paths",
    "Rolling out web components 2026 without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web components 2026?', 'Teams ship without field measurement—web components 2026 failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web components 2026?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web components 2026 changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-components-form-association": (
    "Hidden inputs syncing custom rating widgets broke on form reset until formAssociated custom elements shipped.",
    "web components form association",
    "when web components form association affects users on critical paths",
    "Rolling out web components form association without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web components form association?', 'Teams ship without field measurement—web components form association failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web components form association?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web components form association changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-components-shadow-dom": (
    "Global button { border-radius: 0 } stopped breaking design system buttons inside shadow roots.",
    "web components shadow dom",
    "when web components shadow dom affects users on critical paths",
    "Rolling out web components shadow dom without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web components shadow dom?', 'Teams ship without field measurement—web components shadow dom failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web components shadow dom?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web components shadow dom changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-dialog-element-modal": (
    "We deleted four hundred lines of focus-trap modal JavaScript and used showModal() instead.",
    "web dialog element modal",
    "when web dialog element modal affects users on critical paths",
    "Rolling out web dialog element modal without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web dialog element modal?', 'Teams ship without field measurement—web dialog element modal failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web dialog element modal?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web dialog element modal changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-forms-native-validation": (
    "Removing Yup from signup improved conversion when native constraint validation showed errors immediately.",
    "web forms native validation",
    "when web forms native validation affects users on critical paths",
    "Rolling out web forms native validation without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web forms native validation?', 'Teams ship without field measurement—web forms native validation failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web forms native validation?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web forms native validation changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-htmx-server-driven-ui": (
    "One hundred eighty KB of React admin JS became htmx partial swaps on server-rendered tables.",
    "web htmx server driven ui",
    "when web htmx server driven ui affects users on critical paths",
    "Rolling out web htmx server driven ui without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web htmx server driven ui?', 'Teams ship without field measurement—web htmx server driven ui failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web htmx server driven ui?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web htmx server driven ui changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-islands-partial-hydration": (
    "Three hundred forty KB sitewide JS dropped to twenty-eight KB when only search and theme toggle hydrated.",
    "web islands partial hydration",
    "when web islands partial hydration affects users on critical paths",
    "Rolling out web islands partial hydration without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web islands partial hydration?', 'Teams ship without field measurement—web islands partial hydration failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web islands partial hydration?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web islands partial hydration changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-404-page-product-sites": (
    "We shipped web performance 404 page product sites and discovered the gap between documentation and production the hard way.",
    "web performance 404 page product sites",
    "when web performance 404 page product sites affects users on critical paths",
    "Rolling out web performance 404 page product sites without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance 404 page product sites?', 'Teams ship without field measurement—web performance 404 page product sites failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance 404 page product sites?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance 404 page product sites changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-attribution-reporting-api": (
    "We shipped web performance attribution reporting api and discovered the gap between documentation and production the hard way.",
    "web performance attribution reporting api",
    "when web performance attribution reporting api affects users on critical paths",
    "Rolling out web performance attribution reporting api without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance attribution reporting api?', 'Teams ship without field measurement—web performance attribution reporting api failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance attribution reporting api?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance attribution reporting api changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-back-forward-cache": (
    "Removing beforeunload handlers moved bfcache success from twelve to seventy-eight percent on Chrome Android.",
    "web performance back forward cache",
    "when web performance back forward cache affects users on critical paths",
    "Rolling out web performance back forward cache without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance back forward cache?', 'Teams ship without field measurement—web performance back forward cache failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance back forward cache?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance back forward cache changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-breadcrumb-navigation-seo": (
    "We shipped web performance breadcrumb navigation seo and discovered the gap between documentation and production the hard way.",
    "web performance breadcrumb navigation seo",
    "when web performance breadcrumb navigation seo affects users on critical paths",
    "Rolling out web performance breadcrumb navigation seo without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance breadcrumb navigation seo?', 'Teams ship without field measurement—web performance breadcrumb navigation seo failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance breadcrumb navigation seo?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance breadcrumb navigation seo changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-brotli-gzip-compression": (
    "We shipped web performance brotli gzip compression and discovered the gap between documentation and production the hard way.",
    "web performance brotli gzip compression",
    "when web performance brotli gzip compression affects users on critical paths",
    "Rolling out web performance brotli gzip compression without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance brotli gzip compression?', 'Teams ship without field measurement—web performance brotli gzip compression failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance brotli gzip compression?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance brotli gzip compression changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-bundle-splitting": (
    "Eight hundred ninety KB main bundle became two hundred ten KB after route-based dynamic imports.",
    "web performance bundle splitting",
    "when web performance bundle splitting affects users on critical paths",
    "Rolling out web performance bundle splitting without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance bundle splitting?', 'Teams ship without field measurement—web performance bundle splitting failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance bundle splitting?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance bundle splitting changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-captcha-alternatives-ux": (
    "We shipped web performance captcha alternatives ux and discovered the gap between documentation and production the hard way.",
    "web performance captcha alternatives ux",
    "when web performance captcha alternatives ux affects users on critical paths",
    "Rolling out web performance captcha alternatives ux without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance captcha alternatives ux?', 'Teams ship without field measurement—web performance captcha alternatives ux failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance captcha alternatives ux?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance captcha alternatives ux changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-code-splitting-granularity": (
    "We shipped web performance code splitting granularity and discovered the gap between documentation and production the hard way.",
    "web performance code splitting granularity",
    "when web performance code splitting granularity affects users on critical paths",
    "Rolling out web performance code splitting granularity without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance code splitting granularity?', 'Teams ship without field measurement—web performance code splitting granularity failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance code splitting granularity?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance code splitting granularity changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-command-palette-keyboard": (
    "We shipped web performance command palette keyboard and discovered the gap between documentation and production the hard way.",
    "web performance command palette keyboard",
    "when web performance command palette keyboard affects users on critical paths",
    "Rolling out web performance command palette keyboard without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance command palette keyboard?', 'Teams ship without field measurement—web performance command palette keyboard failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance command palette keyboard?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance command palette keyboard changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-composite-layers-gpu": (
    "We shipped web performance composite layers gpu and discovered the gap between documentation and production the hard way.",
    "web performance composite layers gpu",
    "when web performance composite layers gpu affects users on critical paths",
    "Rolling out web performance composite layers gpu without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance composite layers gpu?', 'Teams ship without field measurement—web performance composite layers gpu failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance composite layers gpu?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance composite layers gpu changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-core-web-vitals": (
    "Search Console flagged forty percent of product pages on LCP until preload, font-display swap, and banner space fixes.",
    "web performance core web vitals",
    "when web performance core web vitals affects users on critical paths",
    "Rolling out web performance core web vitals without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance core web vitals?', 'Teams ship without field measurement—web performance core web vitals failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance core web vitals?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance core web vitals changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-data-table-virtualization": (
    "We shipped web performance data table virtualization and discovered the gap between documentation and production the hard way.",
    "web performance data table virtualization",
    "when web performance data table virtualization affects users on critical paths",
    "Rolling out web performance data table virtualization without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance data table virtualization?', 'Teams ship without field measurement—web performance data table virtualization failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance data table virtualization?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance data table virtualization changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-debounce-throttle-input": (
    "We shipped web performance debounce throttle input and discovered the gap between documentation and production the hard way.",
    "web performance debounce throttle input",
    "when web performance debounce throttle input affects users on critical paths",
    "Rolling out web performance debounce throttle input without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance debounce throttle input?', 'Teams ship without field measurement—web performance debounce throttle input failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance debounce throttle input?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance debounce throttle input changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-document-visibility-api": (
    "We shipped web performance document visibility api and discovered the gap between documentation and production the hard way.",
    "web performance document visibility api",
    "when web performance document visibility api affects users on critical paths",
    "Rolling out web performance document visibility api without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance document visibility api?', 'Teams ship without field measurement—web performance document visibility api failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance document visibility api?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance document visibility api changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-early-hints-103": (
    "We shipped web performance early hints 103 and discovered the gap between documentation and production the hard way.",
    "web performance early hints 103",
    "when web performance early hints 103 affects users on critical paths",
    "Rolling out web performance early hints 103 without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance early hints 103?', 'Teams ship without field measurement—web performance early hints 103 failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance early hints 103?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance early hints 103 changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-element-timing-lcp": (
    "We shipped web performance element timing lcp and discovered the gap between documentation and production the hard way.",
    "web performance element timing lcp",
    "when web performance element timing lcp affects users on critical paths",
    "Rolling out web performance element timing lcp without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance element timing lcp?', 'Teams ship without field measurement—web performance element timing lcp failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance element timing lcp?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance element timing lcp changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-empty-state-design": (
    "We shipped web performance empty state design and discovered the gap between documentation and production the hard way.",
    "web performance empty state design",
    "when web performance empty state design affects users on critical paths",
    "Rolling out web performance empty state design without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance empty state design?', 'Teams ship without field measurement—web performance empty state design failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance empty state design?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance empty state design changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-error-recovery-retry-ui": (
    "We shipped web performance error recovery retry ui and discovered the gap between documentation and production the hard way.",
    "web performance error recovery retry ui",
    "when web performance error recovery retry ui affects users on critical paths",
    "Rolling out web performance error recovery retry ui without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance error recovery retry ui?', 'Teams ship without field measurement—web performance error recovery retry ui failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance error recovery retry ui?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance error recovery retry ui changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-filter-chip-interfaces": (
    "We shipped web performance filter chip interfaces and discovered the gap between documentation and production the hard way.",
    "web performance filter chip interfaces",
    "when web performance filter chip interfaces affects users on critical paths",
    "Rolling out web performance filter chip interfaces without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance filter chip interfaces?', 'Teams ship without field measurement—web performance filter chip interfaces failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance filter chip interfaces?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance filter chip interfaces changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-font-loading": (
    "Web fonts blocked rendering 1.1 seconds until self-hosting, preload, and metric-matched fallbacks.",
    "web performance font loading",
    "when web performance font loading affects users on critical paths",
    "Rolling out web performance font loading without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance font loading?', 'Teams ship without field measurement—web performance font loading failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance font loading?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance font loading changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-http2-multiplexing-assets": (
    "We shipped web performance http2 multiplexing assets and discovered the gap between documentation and production the hard way.",
    "web performance http2 multiplexing assets",
    "when web performance http2 multiplexing assets affects users on critical paths",
    "Rolling out web performance http2 multiplexing assets without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance http2 multiplexing assets?', 'Teams ship without field measurement—web performance http2 multiplexing assets failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance http2 multiplexing assets?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance http2 multiplexing assets changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-http3-quic-benefits": (
    "We shipped web performance http3 quic benefits and discovered the gap between documentation and production the hard way.",
    "web performance http3 quic benefits",
    "when web performance http3 quic benefits affects users on critical paths",
    "Rolling out web performance http3 quic benefits without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance http3 quic benefits?', 'Teams ship without field measurement—web performance http3 quic benefits failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance http3 quic benefits?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance http3 quic benefits changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-image-formats-avif": (
    "Hero AVIF cut transfer forty-two percent versus JPEG with no visible quality loss at equivalent settings.",
    "web performance image formats avif",
    "when web performance image formats avif affects users on critical paths",
    "Rolling out web performance image formats avif without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance image formats avif?', 'Teams ship without field measurement—web performance image formats avif failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance image formats avif?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance image formats avif changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-import-maps-cdn": (
    "We shipped web performance import maps cdn and discovered the gap between documentation and production the hard way.",
    "web performance import maps cdn",
    "when web performance import maps cdn affects users on critical paths",
    "Rolling out web performance import maps cdn without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance import maps cdn?', 'Teams ship without field measurement—web performance import maps cdn failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance import maps cdn?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance import maps cdn changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-inline-validation-timing": (
    "We shipped web performance inline validation timing and discovered the gap between documentation and production the hard way.",
    "web performance inline validation timing",
    "when web performance inline validation timing affects users on critical paths",
    "Rolling out web performance inline validation timing without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance inline validation timing?', 'Teams ship without field measurement—web performance inline validation timing failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance inline validation timing?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance inline validation timing changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-inp-interaction": (
    "Filter clicks took four hundred eighty ms until we virtualized the list and yielded on the main thread.",
    "web performance inp interaction",
    "when web performance inp interaction affects users on critical paths",
    "Rolling out web performance inp interaction without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance inp interaction?', 'Teams ship without field measurement—web performance inp interaction failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance inp interaction?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance inp interaction changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-intersection-observer-debounce": (
    "We shipped web performance intersection observer debounce and discovered the gap between documentation and production the hard way.",
    "web performance intersection observer debounce",
    "when web performance intersection observer debounce affects users on critical paths",
    "Rolling out web performance intersection observer debounce without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance intersection observer debounce?', 'Teams ship without field measurement—web performance intersection observer debounce failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance intersection observer debounce?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance intersection observer debounce changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-islands-architecture": (
    "We shipped web performance islands architecture and discovered the gap between documentation and production the hard way.",
    "web performance islands architecture",
    "when web performance islands architecture affects users on critical paths",
    "Rolling out web performance islands architecture without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance islands architecture?', 'Teams ship without field measurement—web performance islands architecture failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance islands architecture?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance islands architecture changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-layout-shift-debugging": (
    "We shipped web performance layout shift debugging and discovered the gap between documentation and production the hard way.",
    "web performance layout shift debugging",
    "when web performance layout shift debugging affects users on critical paths",
    "Rolling out web performance layout shift debugging without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance layout shift debugging?', 'Teams ship without field measurement—web performance layout shift debugging failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance layout shift debugging?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance layout shift debugging changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-lcp-optimization": (
    "LCP was 4.2s—TTFB and render-blocking CSS delayed hero discovery more than image bytes.",
    "web performance lcp optimization",
    "when web performance lcp optimization affects users on critical paths",
    "Rolling out web performance lcp optimization without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance lcp optimization?', 'Teams ship without field measurement—web performance lcp optimization failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance lcp optimization?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance lcp optimization changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-loading-state-hierarchy": (
    "We shipped web performance loading state hierarchy and discovered the gap between documentation and production the hard way.",
    "web performance loading state hierarchy",
    "when web performance loading state hierarchy affects users on critical paths",
    "Rolling out web performance loading state hierarchy without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance loading state hierarchy?', 'Teams ship without field measurement—web performance loading state hierarchy failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance loading state hierarchy?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance loading state hierarchy changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-long-tasks-monitoring": (
    "We shipped web performance long tasks monitoring and discovered the gap between documentation and production the hard way.",
    "web performance long tasks monitoring",
    "when web performance long tasks monitoring affects users on critical paths",
    "Rolling out web performance long tasks monitoring without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance long tasks monitoring?', 'Teams ship without field measurement—web performance long tasks monitoring failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance long tasks monitoring?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance long tasks monitoring changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-main-thread-work": (
    "We shipped web performance main thread work and discovered the gap between documentation and production the hard way.",
    "web performance main thread work",
    "when web performance main thread work affects users on critical paths",
    "Rolling out web performance main thread work without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance main thread work?', 'Teams ship without field measurement—web performance main thread work failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance main thread work?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance main thread work changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-maintenance-mode-page": (
    "We shipped web performance maintenance mode page and discovered the gap between documentation and production the hard way.",
    "web performance maintenance mode page",
    "when web performance maintenance mode page affects users on critical paths",
    "Rolling out web performance maintenance mode page without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance maintenance mode page?', 'Teams ship without field measurement—web performance maintenance mode page failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance maintenance mode page?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance maintenance mode page changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
  "web-performance-memory-leak-detection": (
    "We shipped web performance memory leak detection and discovered the gap between documentation and production the hard way.",
    "web performance memory leak detection",
    "when web performance memory leak detection affects users on critical paths",
    "Rolling out web performance memory leak detection without field measurement, rollback, or accessibility checks",
    [('What is the main production risk with web performance memory leak detection?', 'Teams ship without field measurement—web performance memory leak detection failures appear as silent UX regressions, cost drift, or audit findings rather than clear errors.'), ('When should we prioritize web performance memory leak detection?', 'Prioritize when user research, CrUX, support tickets, or compliance requirements show pain on critical paths—not when a checklist mentions it abstractly.'), ('How do we validate web performance memory leak detection changes?', 'Baseline RUM before changes, compare p75 after deploy, and keep rollback via feature flags or cache purge documented in the PR.')],
  ),
}