#!/usr/bin/env python3
"""Wave-3 blog generator entrypoint. Topics live in scripts/wave3/topics.jsonl."""
print("Topics and posts were generated by the wave3 rebuild script. Re-run the cloud agent rebuild if you need to regenerate.")
